- npm-shrinkwrap.json
- package.json
The many npm-shrinkwrap.json changes are mostly noise, e.g. the `from` field changing from URLs to version numbers for reasons I don't understand.  I manually sanity-checked it in `git diff` output and it seemed sensible.
> Update hapi to latest stable version.

- tokens/password_change_token.js
We attach `verifyHash` and `authSalt` properties to PasswordChangeToken instances, but I can't work out why or whether they're actually used.  All the tests still pass if I remove them, so perhaps they are vestigial?
> Remove unused data from the PasswordChangeToken class.

- test/load/loadtests.py
Fixes #836.
This updates the loadtests to more closely match observed prod traffic patterns, per https://bugzilla.mozilla.org/show_bug.cgi?id=1097584.  Depends on #844.
In particular, it throws in a whole lotta is-this-account-verified-yet polling.  I'm not sure we actually *should* be skewing quite so much towards that single request, but it does reflect production realities.
@jrgm r?
> Update loadtest to be more similar to production traffic breakdown

- config/config.js
- test/remote/password_forgot_tests.js
Fixes #845.
@dannycoates r?  Do we tweak these values in any production config?  I couldn't find it if so...
> Increase default token lifetimes to 30mins.

- package.json
Just happened to notice this outdated line. If folks have a better description, let me know.
> change package.json description to refer to Firefox Accounts, not 'PiCl'

- routes/account.js
- routes/utils/password_check.js
- test/local/password_check_test.js
This will allow us to deploy the lockout code preffed off, but still get metrics on how often it would have triggered if it were enabled.  It would be good to have this in train-32 when the account lockout stuff starts to hit prod.
I also switched from `log.event` to `log.info` since the "events" things are special-purpose account lifecycle events designed to be consumed by downstream services, e.g. telling sync to delete a user's data if they delete their account.
@shane-tomlinson r?
> Log account lockout events even if we don't actually do the lockout.

- npm-shrinkwrap.json
- package.json
Older versions of scrypt-hash depend on the processor supporting SSE instructions, in newer versions there is also an alternative implementation. This patch enables fxa-auth-server to build on ARM.
> Enable build on ARM platforms (including Raspberry Pi)

- npm-shrinkwrap.json
Related to https://github.com/mozilla/fxa-auth-mailer/issue/31 and https://github.com/mozilla/fxa-auth-mailer/pull/32, this (ab)use of shrinkwrap will cause npm to put the strings used in train-31. This means we don't get 'Almost There' translated in some languages (not all locales have translated it yet), but we get back the translations of the email `Subject:` header for 'Verify your account' and 'Reset your password'.
> for train-32 only, a heinous hack to get email subjects back

- routes/account.js
- routes/utils/password_check.js
A PII scrubber is choking on the '[123, 65, 21, ...]' formatting, and it should be .toString('hex')
r? @rfk
> fix(logging): log emailRecord.uid as a hex string, not a byte array

- grunttasks/bump.js
- grunttasks/copyright.js
- grunttasks/jshint.js
- grunttasks/version.js
- npm-shrinkwrap.json
- package.json
Folks can `git clone https://github.com/jrgm/fxa-auth-server/tree/add-version-task` and then try doing edit Changelog, `grunt version` or `grunt version:patch`, look at git log -3, and git tags, etc.. To get back to the original state,  do `git tag -d v1.33.0` (or whatever), and then do `git reset --hard origin/add-version-task`. 
@rfkelly, @dannycoates, @chilts - try it out and r?
> chore(release): add tasks "grunt version" and "grunt version:patch" to create release tags

- npm-shrinkwrap.json
Picks up subject lines and lockout strings.
> chore(shrinkwrap): get latest fxa-content-server-l10n version

- scripts/e2e-email/index.js
- scripts/e2e-email/localeQuirks.js
- scripts/e2e-email/p-request.js
This script will, for each locale, create an account, forget the password, and lock then try to unlock the account, then gathers up the emails at restmail and performs checks against the headers for that localized content. (Mostly intended for use in stage; will currently fail if run against prod, since /v1/account/lock is not available in production). 
r?
> test(email): script to check delivery and content for all production locales

- db/httpdb.js
Currently we set `verifierSetAt` inside createAccount() but we don't
for resetAccount(). This change mirrors that. Furthermore, the db-mem
and db-mysql backends set this field but that logic should be contained
here, rather than in the dumb backends.
> fix(httpdb): Set verifierSetAt for resetAccount()

- scripts/e2e-email/index.js
- scripts/e2e-email/localeQuirks.js
- adds an option that I found useful
- updates entry for 'es'
> fix(options): -L, --locale <en[,zh-TW,de,...]>; Test only this csv list of locales

- scripts/e2e-email/localeQuirks.js
Translations are coming in slowly for `'Re-verify your account'` and some others. (It sucks to have to maintain this meta-list, but it's better than not knowing if things have regressed to untranslated cycle-to-cycle).
> fix(tests): update for some locales that have now translated fxa-auth-mailer strings

- scripts/e2e-email/localeQuirks.js
This change https://github.com/mozilla-services/puppet-config/pull/1230 will allow translations for uk,hsb,lsb available, and also changes the default language to `en` to match what fxa-content-server does.
> fix(tests): a config update now makes uk,hsb,dsb available

- mailer.js
To match https://github.com/mozilla/fxa-auth-mailer/pull/40/.
> fix(l10n): pass config.i18n.defaultLanguage to fxa-auth-mailer

- config/config.js
- config/supportedLanguages.js
- mailer.js
- npm-shrinkwrap.json
- scripts/check-i18n.js
- scripts/e2e-email/index.js
- scripts/test-local.sh
- test/local/mailer_locales_tests.js
Splits out the list of supported locales, and add a "non-binding" test that we are still using the same locales that are used by the fxa-content-server. Fixes #914 
Locales that change with this PR are: en is used instead of en-US, and adds locales dsb, hsb, sv-SE, and uk. This matches what is currently used in production with this temporary puppet config change - https://github.com/mozilla-services/puppet-config/commit/18cdef8d157005231b04b2696671481d2f56c6d5#diff-0abe6433b87b21a40477a4c94164078a
@dannycoates, @rfk, @chilts  - r?
> Check that we are using same locales as fxa-content-server

- routes/idp.js
- test/remote/misc_tests.js
fixes the content-server test caused by #902
> to support legacy jwcrypto .well-known/browserid must be base 10

- .travis.yml
Since Travis uses the same semantics as nvm we can test on both
io.js v1.x and v2.x: https://github.com/creationix/nvm#usage
> build(travis): Test on both io.js v1 and v2

- pool.js
Following https://github.com/mozilla/fxa-auth-db-mysql/issues/9 we
should stop retrying requests to the db-server so we're more explicit
about what is happening.
Fixes #921.
> fix(pool): Stop retrying requests to db-server

- config/dev.json
We need this to test the permission screen in the preVerified signup flow.
@vladikoff r? Do we need to configure something like this for fxa-dev too?
> tests(preverify): add 321done to trusted jkus for dev

- lib/log.js
- npm-shrinkwrap.json
- package.json
closes #879 
@jrgm and @whd this changes the log output to mozlog json format.
This also retires the `domain` tracing that hasn't been use for a while.
> switch from bunyan to mozlog

- npm-shrinkwrap.json
Picks up most recent translations in git://github.com/mozilla/fxa-content-server-l10n.git, and also picks up code rearrangement in git://github.com/mozilla/fxa-auth-db-server.git, which is used in testing.
> chore(shrinkwrap): update npm-shrinkwrap mostly to update fxa-content-server-l10n for mailer

- test/local/db_tests.js
This fixes an issue where the `tap` runner would exit early because the tests weren't registered until the `DB.connect()` promise resolved. This meant that, occasionally, none of the tests would run...but show as passing! :smile_cat:
> Ensure the DB unit tests always run

- config/index.js
- lib/server.js
This is to fix https://github.com/mozilla/fxa-auth-server/issues/741
> Renaming toolbusy config option to maxEventLoopDelay

- npm-shrinkwrap.json
- package.json
update the version of node-ass that we use to the same as used in fxa-auth-db-server and fxa-auth-db-mysql (which I should make the npm available version, but for now...). 
Fixes #938 and the problem in general if you don't have a `~/tmp` directory or `$TMPDIR` or `$TEMP` defined.
> fix(test): use a version of node-ass with updated node-temp

- lib/routes/utils/password_check.js
This removes the operative change in GH-943, which puts things back in a working state. Breakfix. 
A correct fix can happen later.
> fix(password): revert part of GH-943; currently in broken state

- npm-shrinkwrap.json
Just need to bump shrinkwrap to allow a version of fxa-content-server-l10n to be used. This is for the train-39 branch.
@dannycoates - r?
> fix(l10n): pick up latest content l10n to fix Slovenian and Pt-BR mails

- npm-shrinkwrap.json
Picking up latest in these repos:
```
-      "from": "git+https://github.com/mozilla/fxa-auth-mailer.git#e35e7dd1ceb5046da5e8877cac4288738b81ba90",
+      "from": "git+https://github.com/mozilla/fxa-auth-mailer.git#31612d4a28ebd3be4a91245e9b0614cafbf9323f",
-      "from": "git://github.com/mozilla/fxa-content-server-l10n.git#aa9ff58c9673444616d6f993bcdebb89a81792ab",
+      "from": "git://github.com/mozilla/fxa-content-server-l10n.git#f1c8b0c9931153f7decea298fa00c6d9eb3102ed",
```
> chore(shrinkwrap): update shrinkwrap, notably for git fxa-auth-mailer and fxa-content-server-l10n

- scripts/e2e-email/index.js
- scripts/e2e-email/localeQuirks.js
Kinda ugly with the number of locales not up to date, but it's the current state. r? @rfk
> tests(e2e-email): updates to reflect current l10n state in train-41

- lib/routes/account.js
- lib/routes/password.js
- test/client/api.js
- test/remote/account_create_tests.js
- test/remote/password_forgot_tests.js
Fixes #961.
Accepts a `service` query parameter on the following endpoints:
* `/account/create`
* `/account/login`
* `/password/forgot/send_code`
Note that a new test hasn't been added for `/account/login`, because I couldn't find anything to assert against. I'm happy to add one if somebody can point out a good way to assert that the parameter worked. Tests are added for the other two routes.
> fix(api): accept service as a query parameter

- lib/error.js
- test/local/error_tests.js
Fixes #419.
The issue just mentions Joi errors but it turns out the invalid parameter case was already handled, so this changeset only adds handling for the missing parameter case.
The change works by checking the `message` property of the Joi error. It is definitely a hackish approach, but I can't see another way to do it without modifying Joi itself.
I've limited the hackishness as much as possible by importing the comparison string from Joi directly, rather than hard-coding it ourselves. I've also added a unit test that ensures the relied-upon string actually exists in Joi, which further mitigates the hack (I think).
There were no tests at all for the error module before this. I've added some to cover what I've done here, but I haven't gone further to test the rest of the module.
> fix(errors): convert missing parameter errors correctly

- npm-shrinkwrap.json
- test/local/db_tests.js
- test/remote/account_create_tests.js
This PR addresses other bugs related to https://github.com/mozilla/fxa-auth-server/issues/993
I ordinarily wouldn't put these patches into one PR, except all 3 are needed to get the tests, locally and on travis, to pass again.
You may want to review each commit separately, which makes it clear(er) what changes what.
1) fix(tests): verifyHash should no longer be returned
- See https://github.com/mozilla/fxa-auth-db-mysql/issues/47. Changes this
from expecting to not expecting verifyHash in the returned message, similar
to changes in https://github.com/mozilla/fxa-auth-db-server/pull/143/files
2) fix(tests): skip 3 pt-BR specific tests due to no translation yet
- we have new content for emails sent
https://github.com/mozilla/fxa-auth-mailer/pull/48/files but we don't yet
have translations …
> Fixes for test failures in #993 and an update to shrinkwrap

- test/remote/account_unlock_tests.js
- test/remote/password_forgot_tests.js
- test/remote/recovery_email_verify_tests.js
I've had this on a branch for eons and keep neglecting to make this PR.  This is used as REDIRECT_DOMAIN=my.test.domain tap ...
@dannycoates - r?
> fix(tests): make smtp.redirectDomain configurable in remote tests

- npm-shrinkwrap.json
- package.json
- scripts/start-local.sh
- test/local/verifier_upgrade_tests.js
- test/test_server.js
This is a pre-requisite for any changes that depend on incoming db changes, now that the db repos have been merged into `fxa-auth-db-mysql`.
> chore(deps): switch from db-mem to db-mysql

- lib/crypto/butil.js
- lib/db.js
- lib/routes/account.js
- lib/routes/session.js
- lib/routes/sign.js
- lib/tokens/session_token.js
- lib/userAgent.js
- npm-shrinkwrap.json
- package.json
- test/local/butil_tests.js
- test/local/db_tests.js
- test/local/user_agent_tests.js
Fixes https://github.com/mozilla/fxa-auth-server/issues/983.
Depends on #1000 and https://github.com/mozilla/fxa-auth-db-mysql/pull/65, requires a dependency-update and a rebase after those are fixed and then the tests should all pass.
Creates session tokens with the new `uaBrowser`, `uaBrowserVersion`, `uaOS`, `uaOSVersion`, `deviceType` and `lastAccessTime` fields and updates those fields whenever the session token is used.
> feat(db): store user agent and last-access time in sessionTokens

- README.md
I've done this speculatively, just because I happened to notice it when I was [updating the docs](https://github.com/mozilla/fxa-auth-db-mysql/issues/73) for `fxa-auth-db-mysql`. Presumably it doesn't belong here any more?
> chore(docs): remove stale db info from the readme

- lib/routes/defaults.js
- test/local/base_path_tests.js
- test/remote/misc_tests.js
Adds the source repo to '/' and a new '/__version__' route. Fixes #1005 
Became a bit of a yak shave. Easier to review as two commits, https://github.com/mozilla/fxa-auth-server/commit/a79d2b027b8a94ee81ec2b3774cfa84f850ccbb9?w=1 (with `diff -w`), and https://github.com/mozilla/fxa-auth-server/commit/842799f7d32ca3b7b32658f1e3ac77ce31189af6 (with --yak-shave).
> chore(version): add /__version__ route; add source repo based on origin; simplify routes/default

- lib/db.js
- lib/pool.js
- test/local/pool_tests.js
Fixes #1003 and (indirectly) fixes https://github.com/mozilla/fxa-auth-db-mysql/issues/51 by virtue of being the last bit of work listed for that issue.
The fix also required changing `lib/pool.js` because previously it was only parsing body data in the success condition, whereas we actually need the body data to get the `errno` property. That module was untested so I also took the time to write a bunch of tests for it.
Two new dev dependencies are added, `proxyquire` and `sinon`.
> fix(server): check errno on database errors

- lib/userAgent.js
- test/local/db_tests.js
- test/local/user_agent_tests.js
Fixes #1010.
If `ua-parser` doesn't return a device type, compare the OS to a list of known mobile OS' to determine whether or not the user agent is on a mobile device.
I derived the list of operating systems in `isMobileOS` from tests of `ua-parser` against [this list of mobile user-agent strings](http://www.useragentstring.com/pages/Mobile%20Browserlist/). I then added `iOS`, `Firefox OS`  and `BlackBerry OS` to the list of failing cases for completeness / just to be on the safe side.
The thing I'm most worried about is that I may have gone too far in my quest for correctness. What is the sane cut-off point between ensuring we have good enough metrics and unnecessarily performing string comparisons against operating systems nobody has ever heard of? I'm happy to chop some. :smile:
> fix(server): improve identification of mobile user agents

- lib/routes/defaults.js
- test/local/base_path_tests.js
- test/remote/misc_tests.js
I know I just added this, but seeing this in practice, the source is (usually) the least interesting information in this output compared to versions/shas, so it should be last.
Before:
```
{"source":"https://github.com/mozilla/fxa-auth-server.git","version":"1.42.0","commit":"94745ee21541be27e2308fe0c677aa49f8c3bd7b"}`
```
After:
```
{"version":"1.42.0","commit":"94745ee21541be27e2308fe0c677aa49f8c3bd7b","source":"https://github.com/mozilla/fxa-auth-server.git"}
```
> chore(version): display source repo last in {/ver.json,/__version__}

- bin/notifier.js
So, bad news. When the logging was refactored to mozlog mid-to-late May, this line was left behind, which throws but that exception is caught and swallowed. Things then continue silently from there with a default sns.publish.
> fix(notifier): calling undefined "log" throws

- bin/key_server.js
- config/index.js
- lib/db.js
- lib/routes/account.js
- lib/routes/index.js
- npm-shrinkwrap.json
- package.json
- test/local/openid_tests.js
- test/ptaptest.js
This adds the ability to create and login to FxA using an OpenID 2.0 identity provider (IDP).
`/account/openid/authenticate` - initiates the flow which redirects to the 3rd party IDP
`/account/openid/login` - the return target from the IDP which either creates a new account or logs in an existing user, then redirects to the content-server to log the user into Sync.
I've left these undocumented in `api.md` for now because they're fairly experimental an not for "public" consumption.
```json
{
"openIdProviders": ["https://me.example.com"]
}
```
An array of OpenID identifier prefixes that are allowed to use an OpenID based account. This allows us to limit which providers we allow to create these accounts. Initially it can be, and defaults to, empty.
> OpenID login support

- test/load/loadtests.py
@rfk had two related PRs for loadtesting:
https://github.com/mozilla/fxa-auth-server/pull/844 'Use shiny new PyFxA library for the python loadtests'
and https://github.com/mozilla/fxa-auth-server/pull/851 'Update loadtest to be more similar to production traffic breakdown', which contained the commit to use PyFxA
The PRs were setup to merge #844 rfk/use-pyfxa-for-loadtests into master, and merge #851 rfk/make-loadtests-match-prod-traffic into rfk/use-pyfxa-for-loadtests. 
So, #851 was to be merged first, and then #844. However, I merged #844 and then #851, which means rfk/make-loadtests-match-prod-traffic never merged into master. However, since rfk/make-loadtests-match-prod-traffic had all the bits necessary to run correctly, it worked fine. 
This PR just brings the commits from …
> Update loadtest to be more similar to production traffic breakdown - redux

- lib/db.js
- lib/routes/account.js
- lib/routes/session.js
- lib/userAgent.js
- test/local/db_tests.js
- test/local/user_agent_tests.js
This is a continuation from https://github.com/mozilla/fxa-auth-server/pull/1039, which was opened against the `train-44` branch.
As per discussion in that PR, this change limits session token updates to just the `/certificate/sign` endpoint, and only in the case where the user agent has changed or they've not been updated in the past hour.
The changes to `lib/userAgent.js` were necessary to make the new comparisons work with null fields from the database.
@rfk & @jrgm r?
> fix(db): decrease session token update frequency

- lib/db.js
- lib/routes/sign.js
- lib/tokens/session_token.js
- test/local/db_tests.js
- test/local/session_token_tests.js
This addresses [feedback](https://github.com/mozilla/fxa-auth-server/pull/1042#discussion_r38881438) from #1042, refactoring the checks around session token updates to the `SessionToken` object.
Fwiw, the name of `DB.prototype.updateSessionTokenInBackground` bothers me, now that it is only called from one place. I felt a bit iffy about it before because the backgroundness doesn't come from the function itself, which returns a promise like the other `DB` methods, but from the caller choosing to ignore said promise.
Now that only one of those callers remains, it strikes me that some commentary at the call site might be a more appropriate place to point out that we're not waiting for a response. Would it be okay to rename it to `updateSessionToken` in this commit and add such a comment …
> fix(db): properly encapsulate session token update logic

- config/index.js
This backports the config-related parts of #1034 from `master` onto `train-45` branch, which should allow the train to be deployed with the latest version of auth-mailer strings.  Fixes https://github.com/mozilla/fxa-auth-mailer/issues/75.
@jrgm r? for patch release of train-45
> fix(email): Backport auth-mailer config changes from master.

- .travis.yml
- scripts/start-local-test-mysql.sh
- test/local/verifier_upgrade_tests.js
Hey, @vladikoff. I was reviewing your GH-1047, and there were a problem: $DB, not DB (so it wasn't actually running against the database ;-) A way to test the test is to add `sleep 20; mysql -uroot 'drop database if exists fxa'`; that better fail if the tests are using the database).
But running against the database revealed that test/local/verifier_upgrade_tests.js is flaky on travis (passes on my local osx with a database; maybe it shouldn't but it does). Adding this try-catch corrects one definitely failure I reproduced running tests on linux, but that test is still flaky. I've taken several approaches in re-writing that test to not be as flaky on travis, and some were better, but still not solid. 
Anyways, this is a PR to your PR. You may just want to merge this in manually and close …
> fix(tests): run mysql tests on travis, moar

- bin/basket.js
- lib/db.js
- lib/routes/account.js
- test/local/basket_tests.js
- test/local/db_tests.js
Fixes #1038.
`bin/basket.js` has been fairly heavily refactored so that the two message handlers can share common code. I've called the new message `login` but I was a bit unsure about it because there is some `login`/`signin` duality in the surrounding code. Are those terms completely interchangeable or is there some subtle contextual difference between the two? Is one of them generally preferable to the other?
There is a small gap in the test coverage but plugging it is going to be time-consuming, so I wanted to check here first: there are no assertions that the call to `log.event` is made correctly from the route handler. Fwiw, there are also no equivalent assertions for existing calls to `log.event`.
Elsewhere, there were no tests at all for the basket stuff previously and this PR …
> feat(basket): send sync login events to basket

- npm-shrinkwrap.json
The production/stage builds would not start because they couldn't find pem-jwk. Shrug.
> chore(shrinkwrap): redo shrinkwrap to re-add missing fxa-jwtool->pem-jwk

- lib/log.js
- lib/routes/account.js
- lib/routes/sign.js
- lib/tokens/session_token.js
- test/local/log_tests.js
- test/local/session_token_tests.js
Fixes #1027, sending the value of `account.createdAt` with the `account.signed` activity event. The data should be processed by a Heka filter as per https://github.com/mozilla/fxa-auth-db-mysql/issues/86.
While modifying `log.activityEvent`, I noticed that it wasn't allowing `service` to be set on the query string, which was already fixed everywhere else in https://github.com/mozilla/fxa-auth-server/pull/984. Seeing as I was writing tests for that function anyway, I took the liberty of fixing it here too and adding a test.
> feat(logging): add createdAt to account.signed activity event

- npm-shrinkwrap.json
Updates:
fxa-auth-mailer: df59422 -> 62c023e
fxa-content-server-l10n.git: 2ec3304 -> 6e90937
and removes commander, which is a dev dependency, and I think got in there from my e2e-scripts PR.
Note: I did `/bin/rm -rf ./node_modules npm-shrinkwrap.json; npm install --production; npm ls; npm shrinkwrap` to produce this. Other patterns were giving me stuff that wouldn't work (missing dependencies after re-install). Maybe npm@3, someday, has solved this madness.
> chore(shrinkwrap): update shrinkwrap for latest fxa-auth-mailer, fxa-content-server-l10n

- lib/log.js
- lib/metrics/statsd.js
- lib/routes/account.js
- test/local/statsd_tests.js
Fixes https://github.com/mozilla/fxa-content-server/issues/3046.
The existing log functions are unsuitable for this event because we want to send the data to statsd as a timing. Hence I've added new `timing` methods to `lib/log.js` and `lib/metrics/statsd.js`, following a similar approach to `log.increment`.
> feat(metrics): send account verification time to statsd

- config/supportedLanguages.js
fixes mozilla/fxa-content-server#3125, ref mozilla/fxa-content-server#3126
@jrgm - r?
> feat(i18n): Enable Romainian `ro` support.

- npm-shrinkwrap.json
- test/local/mailer_locales_tests.js
Update shrinkwrap, principally for
fxa-auth-mailer.git : from 62c023e to 93b0f31
fxa-content-server-l10n.git : from 6e90937 to fa01545
r? - @rfk
> Update shrinkwrap and fix test expectation for new l10n content

- config/index.js
- docs/api.md
- lib/server.js
- package.json
- test/client/api.js
- test/remote/misc_tests.js
Fixes #550, adding a config option to set the `Access-Control-Allow-Origin` response header on most endpoints.
~~There are two endpoints that it doesn't affect:~~
* ~~`POST /v1/account/unlock/verify_code`~~
* ~~`POST /v1/recovery_email/verify_code`~~
~~As per [the documentation](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-v1accountunlockverify_code), those may be accessed from different domains so must always set the header to `*`.~~
~~For the other endpoints,~~ the default setting is ~~also~~ `*` but it can be over-ridden by setting the `CORS_ORIGIN` environment variable.
For the tests, I tried to modify the test client object in the least intrusive way possible, so that I could assert the header was being set correctly without having to update every usage of …
> feat(server): support stricter access-control origin on most endpoints

- lib/routes/account.js
- test/remote/account_login_tests.js
@vladikoff here's an alternative to your #1083 that zaps the sending at its source, and removes the offending test; r?
Fixes mozilla/fxa-auth-mailer#96
> fix(email): stop sending new sync device emails

- config/index.js
- lib/error.js
- lib/routes/account.js
- lib/server.js
- npm-shrinkwrap.json
- package.json
- test/client/api.js
- test/client/index.js
- test/config/mock_oauth.json
- test/local/concurrent_tests.js
- test/oauth_helper.js
- test/remote/account_profile_tests.js
- test/test_server.js
A preliminary suggestion for how /account/profile might work, posting for feedback.  Needs docs before final merge.  @seanmonstar care to take a look?
Fixes #1053.
> feat(profile): Add oauth-authenticated /account/profile endpoint.

- lib/routes/account.js
- test/remote/account_profile_tests.js
Part of the fix for the backout in https://github.com/mozilla/fxa-profile-server/pull/171.  @seanmonstar r?
> fix(oauth): look for the correct 'scope' param in oauth response, not 'scopes'

- docs/api.md
- docs/endpoint_data.md
- docs/schema.md
- lib/db.js
- lib/error.js
- lib/routes/account.js
- npm-shrinkwrap.json
- test/client/api.js
- test/client/index.js
- test/local/db_tests.js
- test/remote/device_tests.js
This change is entirely predicated on the acceptance (or otherwise) of https://github.com/mozilla/fxa-auth-db-mysql/pull/116, hence the `WIP` label. However, because I'm keen to try and get this into train 50 if at all possible, I'm opening the PR now in the hope of getting the review process underway ASAP.
Just to be ultra-clear, **these changes can't be merged until after https://github.com/mozilla/fxa-auth-db-mysql/pull/116 is merged**.
For detailed requirements concerning this API, see [the feature readme](https://github.com/mozilla/fxa/blob/master/features/FxA-45-device-registration-api/README.md).
@rfk and/or @dannycoates, if either of you have time it would be awesome to get some feedback on this. Also, @shane-tomlinson, you may or may not be interested depending on other, far more …
> feat(server): implement device registration api

- lib/routes/account.js
- test/remote/device_tests.js
There were a couple gaps in the device registration tests that allowed inconsistent validation to fail `GET /account/devices` requests, if fields were unset or had been set to the empty string.
This PR adds the appropriate tests and harmonises the validation rules across all endpoints so that the tests succeed.
Apologies for this slipping through in the original device registration PR, I'm annoyed with myself about it. I had a bit of a blind spot because the schemata started out stricter than they are now, so the new tests only became necessary later on.
> fix(server): eliminate device validation discrepancies

- docs/api.md
- docs/endpoint_data.md
- lib/routes/account.js
- test/remote/device_tests.js
Fixes #1119.
Previously, `/account/devices` was returning a session token id, something of a chocolate teapot for clients. This change replaces that with a boolean for each device, indicating whether it is the owner of the current session.
The clients need updating after this is merged.
> fix(server): return isCurrentDevice from /account/devices

- lib/routes/account.js
- npm-shrinkwrap.json
- test/remote/device_tests.js
Fixes #1123 but depends on changes in https://github.com/mozilla/fxa-auth-db-mysql/pull/117 so **do not merge until after that PR has been accepted**.
This issue was caused by my misunderstanding of Joi's `optional()`, which doesn't permit `null` values. It was exacerbated by yet another gaping hole in my test coverage, this time in `fxa-auth-db-mysql`, which meant the memory backend and the MySQL backend were behaving differently with regards to the initialisation of missing fields in the `devices` table.
And then I stupidly to forgot to test device registration against the MySQL backend, so the aforementioned discrepancy masked this bug until @jrgm found it when he deployed train 50. Apologies @jrgm (and everybody else).
I've updated `npm-shrinkwrap.json` here for the purposes of making …
> fix(server): permit null values in devices response

- .travis.yml
- scripts/start-local-test-mysql.sh
- scripts/start-travis-auth-db-mysql.sh
- test/local/verifier_upgrade_tests.js
Fixes #1125 
The backgrounded fxa-auth-db-mysql server was failing to start because the install was failing to install db-patcher (npm install quirk). This changes the npm install to run *in* the directory, which installs all the devDependencies including mysql-patcher. 
Also, there was an inherent race condition in the previous script. (It would try to complete the npm install/database update and be up and running before the actual tests would start). There is now a pause  and a check that the server started before continuing with the actual tests. (The check will be updated in a later PR to check that the implementation says 'MySql').
Also, updates to use npm@2.
> Fix travis-ci to actually run fxa-auth-db-mysql when $DB = 'mysql'

- npm-shrinkwrap.json
- scripts/start-travis-auth-db-mysql.sh
Make the travis-ci check a bit more definite by checking that `"implementation":"MySql"` is in the `/__version__` response. 
(Note: while failing this check will cause the overall travis-ci check to fail, travis-ci will continue on to run `npm test`. It doesn't abort on the first failure. Just the way travis-ci works).
> fix(travis-ci): check that auth-db-mysql reports "MySql" as constructor class name

- docs/api.md
- lib/routes/account.js
- test/remote/device_tests.js
Fixes #1118, enforcing the presence of the `name` parameter in device information.
@rfk or @dannycoates: r?
> fix(server): require device name to be set explicitly

- docs/api.md
- lib/db.js
- lib/routes/account.js
- test/local/db_tests.js
- test/remote/device_tests.js
Fixes #1117.
For some reason I forgot the `lastConnectedAt` field the first time round. Here it is.
> fix(server): add missing lastAccessTime field to devices response

- .travis.yml
Perhaps over-thinking, but this will build on node-4.x with g++-4.8, and on node 0.10 and 0.12 with the default g++-4.6. 
r? @dannycoates
> fix(travis): install/use g++-4.8 for node 4.x build of scrypt-hash

- README.md
- config/index.js
Just a leftover comment referring to long-dead servers.
> chore(docs): remove misleading references to awsbox

- lib/routes/account.js
Includes the `uid` (with domain as in the `delete` event) and the new `generation`.
> emit an event for account reset so sync can update the generation

- lib/metrics/statsd.js
- test/local/statsd_tests.js
This PR adds additional metrics to statsd messages. The following are now included
* agent_ua_family
* agent_ua_version
* agent_ua_version_major
* agent_os_version
* agent_os_family
* agent_os_major
Fixes #1115
> feat(metrics): Add additional metrics on statsd messages

- lib/tokens/session_token.js
- test/local/db_tests.js
- test/local/session_token_tests.js
This is the same as https://github.com/mozilla/fxa-auth-server/pull/1160, but targeted at current production version v1.53.0. 
It seems that CPU has suprisingly returned to normal-ish. But I'm going to continue to get this built and tested in stage in case the problem returns.
> fix(tokens): extend token freshness threshold to 6 hours

- lib/tokens/session_token.js
- test/local/db_tests.js
- test/local/session_token_tests.js
Fixes #1159 
A strawman to "fix" #1159. r? - @rfk, @philbooth 
This is targeted to `master`, but I'd actually want this on a branch from tag 0.53.0, the current production version. 
(Could be improve by moving TOKEN_FRESHNESS_THRESHOLD to a config param, but I'm looking for a minimal change to address a current issue).
> fix(tokens): extend "freshness" threshold to 6 hours

- npm-shrinkwrap.json
- scripts/e2e-email/localeQuirks.js
Update shrinkwrap notably for l10n strings:
```
- "resolved": "git+https://github.com/mozilla/fxa-auth-mailer.git#6a6fe5522a3b963c710d715b9ea81d3610642ac9",
+ "resolved": "git+https://github.com/mozilla/fxa-auth-mailer.git#26ced35d881466fb4b38b093445b18c0c2db9281",
- "resolved": "git://github.com/mozilla/fxa-content-server-l10n.git#b8647cd72b2f51b79bfd45acb45a6681cbd08d8f"
+ "resolved": "git://github.com/mozilla/fxa-content-server-l10n.git#9fde2c932a007ca1d752d1660fea13851608bd21"
- "resolved": "git+https://github.com/mozilla/fxa-auth-db-mysql.git#85811d7496a2c1444a4a612a4c1c2d9ba7f862af",
+ "resolved": "git+https://github.com/mozilla/fxa-auth-db-mysql.git#5598551b07ad8081b6225a0a27b5a831e41cc9cf",
```
Also 'ko' has some translations now for some email subjects
> chore(shrinkwrap): Update shrinkwrap, and "ko" has some translations now

- lib/tokens/session_token.js
- test/local/db_tests.js
- test/local/session_token_tests.js
We've been having bursts of 5xx errors in production today. Snap shotting `show processlist` on the database shows these bursts are correlated with "logjams" of updates to sessionTokens taking dozens of seconds. To alleviate this problem, effectively stop these updates from happening (a few will still occur due to other reasons `isFresh()` would return true, but from data this is on the order of 1%).
Already discussed with @dannycoates. r? to make sure I have no typo in there ;-)
Note: this is targeted to the branch that is running in production. I'll prepare a similar patch for `master`, where the code is just a tiny bit different.
/cc @ckolos
> fix(sessiontokens): effectively disable sessionToken updates

- config/index.js
Fixes #1155 by adding a config option to disable HTTP keepalive in hapi-fxa-oauth, and defaulting it to False.
Also fixes the bug noted in https://github.com/mozilla/fxa-auth-server/pull/1111#issuecomment-175474037 which we missed during initial review of that PR.
> OAuth config fixes

- bin/email_bouncer.js
- lib/bounces.js
- lib/db.js
- lib/error.js
- lib/routes/account.js
- npm-shrinkwrap.json
- package.json
- test/local/bounce_tests.js
- test/local/password_check_test.js
- test/local/push_tests.js
- test/local/statsd_tests.js
- test/mocks.js
This PR adds some de-mangling logic to our bounce handling as proposed in [1].  It's complicated by the fact that we didn't have existing tests for the bounce-handling code, and by the fact that I wanted to use a named constant rather than check for the magic value `errno === 102` in the new test.  So it may be easier to review as three separate commits:
* Add named constants for our errno values
* Refactor the bounce handler to be mockable/testable, and add some tests
* Add the de-mangling logic along with an additional test for it
Fixes #1136.
@dannycoates f?, could you please sanity-check my refactor of `./bin/email_bouncer.js`?
@vbudhram r?
[1] https://github.com/mozilla/fxa-auth-server/issues/1136#issuecomment-174443640
> Cope with quoted email addresses in bounce notifications

- lib/log.js
- test/local/log_tests.js
Our log-scrubber will automatically remove PII from a top-level field named "email", but not from within nested JSON in other fields.  This lifts the "email" property off error objects into the top-level fields for logging purposes.  @dannycoates r?
Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/124 (https://bugzilla.mozilla.org/show_bug.cgi?id=1232570)
> fix(logging): Remove PII from logged error object details.

- lib/log.js
- lib/metrics/statsd.js
- lib/server.js
We meant to do some analysis of this skew measurement, but haven't prioritized it.  Let's sent it to statsd/datadog for easier aggregation and analysis.  @jrgm r?
> feat(logging): Log hawk timestamp skew to statsd for easier analysis.

- docs/api.md
- lib/customs.js
- lib/routes/account.js
- test/client/api.js
- test/local/customs.js
- test/remote/account_status_tests.js
This PR adds the route `POST /v1/account/status` to check that status of an account by its email address.
Fixes #1176
> feat(api): Add get account status by email endpoint

- lib/routes/account.js
- lib/tokens/token.js
- test/client/api.js
- test/remote/device_tests.js
Fixes #1197.
The fix itself just updates the Joi data but I'm feeling pretty sketchy about the changes made to test it. As per https://github.com/mozilla/fxa-auth-server/issues/1197#issuecomment-188755474, it's difficult to force a certain value for `lastAccessTime` from the remote tests because it gets set automatically. I took the approach of passing in a query param to force it but there's one place in particular where that feels a little bit hairy, see my comment inline.
@rfk, @jrgm r?
> fix(api): permit lastAccessTime 0 in devices response

- lib/routes/validators.js
- test/local/email_validity_tests.js
Fixes #1193.
I'm not sure whether this is still worth resolving in light of [the decision](https://github.com/mozilla/fxa-content-server/pull/3546#issuecomment-191324647) over on the content server not to support unicode email addresses. This change does not bring us full harmony between the two implementations, although they are closer with this change than without it. But at some point in the future, we'll still need to address the divergence between the two.
Anyway, here it is just in case.
> fix(api): reject emails without a dot in the domain

- test/mailbox.js
- test/remote/account_create_tests.js
- test/remote/account_login_tests.js
- test/remote/account_profile_tests.js
- test/remote/account_status_tests.js
- test/test_server.js
Fixes #1206.
The problem was fixed by URI-encoding the `name` portion of the path when the `server.mailbox` test helper makes requests to the auth mailer.
Even though the tests were just written as a sanity check ahead of https://github.com/mozilla/fxa-content-server/pull/3546 and the fix is not to production code, I figured it's still worth landing?
> fix(tests): sanely handle unicode email addresses in account tests

- config/index.js
This adds signIn configuration value needed by new password flow templates. This is needed by new password email templates.
Ref: https://github.com/mozilla/fxa-auth-mailer/pull/124
Ref: https://github.com/mozilla/fxa-content-server/issues/3467
@vladikoff r?
> chore(api): Add signin config value

- lib/routes/account.js
- npm-shrinkwrap.json
- test/remote/password_forgot_tests.js
Fixes the recent 500 errors that have been occurring on the `/devices` endpoint by permitting a null `lastAccessTime` in the response.
Note that these nulls are a result of the `LEFT JOIN` in the stored procedure rather than being in the database directly, so the `NOT NULL` in the schema still stands.
@jrgm, @rfk r?
> fix(api): permit null lastAccessTime in devices response

- lib/log.js
- lib/metrics/context.js
- lib/routes/account.js
- lib/routes/sign.js
- test/client/api.js
- test/client/index.js
- test/local/log_tests.js
- test/local/metrics_context_tests.js
- test/remote/account_create_tests.js
- test/remote/account_login_tests.js
- test/remote/certificate_sign_tests.js
- test/remote/password_forgot_tests.js
Fixes #1200.
To reduce repetition of the validation boilerplate, I extracted the schema into the `metricsContext` module. I opted for there rather than the `validators` module so that the schema could live close to the `add` method; if any changes need to be made to this stuff down the line, they will only affect this one module. But I also realise I'm breaking with convention a bit so if you don't like it I'm happy to stick it in `validators`.
@rfk, r?
> feat(logging): add metrics context metadata to activity events

- lib/routes/account.js
- test/local/account_routes.js
- test/mocks.js
Potentially fixes #1219, /cc @jrgm; @philbooth mind an r?
This proved tricky to test using the current test infrastructure, because the desired logic requires the creation of a strange database state.  I took a new approach based on mocking out everything but the route-handling code itself, which made the specific change in this PR easier to test, but may have other downsides overall.  What do you think @philbooth?  If we like it, we could work on slowly refactoring other routes to have more unit-test-style tests like this as well.
> fix(email): Clean up accounts with invalid emails on status poll.

- npm-shrinkwrap.json
Only changing top-level deps fxa-auth-db-mysql, fxa-auth-mailer, and fxa-content-server-l10n.
> Some shrinkwrap bumps for train-59 (narrowly targetted)

- test/remote/account_profile_tests.js
Just cleaning up a stray, deprecated call to `.root()`.
> chore(convict): use convict .getProperties(), not deprecated .root()

- lib/routes/account.js
- test/remote/device_tests.js
- test/remote/password_forgot_tests.js
Per https://github.com/mozilla/fxa-auth-server/pull/1229, we're going to need to refactor the way we accept and store keys for push connections.  To avoid any weirdness with data in old formats, I think we should lead with a deployment that specifically disables the storage of keys until we're ready for them.
In theory this will have no observable effect, since none of our clients are sending the keys bundle.  But that's only in theory, I'd quite like to be able to know it in practice.
> fix(push): Disallow storing of public-key values until we're ready to use them

- config/index.js
- lib/mailer.js
- npm-shrinkwrap.json
Primarily @vbudhram's work, @shane-tomlinson made some name changes and
squashed the commits.
Ref #1230.
This is #1230 w/ only the portions that interface with the auth-mailer.
> feat(mailer): Add "re-confirm your email" templates.

- .nsprc
- npm-shrinkwrap.json
- package.json
Let's see if this works.
I still get one warning from **nsp**, but we can't update the **hapi** dependency without doing a major version bump.
```
✗ grunt nsp
Running "nsp" task
Warning: (+) 1 vulnerabilities found
Name     Installed   Patched    Path                                                              More Info
moment   2.10.3      >=2.11.2   fxa-auth-server@1.60.0 > hapi@8.8.1 > joi@6.4.1 > moment@2.10.3   https://nodesecurity.io/advisories/55
Use --force to continue.
Aborted due to warnings.
```
> chore(nsp): Update convict, add .nsprc file to silence some NSP warnings

- lib/routes/account.js
- test/remote/device_tests.js
The device name is a displayable string (although we don't currently display it anywhere) so we should apply the same filtering as e.g. the user's own display name string.
> Restrict device name to display-safe unicode characters

- config/index.js
- docs/api.md
- lib/error.js
- lib/routes/account.js
- test/local/account_routes.js
To help us with rolling out device metadata updates to release Firefox, this PR adds two things:
* More metrics on what has changed (if anything) to trigger the update
* A safety switch to let us easily pref the feature off if we get swamped
@jrgm what do you think?
> feat(devices): Add metrics on device updates, and a flag to disable them

- docs/pushpayloads.schema.json
We want to define (and maybe validate in tests) what we send using the Push API from the fxa-auth-server to the Firefox Browser.
We settled on using JSON Schema for this, it looks mature enough and allows us to use good old JSON.
You can try this schema [here](http://www.jsonschemavalidator.net/)
Here's an example of a JSON payload with the current PR proposal (I'll update it in this comment when we amend the schema):
```
{
version: 1,
action: "fxaccounts:new_device",
data: {
deviceName: "dd"
}
}
```
Any feedback on this?
ping @mhammond @ckarlof @rfk @kitcambridge @rnewman @edmoz @philbooth @vladikoff
> feat(push): document the format of the push payloads

- lib/routes/account.js
This PR adds the `sessionToken` param to the `/account/reset` endpoint. This is needed to support legacy and new clients that don't require a re-login.
@jbuck r?
> refactor(reset): Adds sessionToken as an optional param

- docs/api.md
- lib/error.js
We've already left space in our errno sequence for number 125, I don't see why we shouldn't at least document what it's for
> feat(errors): Add API and docs for new "request blocked" errno 125.

- docs/api.md
- lib/routes/account.js
- lib/routes/password.js
- lib/routes/utils/request_helper.js
- test/client/api.js
- test/client/index.js
- test/local/password_routes.js
- test/local/verifier_upgrade_tests.js
- test/remote/account_reset_tests.js
- test/remote/password_change_tests.js
PR https://github.com/mozilla/fxa-auth-server/pull/1232 is being split into two PRs. This PR contains updates to `/account/reset` and `/password/change/finish`. These endpoints return sessionToken and keyFetchTokens that allow the client not to have to re-login after performing the respective functions.
Corresponding content-server changes: https://github.com/mozilla/fxa-content-server/pull/3747
@shane-tomlinson @rfk, this what you had in mind? r?
> refactor(signin): Updated password/change/finish and account/reset

- docs/api.md
- lib/routes/account.js
- test/remote/device_tests.js
- test/remote/password_forgot_tests.js
@rfk @seanmonstar 
In light of [your conversation](https://github.com/mozilla/fxa-auth-server/pull/1263#issuecomment-221083580), I've gone ahead and removed device registration from the `/account/signup` and `/account/login` endpoints entirely.
r?
> fix(api): remove device registration from signup/login endpoints

- scripts/e2e-email/index.js
- scripts/e2e-email/localeQuirks.js
- scripts/e2e-email/validate-email.js
repairs this test by getting `/account/keys`, using instance methods (not creating more logins), and restoring the check for new login (that was removed when we stopped sending this notification). 
Also note: `ar` email doesn't appear to be translated (like a lot of other locales note in `localeQuirks.js`).
r? @vbudhram
> fix(e2e-email): fix e2e-email for all locales

- config/index.js
- lib/routes/utils/request_helper.js
- test/local/account_routes.js
This PR adds the ability to specify an array of regex for email addresses to enable sign-in confirmation. This will give us the ability to turn feature on/off for more specific group of audiences.
@philbooth I would ideally like to merge your testing changes in before merging this. Mind a review at your leisure?
> feat(signin): Add regex for enabling signin confirmation

- config/index.js
- test/local/account_routes.js
- test/local/password_routes.js
- test/mocks.js
- test/ptaptest.js
The recent explosions in `tests/local/account_routes` resulted in a lot of a duplication and not much order, with assertions for the different endpoints all kind of jumbled up with each other.
To fix this, I've done the following:
* Made the test wrapper in `test/ptaptest` more composable by adding an optional third argument, `parentTest`. This allows us to nest tests inside each other while still making use of the boilerplate code for calling `t.end()` and logging errors, which the wrapper provides.
* Refactored all of the tests in `tests/local/account_routes` so that they are grouped by endpoint. Each endpoint has one and only one base test, with child tests added whenever some variation in the setup is necessary. Doing this allowed us to delete ~600 lines of setup code without removing …
> refactor(tests): eliminate duplicate setup in local route tests

- lib/routes/account.js
- test/local/account_routes.js
- test/mocks.js
Ref https://github.com/mozilla/fxa/issues/138
Uses param from https://github.com/mozilla/fxa-auth-mailer/pull/169 that will be forward using the content server
> feat(metrics): add metrics for reminder queries

- lib/routes/password.js
- test/mocks.js
- test/remote/password_change_tests.js
@shane-tomlinson @vbudhram for your consideration...
The way that the /password/change/finish endpoint currently works, is that it accepts *raw sessionToken data bytes* in the request body.  This is the only place in the code that the clients sends session data in raw form over the wire - in all other places, we derive a "token id" and "token key" and use those to make a signed request in a way that's resistant to a MITM attack.
On the auth-server side, the effect is that we have to call `tokens.SessionToken.fromHex` on the submitted value in order to derive the token id, before we can actually look up the token.
I think we should change this route to accept the token id instead of the raw token, to keep the security model of these things consistent.  Since it's an API change we'd have to …
> fix(signin): Let /password/change/finish accept session tokens by id.

- lib/routes/account.js
- test/client/index.js
- test/remote/account_create_tests.js
Once train-64 ships, we can remove the backwards-compatibility check that sends a post-verification email when `service` is missing or empty.  The content-server will always provide a `service=sync` parameter when verifying for sync.
@seanmonstar r? (although don't merge until after train-64 has been cut).  Fixes #1249.
> fix(verify): Don't sent post-verify email when `service` is blank.

- bin/key_server.js
- config/index.js
- lib/log.js
- lib/metrics/context.js
- lib/routes/account.js
- lib/routes/index.js
- lib/routes/session.js
- lib/routes/sign.js
- npm-shrinkwrap.json
- package.json
- test/local/account_routes.js
- test/local/log_tests.js
- test/local/metrics_context_tests.js
- test/local/sign_routes.js
- test/mocks.js
Fixes #1199.
Slower than advertised, sorry, this is a rebased #1259 with refactored tests. Everything else should be effectively the same as the old PR.
To recap, this change adds new activity events to support the new KPI dashboards. Because these events rely on metadata that is not available on every endpoint, data is stashed in memcached for later retrieval. The default lifetime for this data is 30 minutes but in most cases I expect it to be purged sooner than that, as activity events for the signup and login flows are emitted.
The config for memcached uses different environment variables from the customs server, to make it easier to target a different instance of memcached. And the default namespace for the new data is different to the customs server, to make it possible to target the …
> feat(server): emit new activity events for kpi dashboards

- README.md
- package.json
- scripts/test-local.sh
This allows one to do something like `NO_COVERAGE=1 npm test -- test/local/account_routes.js` to quickly run the account tests.
> chore(tests): allow passing a glob to npm test

- npm-shrinkwrap.json
@jrgm, @rfk - I did `rm -rf node_modules; npm install --production; npm shrinkwrap` and my shrinkwrap file has shrunk by 3600 lines. When I do `rm -rf node_modules; npm install; npm shrinkwrap --dev`, shrinkwrap complains about extra deps being installed. Any ideas?
fixes mozilla/fxa-content-server#3851
> fix(deps): update npm-shrinkwrap.json w/ newest auth-mailer & fxa-content-server-l10n

- docs/overview.md
I realised that I hadn't thought through all of the permutations correctly when I documented the activity event data recently. Specifically:
* Some endpoints can be invoked outside of a flow, so `flow_id` and `flow_time` should be optional for those cases.
* Some endpoints are never part of a flow, so `flow_id` and `flow_time` should not be mentioned for those cases.
This PR addresses those issues.
> fix(docs): correct the acitvity event data documentation

- lib/push.js
- test/local/push_tests.js
Fixes #1323, which was causing session tokens not to be deleted when disconnecting from Sync.
So, by extension, this should also address https://github.com/mozilla/fxa-bugzilla-mirror/issues/150.
@vladikoff, @shane-tomlinson r?
> fix(server): fix bad sessionTokenId arg in call to updateDevice

- lib/routes/account.js
- test/local/account_routes.js
- test/remote/account_signin_verification_enable_tests.js
- test/remote/account_signin_verification_tests.js
Based on our IRC chat, here is a table defining the expected emails (inorder) when logging in with the different states of the auth-server.
|    |      Sign-in Confirmation On      |  Sign-in Confirmation Off |
|----------|:-------------:|------:|
|Unverified Account |  Verify your Firefox Account, Account Verified | Verify your Firefox Account, New sign-in to Firefox, Account Verified |
|Verified Account |  Confirm sign-in to Firefox | New sign-in to Firefox |
@shane-tomlinson @rfk These seem reasonable? r?
Fixes #1314
>  fix(signin): Fixes multiple emails sent on login

- .nsprc
Per discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1284668, it's safe for us to silence this warning for now in order to unbreak travis builds.  @seanmonstar r?
> chore(nsp): Add NSP exception for https://nodesecurity.io/advisories/121

- scripts/start-local-mysql.sh
- scripts/start-local.sh
- scripts/start-travis-auth-db-mysql.sh
- scripts/test-local.sh
The internet said this was a good idea [1] so I added it to all our bash scripts that aren't obviously doing their own error handling.  Might help with problems like [2]?
[1] http://redsymbol.net/articles/unofficial-bash-strict-mode/
[2] https://github.com/mozilla/fxa-auth-server/commit/37f0fe4637b84e4ce370c0e9f5244d2a8fc86add#commitcomment-18148096
> chore(scipts): Add stricter error handling to bash scripts

- lib/log.js
- lib/routes/account.js
- test/local/account_routes.js
- test/local/log_tests.js
- test/mocks.js
Our `log` object has a lot of methods and it's not always obvious which one to use when.  By far the worst offender here is `log.event`, which has a generic name but a very specific job.  I've the `log.js` module, added some high-level comments to it, and and renamed `log.event` to `log.notifyAttachedServices` in an attempt to avoid future confusion.
@philbooth r?
> fix(log): Add comments and clarify naming for logging methods.

- config/index.js
- lib/db.js
- lib/routes/account.js
- lib/routes/password.js
- lib/server.js
- lib/tokens/key_fetch_token.js
- test/client/index.js
- test/local/account_routes.js
- test/remote/account_signin_verification_tests.js
- test/remote/password_change_tests.js
This PR adds support for account verification status check via `/account/keys`.
Fixes #1287
> fix(signin): Add keyFetchToken verification state support

- lib/customs.js
- test/local/customs.js
This PR scrubs the request payload that is sent to the customs server. Specifically it removes `authPW` from payload. 
Fixes https://github.com/mozilla/fxa-auth-server/issues/1347
@seanmonstar mind a sanity check / r?
> refactor(customs): Scrub request payload sent to customs server

- lib/routes/account.js
- lib/routes/index.js
- lib/routes/session.js
- lib/routes/sign.js
- test/client/api.js
- test/remote/certificate_sign_tests.js
- test/remote/password_forgot_tests.js
Fixes https://github.com/mozilla/fxa-auth-server/issues/1345.
The content server only sends a `metricsContext` payload to `/account/create` and `/account/login`. The code for receiving it on other endpoints is redundant and makes client code more confusing because it introduces different ways to pass a `service` parameter.
https://github.com/mozilla/fxa-js-client/pull/205 has been opened to remove the redundant options from the client library. This PR is okay for simultaneous review because those client options aren't actually used by anyone.
@rfk, do you foresee any problems with us doing this?
> fix(server): remove metricsContext from payloads where it is never sent

- lib/customs.js
- lib/routes/utils/request_helper.js
- test/local/account_routes.js
This is an alternative proposal to #1355, taking a smaller step to enabling this flow on all devices.  Here, the rules work as follows:
* The customs-server can flag a request as being suspicious, rather than outright needing to be blocked.  We always do sign-in confirmation for such requests.
* The list of forced email addresses, is now checked before the list of devices.  This means anyone using an @restmail.net or @mozilla.com address will get sign-in confirmation on all their devices, allowing preliminary testing of various legacy devices.
* After those two checks, we keep the current logic of rolling out to a percentage of known-to-be-working-properly device types.
@shane-tomlinson r?
> feat(signin): Always do sign-in confirmation on suspicious requests.

- test/e2e/push_tests.js
Related to https://github.com/mozilla/fxa-auth-server/issues/1368
> fix(tests): disable e2e tests until push server fixed

- lib/routes/password.js
- test/local/password_routes.js
- test/mocks.js
Fixes #1373.
This addresses the immediate issue of passwordForgotTokens being assigned the `createdAt` timestamp from the emailRecord.
There is a broader question of whether we should enforce fresh timestamps in the `Token` constructor to stop things like this happening again in the future. Were we to do so, it would probably mean reworking some tests that depend on setting a specific time.
@vbudhram r?
> fix(server): assign fresh createdAt timestamp to passwordForgotTokens

- lib/db.js
- test/local/account_routes.js
- test/remote/db_tests.js
Fixes #1378.
Account reset tokens are created via `db.forgotPasswordVerified` instead. This begs the question of whether the `createAccountResetToken` in the db server is also redundant. I'll raise that in another issue.
@vladikoff r?
> Remove unused method db.createAccountResetToken

- lib/routes/account.js
This PR add some additional logging to help better evaluate sign-in confirmation feature.
Per #1363 , 
a = account.create.confirm.start (from create account) + account.signin.confirm.start (from login)
b = account.signin.confirm.success
c = acocunt.signin.confirm.error (from email bounce)  + acocunt.signin.confirm.invalid (from invalid token)
Fixes https://github.com/mozilla/fxa-auth-server/issues/1363
> Add additional logging for sign-in confirmation

- lib/routes/account.js
- test/local/account_routes.js
- test/mocks.js
Fixes #1388.
Here is a sample log line showing the new event, along with the appropriately stashed metrics context data.
```
activityEvent {"event":"account.confirmed","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:50.0) Gecko/20100101 Firefox/50.0","time":1470316397843,"flow_id":"8b3cdf7cfc9d4968f8e23e4dba36509b80170211360f9236f12e4bbbc5437d7b","flow_time":13063,"context":"fx_desktop_v2","entrypoint":"menupanel","service":"sync","uid":"e73292390c9b420885565112f426988f"}
```
There's some minor additional rejigging in the route handler from where I decided to eliminate all the duplicate calls to `account.uid.toString('hex')`.
And the local test changes for `/recovery_email/verify_code` may look a bit hairier than anticipated because of whitespace changes from how the nesting …
> feat(logging): emit an account.confirmed activity event

- lib/routes/password.js
- test/mocks.js
- test/remote/password_change_tests.js
This PR removes accepting raw session token data on password changes. Any request sending this data will receive an invalid verification code error.
Fixes #1351
> fix(password): Remove raw token support

- lib/routes/account.js
- lib/tokens/session_token.js
- lib/tokens/token.js
- test/local/session_token_tests.js
- test/local/token_tests.js
- test/remote/base_path_tests.js
Fixes #1383.
The ideal fix for this would have been always to set `createdAt` to `Date.now()` in the `Token` constructor. Unfortunately, [these tests](https://github.com/mozilla/fxa-auth-server/pull/1198/files#diff-192be473e813a7f161eb81eb38511e09R339) need to retain the ability to set `createdAt` to something else, so that they can make assertions against a zero `lastAccessTime` from the db.
Instead, as a second-best option, I've pulled the implementation of `optionallyOverrideCreatedAt` down from the `/account/create` route handler into the base `Token` object. This ensures that the timestamp can be overridden from the tests but not in a production environment.
@vladikoff r?
> fix(server): ensure tokens get a fresh createdAt timestamp

- lib/db.js
- lib/devices.js
- lib/routes/account.js
- lib/routes/index.js
- lib/routes/sign.js
- test/local/account_routes.js
- test/local/devices_tests.js
- test/local/sign_routes.js
- test/mocks.js
- test/remote/db_tests.js
I forgot to create an issue to cover this one but it reinstates placeholder devices, which initially got merged in #1299 before being reverted in #1344. The original issue for the feature was #1196.
It was reverted because of two problems:
1. Vanilla web sessions started showing up in the devices view. That problem was fixed by https://github.com/mozilla/fxa-js-client/pull/205 and https://github.com/mozilla/fxa-content-server/pull/3957.
2. The device name was blank. That problem is fixed in this PR by ensuring that `db.devices` returns the parsed user agent info (line 443 of `lib/db.js`, tests at line 296 of `test/remote/db_tests.js`), which is also why the extra deletes are added to `/account/devices` handler.
Tested locally, but I also hope/plan to have it running in AWS …
> fix(server): reinstate placeholder devices for sync sessions

- npm-shrinkwrap.json
- package.json
@vbudhram r?
While working on a thing I noticed that `ws` and `ajv` were not in shrinkwrap, also ajv was in devDeps, but used as a dep in the code now.
> fix(deps): update shrinkwrap, add missing deps

- docs/overview.md
- lib/log.js
- test/local/log_tests.js
It just occurred to me that we over-simplified the relationship between activity events and flow events in #1409 (my fault for not thinking things through properly when reviewing).
There are a number of activity events which should never have a corresponding flow event. And there are a few others that should only have a flow event if `metricsContext.gather` returns a `flowId`.
This change ensures that we limit the flow events only to those that actually constitute part of the sign-up or sign-in flow. And if we encounter any flow events that do not have a `flowId` we now log an error, which we weren't doing previously.
Doing this also meant we could ditch that really ugly table from the docs, because all of the events now have a uniform structure.
@vladikoff, r?
Sign-up log excerpt:
``` …
```
> fix(logging): not all activity events are flow events

- lib/db.js
- lib/routes/account.js
- lib/tokens/session_token.js
- lib/userAgent.js
- test/local/user_agent_tests.js
This has now received approval from legal. The fix just ensures that placeholder devices get a name based on the user agent string, if we failed to parse it for whatever reason.
In lieu of a legacy device to test on, I did the following:
1. Commented out [the call to `this.updateDeviceRegistration` in `setSignedInUser`](https://dxr.mozilla.org/mozilla-central/source/services/fxaccounts/FxAccounts.jsm#556), in a local build of Firefox:
2. Changed my user agent to something silly:
3. Signed in and navigated to the devices view:
The limits used for truncation are completely arbitrary, I'm open to other suggestions if anyone has them. In reality, this code should be executed very rarely.
@vladikoff, r?
> fix(server): reinstate default user agent fallback

- lib/log.js
Diving through hapi code, this is the trail I took to decide to inspect `response.source`:
1. `reply(data)` https://github.com/hapijs/hapi/blob/v8.8.1/lib/reply.js#L65
2. `reply.response(data)` https://github.com/hapijs/hapi/blob/v8.8.1/lib/reply.js#L128
3. `Response.wrap(data)` https://github.com/hapijs/hapi/blob/v8.8.1/lib/response.js#L56
4. `new Response(data, ...)` https://github.com/hapijs/hapi/blob/v8.8.1/lib/response.js#L15
5. `Response._setSource(data, ...)` https://github.com/hapijs/hapi/blob/v8.8.1/lib/response.js#L88
There doesn't appear to be a public API to inspect the waiting JSON response, so this may be brittle and require updating when we upgrade hapi.
> fix(logs): look in response.source for uid

- npm-shrinkwrap.json
- package.json
Update to fix a leak. I don't know if we need to get an updated version of fxa-auth-mailer that uses poolee@1.0.1 too. Thoughts? @vladikoff
> fix(deps): use poolee@1.0.1

- lib/routes/account.js
- test/local/account_routes.js
This PR adds the ability for the auth-server to receive a query param `sendEmailIfUnverified` on the `/account/login` endpoint, specifying whether or not it should the verify account email for unverified accounts.
Ref: #1325
> fix(emails): On login, delegate email sending to auth-server

- bin/key_server.js
- lib/newrelic.js
- npm-shrinkwrap.json
- package.json
svcops would like to make use of New Relic. This PR just makes it possible to load the module if explicitly configured. Further configuration will happen with puppet in the circusd environment (unless we have to set so many switches that a sane configuration file makes sense).
r? @rfk 
/cc @ckolos
> feature(newrelic): add optional newrelic integration

- config/index.js
- npm-shrinkwrap.json
Connects to https://github.com/mozilla/fxa-auth-mailer/issues/203; @shane-tomlinson r?
> fix(config): Remove unused URL opions from mailer config.

- lib/routes/account.js
- lib/routes/utils/request_helper.js
- test/local/account_routes.js
This PR changes https://github.com/mozilla/fxa-auth-server/pull/1435, to send `sendEmailIfUnverified` via query params. For all unverified login requests coming from a non content-server context, a verification email will be sent.
@shane-tomlinson This what you had in mind? r?
> fix(email): Refactor to send `sendEmailIfUnverified` via query

- config/index.js
- lib/db.js
- lib/routes/account.js
- lib/routes/utils/request_helper.js
- npm-shrinkwrap.json
- test/local/account_routes.js
- test/mocks.js
We will start to record a history of security events, which will include the event name, IP address, and uid.
There could be other or new events, but for now, they are:
- `account.create`
- `account.login`
- `account.reset`
This is actually trickier than what one might imagine at first thought. We don't want to mark an IP address of an attacker as "all good". Until sign-in confirmation is at 100%, it is possible that we do that. So, it might make sense to also add a `account.confirmed` event, recorded when a user follows the sign-in confirmation link from their email.
Then, there is the matter of what events are worthy of skipping sign-in confirmation. Probably only `account.confirmed`. However, a user may answer the sign-in confirmation on their mobile device, with a different IP address …
> feat(security): record event names and ip addresses for important events

- lib/log.js
- test/local/log_tests.js
GitHub's most annoying feature is definitely it's refusal to re-open a closed PR after you've force-pushed the branch. Because this is exactly the same PR as #1461 was, with a couple of changes to the log tests.
Anyway, to repeat what I said there:
> This is a temporary hack to improve the accuracy of the sign-in funnel metrics as part of train 70. Longer term I will do something nicer than this, I'm just not sure what it is yet. Making this fix now allows us to get more accurate flow metrics sooner.
>
> See the related discussion in #1457, this PR doesn't fix that issue but whatever replaces it will.
>
> @vladikoff or @vbudhram, r?
> fix(logging): ignore account.signed flow events from the content server

- config/index.js
- lib/features.js
- npm-shrinkwrap.json
- package.json
- test/local/account_routes.js
- test/local/features_tests.js
- test/local/session_token_tests.js
- test/remote/db_tests.js
Doing this saves us the cost of constructing a fresh `RegExp` on each call to the feature flag methods. They couldn't be cached on initialisation because the unit tests relied on changing the regex between tests. Support for `RegExp` was added to convict in version `1.5.0`.
I'll add details of the config changes to the deploy doc after it gets merged.
> fix(config): return parsed RegExp instances from config

- config/index.js
@jrgm, I learned the lesson from yesterday and am tagging you for review on this config change.
In discussion with @rfk earlier, we decided that we want to loosen the expiry time on flowIds a little so that we're casting our net a bit wider for the flow metrics. Hence this.
r?
> fix(config): increase flowId expiration to 2 hours

- lib/routes/index.js
- lib/routes/password.js
- test/local/password_routes.js
This updates the auth-server API to accept a metricsContext bundle on the password-reset endpoints.  It will be needed before we can start emitting password-reset-related flow events as described in https://github.com/mozilla/fxa-content-server/issues/4004
Obviously there will need to be some work done to actually *use* the metricsContext bundle, this just accepts it in the API so that we can ship content-server code that submits it as part of the next train.  I think we should try to get it into train-71 if possible, @philbooth r?
> feat(reset): Accept metricsContext bundle on password-reset endpoints.

- test/local/mailer_locales_tests.js
Latest l10n broke this test. Once this gets merged I'll tag a 71.1 release.
@vladikoff r?
> fix(tests): es-ES is now 100% supported

- npm-shrinkwrap.json
- package.json
... which is really just upgrading to use nan@2.4.0 for node6 compatibility.
> fix(node6): update to scrypt-hash@1.1.14 for node6 compat

- .gitignore
- config/index.js
- lib/push.js
- lib/routes/index.js
- npm-shrinkwrap.json
- package.json
- scripts/gen_vapid_keys.js
- scripts/start-local-mysql.sh
- scripts/start-local.sh
- scripts/test-local.sh
- test/config/mock-vapid-keys.json
- test/e2e/push_tests.js
- test/local/account_routes.js
- test/local/push_tests.js
- test/remote/push_db_tests.js
The push team would like to be able to attribute our notification traffic back to us, for e.g. metrics and reporting purposes.  AFAICT the simplest way to allow this on our side is to implement the " Voluntary Application Server Identification" protocol, or "VAPID".  Since the web-push library has builtin support for it in the latest version, this basically means managing an additional keypair and passing it through to the underlying lib.
Not ready for review yet, but putting it up for any initial feedback, and so I can show it to @bbangert.
> feat(push): Add VAPID identification to push messages.

- bin/key_server.js
Fixes #1492.
@shane-tomlinson, as promised, this fixes the display of RegExp config settings on start-up. r?
> fix(scripts): nicely stringify regexps when logging config

- lib/log.js
- lib/metrics/context.js
- lib/routes/account.js
- test/local/account_routes.js
- test/local/log_tests.js
- test/local/metrics_context_tests.js
Part 1/3, related to #1284.
I'm splitting this PR up as per our conversation in retro, because it is a three-part refactoring. It's not clear to me whether each part will be 👍 or 👎, so I've decided to get them reviewed independently as I finish each one. This is (I hope) the least contentious of the three parts.
Way back when I first implemented the metrics context stuff, I opted to stash the data in memcached using a key that included the event name. Doing this enabled us to delete the data on read, which was important because it wasn't configured to expire.
However, we've since set an expiry time on this data so there is no need to delete on read and there is no need to include the event name in the key. This PR implements those changes and, in doing so, makes it much easier for us to …
> refactor(logging): eliminate the event argument from stash and gather

- bin/key_server.js
- lib/log.js
- lib/metrics/context.js
- lib/routes/account.js
- lib/routes/index.js
- lib/routes/password.js
- lib/server.js
- test/local/account_routes.js
- test/local/log_tests.js
- test/local/metrics_context_tests.js
- test/local/password_routes.js
- test/mocks.js
Part 2/3, related to #1284. Part 1 was #1500.
This PR addresses the meat of the linked issue, namely the awkwardness involved in passing the `metricsContext` object everywhere. It does so by leaning on Hapi's [`server.decorate`](http://hapijs.com/api#serverdecoratetype-property-method-options) extension point to expose the `metricsContext` methods (well, proxies for them) directly on the `request` object.
I also experimented with a slightly different approach, using [`server.method`](http://hapijs.com/api#servermethodname-method-options) instead. That ended up being a bit uglier though, you can see it in 66b27cb if you're interested. The advantage of that approach is that the extension methods are only attached once, on `request.server.methods`. Here the methods are decorated per-request, …
> refactor(logging): decorate request object with metricsContext methods

- lib/log.js
- test/local/log_tests.js
@vbudhram you already reviewed this once before in #1483, however it seems to have been lost during a merge conflict at some point.
This PR reinstates that change and also adds an extra test to make sure it doesn't get lost again.
r?
> fix(logging): device.created is not a flow event

- lib/log.js
- lib/routes/account.js
- test/local/account_routes.js
I don't think the events added for sign-in unblock should be activity events.
In my internal model at least, activity events are reserved for concrete state changes to the account. Flow events, on the other hand, are for tracking different steps of the sign-in funnel and these seem more like flow events than activity events to me.
I realise I've done a poor job at explaining this distinction and [my documentation PR](https://github.com/mozilla/fxa-auth-server/pull/1447) hasn't landed yet because the flow events are still in flux, sorry. But fwiw I'm also working on a refactoring that should make things much easier, to the point where the decision of what is and isn't a flow event or an activity event will mostly be made automagically.
In the meantime, I figured it was worth fixing this …
> fix(logging): emit flow events for sign-in unblock, not activity events

- lib/customs.js
- lib/devices.js
- lib/log.js
- lib/metrics/events.js
- lib/routes/account.js
- lib/routes/sign.js
- lib/server.js
- test/local/account_routes.js
- test/local/customs.js
- test/local/devices_tests.js
- test/local/log_tests.js
- test/local/metrics_events_tests.js
- test/local/sign_routes.js
- test/mocks.js
Part 3/3, fixes #1284. Part 1 was #1500 and part 2 was #1503.
Hopefully this change resolves the recent confusion around what is an activity event and what is a flow event. From now on, we need only make calls to `request.emitEvent` for both event types. All of the decision making for which `log` method to call is contained therein.
This also makes `lib/log.js` a little bit cleaner because it enabled me to move the decision-making into a dedicated module, `lib/events.js`. So `log.activityEvent` no longer includes a conditional call to `log.flowEvent`, those two methods are properly separated.
The new module takes the approach of defining all of the events that *aren't* a flow event. This is easier than defining the flow events directly because of how many there will be when we're …
> refactor(logging): move activity/flow event decision out of log object

- lib/error.js
- lib/log.js
- lib/metrics/context.js
- lib/routes/account.js
- lib/server.js
- test/local/account_routes.js
- test/local/log_tests.js
- test/local/metrics_context_tests.js
- test/mocks.js
Fixes #1480.
Because different flows have different completion signals, we need to emit an explicit `flow.complete` event for the benefit of the funnel queries.
There may be a more elegant way to achieve that than what I've done here, but I had half an eye on the clock in an effort to get this onto train 72. I took the approach of stashing an extra piece of data in memcached, calling it `flowCompleteSignal`.
While implementing it, I also noticed a separate issue that I introduced in #1500. Because the metrics context data is no longer cleared from memcached on read, and because Sync hits the `/certificate/sign` endpoint more than once, it was possible for multiple completion events to be emitted. I fixed this by adding a `request.clearMetricsContext` method and calling it after we emit …
> feat(logging): emit a flow.complete event

- lib/routes/password.js
- test/local/password_routes.js
- test/mocks.js
This PR emits the needed flow events to track password reset. To test, connect with https://github.com/mozilla/fxa-content-server/pull/4297 and js client https://github.com/mozilla/fxa-js-client/pull/214.
Sample output
```
flowEvent {"event":"account.created","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0","time":1477084450050,"flow_id":"00998b433c6bc2cbbe618e009188ac7047495ff3bdffd50b5dfabd0e2eb4b679","flow_time":942771,"context":"fx_desktop_v3","entrypoint":"menupanel","service":"sync"}
flowEvent {"event":"account.verified","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0","time":1477084476101,"flow_id":"00998b433c6bc2cbbe618e009188ac7047495ff3bdffd50b5dfabd0e2eb4b679","flow_time":968822,"cont …
```
> feat(metrics): Add password reset flow metrics

- docs/metrics-events.md
Fixes #1366.
This is my attempt to document the flow and activity events for end users of the metrics data in redash. As such, they skip the details about the structure of emitted data that we have in `docs/overview.md` and instead concentrate on what is actually in redshift.
Note that this is a description of how things *will be* after https://github.com/mozilla/fxa-activity-metrics/pull/2 is finished, not how they are *now*.
The benefit of keeping this documentation inside the repo is that, hopefully, it is more likely to be updated here as new events get added. To give it wider exposure, we could link to it from Mana or wherever people are more likely to see it.
@davismtl, @vladikoff r?
(if you want to review it in its rendered form rather than the raw text, [click …
> feat(docs): document the event data available in redshift/redash

- lib/routes/account.js
- test/local/account_routes.js
Adds the following flow events:
- `flow.signin.submit`
- `account.login.blocked`
- `account.login.invalidUnblockCode`
The follow are already in the code base:
- `account.login.sentUnblockCode`
- `account.login.confirmedUnblockCode`
Closes #1505 
r? @shane-tomlinson or @philbooth
> Add missing flow events for Signin Unblock

- test/signer-stub.js
The referenced `../bin/signer.js` is not actually in bin folder. I also could not find references to it.
> chore(cleanup): Remove signer-stub.js

- docs/metrics-events.md
Some stuff didn't make it on to train 73, this updates the doc to reflect that.
@vbudhram r?
> fix(docs): document the recent flow event changes

- lib/metrics/events.js
- lib/routes/password.js
- test/local/password_routes.js
To complete the conversation in https://github.com/mozilla/fxa-auth-server/issues/1452; @seanmonstar r?
> feat(metrics): Emit an `account.changedPassword` activity event.

- test/remote/db_tests.js
Previously, each test relied on the account being created in the first `it` test case. This moves it to a `beforeEach` and then deletes the account in the `afterEach`. You can use a `it.only` to test a specific test case.
> chore(tests): Make remote db tests independent

- lib/userAgent.js
- test/local/user_agent_tests.js
Fixes #1555.
Firefox-iOS is showing up with ugly user agent strings in the device view. This adds a test to recognise them and return appropriate parsed data instead.
I took the simplest approach of ignoring the Firefox version in the regex here. We could also add a match group to pull that out and return an appropriate `uaBrowserVersion` too if it's preferable. But I thought that was probably unnecessary in light of #1556, which suggests dropping the browser version. And the less specific regex may (or may not) be more robust?
@vladikoff r?
> fix(devices): add special-case recognition of Firefox-iOS

- config/index.js
- lib/features.js
- lib/routes/account.js
- test/local/account_routes.js
- test/local/features_tests.js
- test/local/ip_profiling.js
For consideration, this does not bypass sign-in confirmation when it is specified by a forced email.
Fixes #1547
> fix(bypass): Don't bypass sign-in confirmation for forced emails

- docs/metrics-events.md
I'm starting to think it was a mistake keeping this document in the repo, the continual PRs to update it are getting tiresome. Perhaps it will be okay when the flow event code settles down a bit more, or perhaps I should batch the updates to be less frequent (but I worry about forgetting them), or perhaps I the doc is in the wrong place.
Anyway, this documents mozilla/fxa-content-server#4419.
@vbudhram r?
> fix(docs): document recent fix that affects flow events

- test/test_server.js
Currently, the spawned test server process can not be debugged into. This PR increments the debug port the parent process is running and sets it in the child process.
> chore(debug): Expose debug port for spawned process

- lib/customs.js
- test/local/customs.js
There's one API endpoint that takes the authPW input in a non-standard param, we should sanitize it before sending to customs.  @mozilla/fxa-devs r?
> fix(customs): Sanitize 'oldAuthPW' field when sending to customs.

- lib/metrics/context.js
- test/local/metrics_context_tests.js
Fixes #1571.
`token` was added to these error logs so we could see why `getKey` fails. But dumping the whole token in the error message was wrong (and quite lazy) of me. Really all we're interested in is identifying which field was missing, so that is what this PR does.
@shane-tomlinson r?
> fix(logging): remove raw token data from error log

- lib/routes/account.js
- test/local/account_routes.js
Related to mozilla/fxa-content-server#4477.
We're not quite propagating the metrics context payload through to the end of the `/account/reset` flow, meaning our flow metrics aren't showing completed flows. This change fixes that.
When run against equivalent changes to `fxa-js-client` and `fxa-content-server`, the following flow events show up in the auth server log when you reset your password:
```
flowEvent {"event":"password.forgot.send_code.start","userAgent":"Firefox-iOS-FxA/5.3 (Firefox)","time":1480511151787,"flow_id":"9d0437d21a3bdc251549f65814521325b8beee05326b7870723532a9a25444d0","flow_time":7096,"service":"sync"}
flowEvent {"event":"password.forgot.send_code.completed","userAgent":"Firefox-iOS-FxA/5.3 (Firefox)","time":1480511151808,"flow_id":"9d0437d21a3bdc251549f65814521325b8b …
```
> fix(server): propagate metrics context in /account/reset

- docs/metrics-events.md
- lib/log.js
- test/local/log_tests.js
- test/test_server.js
This logs responses as flow events for routes we've determined are definitely part of a user flow. The format is `route.${path}.${status}`, such as `route./account/login.200` or `route./account/login.400.103`. Includes documentation.
cc @philbooth 
Closes #1526
> feat(metrics): log flowEvents of all requests

- lib/routes/account.js
We don't have any instances of this showing up in Kibana, so I think we can safely remove it.
> chore(login): Remove the legacy `contentToken` parameter from login.

- docs/metrics-events.md
This section of the metrics doc has been getting more unwieldy both to edit and to meaningfully consume. Adding links to the PRs clarifies precisely what is being discussed and when it was merged to `master`.
Additionally, I realised that I lumped the fix for duplicate content server events into train 75, but actually it was merged after that tag.
@seanmonstar, another really meaty and interesting PR for you to look at here, sorry. r?
> fix(docs): add links to prs under "significant changes"

- docs/metrics-events.md
- lib/log.js
- lib/metrics/events.js
- lib/routes/account.js
- test/local/account_routes.js
I should have done the following two things as part of #1578:
1. Call `request.validateMetricsContext()` at the start of the `/account/reset` route handler.
2. Promote the `account.reset` activity event to a flow event.
This change does that.
> fix(server): make account.reset a flow event

- lib/routes/account.js
- test/remote/account_create_tests.js
Fixes #1583 (and also renames the containing function so it's more clear what it does and doesn't do)
@vbudhram r? for inclusion in train-76, so we can get it into prod ahead of a corresponding content-server change.
> fix(signup): Return canonical email address in 'account exists' error.

- lib/error.js
- lib/metrics/context.js
- test/local/metrics_context_tests.js
Fixes #1595.
The "missing token" error generates a lot of log noise because it occurs in legitimate scenarios when trying to gather metrics context data speculatively, from `log.notifyAttachedServices` and `log.flowEvent`.
We were already silencing it in `metricsContext.clear` and actually, due to the above, I think we should silence it in `gather` too. Doing this means `getToken` no longer needs to `throw`, which pleases me because it was only throwing for flow control anyway (my fault).
I also think our logging elsewhere is sufficient to cover any genuine issues relating to missing token data.
@vbudhram r?
> fix(logging): silence spurious "missing token" error noise

- lib/customs.js
- lib/routes/account.js
- test/local/account_routes.js
This fixes #1573 by using the normalized email address in the sign-in unblock feature-flag.  It also does a bit of general refactor to separate the unblocking logic into its own functions, as I was having a hard time keeping my head around the flow.
> Refactor sign-in unblock a little

- lib/mailer.js
- lib/routes/account.js
- lib/routes/password.js
- npm-shrinkwrap.json
- test/local/account_routes.js
- test/local/password_routes.js
- test/remote/account_create_tests.js
- test/remote/password_change_tests.js
- test/remote/password_forgot_tests.js
This PR uses the new verify account sync template and adds location data to password change completed and password change requested. It requires 
Connects with https://github.com/mozilla/fxa-auth-mailer/issues/189
> refactor(signin): Use new verify account sync template and add location data to others

- lib/routes/account.js
- test/local/account_routes.js
- test/mocks.js
Fixes #1426.
In various places we needlessly parse the same user-agent string multiple times. This change eliminates that duplicate effort.
You can test it out by checking the correct user-agent information still appears in emails sent from the `/account/create`, `/account/login` and `/recovery_email/resend_code` endpoints (it's currently deployed to `pbooth.dev.lcip.org` if you want to try it there).
> refactor(server): eliminate duplicate calls to user-agent parser

- lib/bounces.js
- lib/mailer.js
- lib/routes/account.js
- lib/routes/password.js
- npm-shrinkwrap.json
- package.json
- test/client/api.js
- test/client/index.js
- test/local/bounce_tests.js
- test/mocks.js
- test/remote/account_create_tests.js
- test/remote/account_signin_verification_tests.js
- test/remote/password_forgot_tests.js
> refactor(signin): Add support for sending flow metrics in email

- lib/log.js
- test/local/log_tests.js
As per [rfk's comment](https://github.com/mozilla/fxa-auth-server/pull/1576#issuecomment-270045182), the new route-summary flow events aren't working. It turns out they were missing the `/v1` path prefix.
Sample flow event captured with this fix added:
```
flowEvent {"event":"account.created","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:52.0) Gecko/20100101 Firefox/52.0","time":1483434604591,"flow_id":"994908ff1db04960cf8d3dab7f369064cb422d6cd8e3e632bde3d5737f2314de","flow_time":8674,"flowCompleteSignal":"account.verified"}
flowEvent {"event":"route./v1/account/create.200","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:52.0) Gecko/20100101 Firefox/52.0","time":1483434604648,"flow_id":"994908ff1db04960cf8d3dab7f369064cb422d6cd8e3e632bde3d5737f2314de","flow_ti …
```
> fix(logging): add /v1 prefix to flow event route definitions

- config/index.js
r? - @vbudhram, since you looked at the first part in auth-mailer
Simply add config to auth-server that is then passed into auth-mailer. (Has no effect in the default case).
> fix(email): turn on SES Event Publishing metrics

- lib/routes/account.js
- lib/routes/password.js
- npm-shrinkwrap.json
- test/local/lib/log.js
- test/local/lib/server.js
- test/local/pool.js
- test/test_server.js
From mozilla/eslint-plugin-fxa#5
Surprisingly, it doesn't lint about all the `var`s. Probably need to tweak the rule some more.
> style(lib): update `let` to `const` when possible

- lib/db.js
- lib/email/bounces.js
- npm-shrinkwrap.json
- test/local/email/bounce.js
- test/mocks.js
Works just fine, but is missing updated shrinkwrap to use the newest auth-db, so remote tests will be failing until then.
Blocked by https://github.com/mozilla/fxa-auth-db-mysql/pull/199
Connects to #1565
> feat(email): record email bounces in database

- lib/crypto/butil.js
- lib/db.js
- lib/log.js
- lib/pool.js
Fixes #1465.
Friday is Experiment Day. And in addition to experimenting with code, this Friday I am also experimenting with the PR format.
To wit:
This change shifts the burden for unbuffering binary data, from multiple places where we call `pool.put`, `pool.post` or `pool.del` to a single place, inside `pool.request`.
Because sometimes people forget to call `unbuffer` and the effect of doing that may not be immediately obvious. For instance, it was exactly this kind of issue that @shane-tomlinson fixed in #1469.
The default stringification of buffers looks like this:
```js
{ "type": "Buffer", "data": [...] }
```
Our database never expects to receive binary data in that form. Instead it expects binary data as hex strings and reconstructs the buffer from those. Calling `unbuffer` ensures …
> feat(server): auto-unbuffer binary data when crossing API boundaries

- lib/db.js
- lib/devices.js
- lib/routes/account.js
- npm-shrinkwrap.json
- test/local/lib/devices.js
- test/local/routes/recovery_email.js
- test/mocks.js
Fixes #1651
(Should probably be reviewed with w=1 at the end of the github url because there were indentation changes in account.js)
> fix(push): notify a device connected only when account verified

- lib/routes/account.js
- lib/tokens/token.js
- test/local/routes/account.js
- test/local/tokens/key_fetch_token.js
- test/local/tokens/session_token.js
- test/mocks.js
- test/remote/db_tests.js
- test/remote/push_db_tests.js
This is my first stab at trying to find out what's going on with the recent `createdAt` weirdness that was spotted in production. Hopefully there's enough context in these log messages to try and pin down the context. It's meant to be complementary to "other changes" that have been made in "other repos" recently. *NUDGE, WINK*
If possible, I'd like to get it merged in time for train 80, so that we can (hopefully) debug it quicker.
@vladikoff, r?
> fix(logging): log errors when we encounter unexpected createdAt values

- test/local/lib/server.js
- test/local/metrics/events.js
- test/mocks.js
Fixes #1610.
Some tests that I ~~was too lazy to~~ didn't have time to write when I landed #1606. They assert that the server calls `log.summary` correctly and that `request.emitRouteFlowEvent` calls `log.flowEvent` correctly. I also chucked some tests for `log.begin` and `log.error` in there for good measure.
It covers some of the same ground as the tests for `_logEndpointErrors`, yes. I confess that I'm not a massive fan of those tests because they focus on an internal implementation detail rather than the broader, end-to-end behaviour that we're really interested in. In the future, if we're happy with the broader tests, I may come back and rip those narrower ones out.
It covers a case that we weren't explicitly testing before: that `log.flowEvent` is not invoked for non-flow routes. …
> fix(tests): add missing tests for log.begin and log.summary calls

- docs/api.md
- docs/endpoint_data.md
I forgot to write docs for the new `/sms` endpoint! Then I saw @vbudhram's comment about docs in another PR and realised what I'd done! This is my attempt to right that wrong!
> fix(docs): document the /sms endpoint

- lib/routes/sms.js
- test/local/routes/sms.js
Oh man, I am not having a good day.
I was just giving the `/sms` endpoint a final once-over when I noticed a `new` in the fallback error case that should not be there. Surely that errant `new` would cause a `TypeError` at runtime? Why haven't the tests caught that?
Of course, it transpires that I didn't write tests for the fallback error case, so that code was not being tested. And, on writing the test, I realised a separate `TypeError` could occur in the same handler if `err` is undefined.
This change fixes both of those issues and adds a test that catches them.
> fix(sms): make the fallback error case work sanely

- docs/metrics-events.md
We're going to use this rather excellent document as input to a risk-assessment process with a metrics vendor, @philbooth could you please review a couple of small additions?
Also, I noticed that the device-id is not being HMACd in the same manner as the uid.  In retrospect it probably should be, but I'm not sure there's much we can do about it now...
> chore(docs): Add some more details on metrics db column contents.

- lib/metrics/context.js
- lib/routes/account.js
- lib/routes/defaults.js
- lib/routes/password.js
- lib/routes/sign.js
- lib/routes/utils/request_helper.js
- lib/routes/validators.js
- lib/server.js
- test/client/api.js
- test/client/index.js
- test/local/routes/request_helper.js
- test/remote/account_create_tests.js
- test/remote/certificate_sign_tests.js
- test/remote/device_tests.js
This is a backport of a code that has been in production now for a few weeks, coming from the private repo. This strips from the query, payload, and parameters anything which the route doesn't explicitly list out validation for.
The second commit is to adjust the code to new lints that arrived in the public repo.
This must merge before tagging a new train.
> fix(server): disallow any query or payload params without validation

- config/index.js
This is related to https://github.com/mozilla/fxa-auth-server/issues/1611 
We are doing other refactoring right now , so for now we can just flip the switch to turn off this datadog logging and remove the code later...
> feat(logs): disable statsd reporting in config

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
Attempt 2:
Branches from release 81.0 and contains updated auth-mysql-db fix for mozilla/fxa-auth-db-mysql#209.
@vladikoff r?
> Point release 81.1 with createdAt fixes

- config/index.js
- docs/api.md
- lib/routes/sms.js
- lib/senders/index.js
- lib/senders/sms.js
- npm-shrinkwrap.json
- package.json
- scripts/sms/balance.js
- scripts/sms/send.js
- test/local/lib/senders/sms.js
- test/local/routes/sms.js
Fixes #1646, implementing an endpoint for the content server to call before showing the SMS view.
/cc @shane-tomlinson
> feat(server): implement GET /sms/status

- bin/email_notifications.js
- bin/key_server.js
- lib/routes/account.js
- lib/routes/defaults.js
- lib/routes/password.js
- lib/routes/util.js
- lib/senders/sms.js
- lib/server.js
- npm-shrinkwrap.json
- package.json
- test/bench/bot.js
- test/local/lib/senders/translator.js
- test/local/routes/account_devices.js
- test/remote/base_path_tests.js
- test/remote/hpkp_tests.js
- test/remote/misc_tests.js
- test/remote/sign_key_tests.js
- test/test_server.js
Fixes #1674.
There are three breaking changes in particular that affect us:
* Unhandled rejections that reach `done` kill the process. To that end, I've replaced calls to `done` with `then`.
* The second argument to `promisify` is an options object rather than the invocation context. The invocation context is specified via `options.context`.
* Promisification methods ignore multiple callback arguments and resolve the first argument only. There is a new `multiArgs` option to control this.
You can read more about the wider bluebird changes [here](http://bluebirdjs.com/docs/new-in-bluebird-3.html).
> chore(deps): update bluebird

- config/index.js
- lib/routes/sms.js
- lib/senders/sms.js
- test/local/lib/senders/sms.js
- test/local/routes/sms.js
Now that the mailer is inside the auth server repo, there's no need for the `sms` module to return its own ad hoc error structures. Instead it can call `lib/error.js` directly.
At the same time, I also opted to return a proper error for the case where Nexmo throttles us, which fixes #1693.
> refactor(sms): swap out ad hoc error structures for lib/error

- config/index.js
Per suggestion in https://bugzilla.mozilla.org/show_bug.cgi?id=1341160#c14; @vladikoff r?
> fix(config): Use a more generic server url pattern for push registrations

- lib/senders/index.js
- scripts/write-emails-to-disk.js
Evidently I broke this script in d09759c. Yet I was positive I'd tested it after making that change to be sure nothing was broken. But I can't have, because it doesn't work at the moment.
Instead, it fails because the mock sender is not passed through from `lib/senders/index` to `lib/senders/legacy_index`. So instead of writing the emails to disk, it tries to send them out via SMTP.
This change fixes that, and it also fixes a secondary error I introduced, where the script tries to call every mailer method that ends with `...Email`. That pattern was correct in the old set-up, but since the merge it includes a method that the script doesn't want to call. Said method bails because it doesn't receive the correct args, killing the process.
@vladikoff, really sorry about these, care to r?
> fix(scripts): mend the broken write-emails-to-disk script

- Dockerfile-build
- Dockerfile-test
- circle.yml
- scripts/download_l10n.sh
- scripts/test-integrations.sh
- scripts/test-local.sh
This takes over the `circle.yml` file to be used for our docker publishing, to be similar with our other repos.
@philbooth I'm not certain exactly how the fxa-test repo updates itself, but perhaps instead of using a complete mirror, what if we just made a small repo in the fxa-test org that essentially just has the old `circle.yml`, and let that run?
> feat(docker): add docker support with circle-ci

- docs/metrics-events.md
- lib/metrics/events.js
- lib/routes/account.js
- test/local/routes/account_devices.js
This is a WIP PR to emit a new metrics event, which we'll need for the metrics vendor evaluation that's going on right now.  It's a bit of a hack to detect when a user uses the "send tab to device" feature in sync.  In the real world, we'd aim to get this event out of sync telemetry data.  For initial proof-of-concept with metrics tooling, it suffices to cheat a little and log it from within FxA.
@mhammond @grigoryk could you please take a look at my inspection of the payload for 'sync:collection_changed' here, and confirm whether such a push message body does indicate an attempt to send a tab from one device to another?
This needs tests, but if it looks low-risk, I'd like to make a train-82 point release to get this out and logging in production as soon as possible.  The more historical …
> feat(metrics): Log metrics event for sending a tab between devices.

- bin/key_server.js
- lib/metrics/events.js
- lib/routes/account.js
- lib/senders/email.js
- lib/senders/index.js
- lib/senders/legacy_index.js
- lib/senders/sms.js
- lib/senders/translator.js
- lib/server.js
- scripts/sms/balance.js
- scripts/sms/send.js
- scripts/write-emails-to-disk.js
- test/local/lib/mailer_locales.js
- test/local/lib/senders/translator.js
- test/local/lib/server.js
- test/local/metrics/events.js
- test/local/routes/account.js
- test/mocks.js
Fixes [bug 1345006](https://bugzilla.mozilla.org/show_bug.cgi?id=1345006), emitting just the resolved locale on flow events rather than the entire list of acceptable languages.
Doing this necessitated a bit of refactoring:
* `lib/senders/translator` is changed to export a `getLocale` method in addition to the existing function that returns the translator object.
* `lib/senders/translator` is now created at the top level and passed in to the sender modules, so that `getLocale` can be called from `lib/server` to decorate the `request` object with.
With this change in place, the flow events now look like this:
```
flowEvent {"event":"flow.complete","locale":"en","uid":"b639696295e244b6b985d0c12dd9f7af","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:54.0) Gecko/20100101 …
```
> fix(metrics): log locale instead of accept languages on flow events

- lib/error.js
The auto-generated API docs claim their first victim!
I was just reviewing the output from the script I'm working on and noticed that one of the error strings was duplicated. Just a little copy/paste error, nothing too major, but it's nice to have some early validation that the automation is doing its job.
> fix(errors): fix misleading error string for featureNotEnabled

- scripts/test-local.sh
Fixes #1727.
**Before:**
```
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․Started DB server on http://127.0.0.1:8000
․
․․․Started DB server on http://127.0.0.1:8000
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
511 passing (2m)
```
**After:**
```
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․ …
```
> fix(tests): invoke mocha recursively on test directories

- lib/db.js
This is support of our docker-dev work in https://github.com/vladikoff/fxa-docker-dev/pull/7. And it's currently WIP.
----
The idea here is that the auth-server should be able to stand up even if the db-server is currently on fire. We don't actually need to start listening for requests. If an incoming request needs access to the database, we will already correctly send back a 500 if the db connection fails.
> feat(db): make database fault tolerant of db server

- config/popular-email-domains.js
- lib/email/bounces.js
- lib/email/delivery.js
- lib/email/utils/helpers.js
- lib/senders/email.js
- test/local/email/bounce.js
- test/local/email/delivery.js
- test/local/lib/senders/email.js
This PR will log the email domain if it is one of the popular domains, otherwise it logs `other`. The goal for this is to help us identify popular email services that have high bounce rates.
@rfk @seanmonstar r?
Fixes #1689
> refactor(logging): Log emailEvent for bounces and deliveries

- docs/metrics-events.md
We had the bracketed href part of some markdown links on a separate line and GitHub used to render that fine. Now it inserts whitespace between the closing `]` and the opening `(` so they're not parsed as links:
I've fixed it by removing the newlines from the source document.
In addition to that, on some changes I made recently I forgot to include links to the relevant pull requests. While fixing the above I opted to sort those out too.
And there's one other change, which I'll comment on inline.
> fix(docs): fix broken links in metrics events docs

- lib/db.js
- npm-shrinkwrap.json
This PR passes the `emailCode` when using the updated [verifyEmail](https://github.com/mozilla/fxa-auth-db-mysql/blob/46e333b5bb38ceac6529c9355ae13fa99effc006/docs/API.md#verifyemailuid-emailcode).
> Use updated verify email call

- scripts/sms/balance.js
- scripts/sms/send.js
The interface for `lib/senders` changed in 8ea58bf / #1684 but these scripts weren't updated to match. This fixes them.
> fix(scripts): fix the broken sms scripts

- scripts/write-emails-to-disk.js
This PR fixes the write email to disk script. It uses the correct mailer `_ungatedMailer` to create emails.
> fix(script): fix broken write email to disk script

- lib/metrics/events.js
- test/local/metrics/events.js
- test/local/routes/account.js
- test/mocks.js
Fixes [bug 1349830](https://bugzilla.mozilla.org/show_bug.cgi?id=1349830).
On requests that don't have a session token, flow events were being emitted with `uid: null`. In the metrics pipeline, this gets hashed to a very high value. In the import scripts we use `MAX(uid)` when updating `flow_metadata`, which means only uids that hash to a value larger than hashed null show up in the data. Everything else appears to be associated with the hashed null "user".
This fixes that by ensuring we don't emit uids with falsey values. I also took the precaution of calling `toString` predicated on the result of `Buffer.isBuffer(data.uid)`. There wasn't any direct evidence that this is causing us a problem at the moment, but I thought it was worth tightening the function up while I was in there. …
> fix(logging): don't emit null or undefined uid on flow events

- lib/geodb.js
- test/local/lib/geodb.js
Absent-mindedly, I failed to return `countryCode` from `lib/geodb` and stupidly, I failed to spot the problem because there were no remote tests for the SMS endpoints.
This PR uplifts the `countryCode` change from #1766 to `train-83` because I suspect it is causing problems there. Specifically, I presume that [this check](https://github.com/mozilla/fxa-auth-server/blob/train-83/lib/routes/sms.js#L122) always fails for obvious reasons:
```js
return REGIONS.has(result.location.countryCode)
```
@shane-tomlinson, am I right in thinking this would mean we never actually enable SMS on the front end?
> fix(sms): propagate countryCode through our fxa-geodb wrapper

- mailer/config.js
sets `env:` settings of `VERIFICATION_REMINDER_...` for these, for running in docker.
> fix(config): environment expose verification reminder config

- lib/routes/sms.js
- test/client/api.js
- test/client/index.js
- test/local/routes/sms.js
- test/mocks.js
- test/remote/sms_tests.js
@shane-tomlinson, sorry it took me so long to get round to this, flow event stuff is a bit of a nightmare at the moment. Was there an issue for this? Is it what you wanted?
> feat(sms): return country code from /sms/status

- docs/metrics-events.md
- lib/routes/sms.js
- test/local/routes/sms.js
This occurred to me as something we probably want to keep track of. Which regions are we sending SMS to?
> feat(metrics): emit a flow event for the sms region

- config/index.js
- lib/mock-nexmo.js
- lib/senders/sms.js
- test/local/lib/mock-nexmo.js
- test/local/lib/senders/sms.js
@philbooth - before I get too far down a rabbit hole, mind seeing what you think?
The goal is for functional tests to be able to run against fxa-ci w/o actually sending SMS messages and costing Mozilla money for every test, as well as to reduce the number of places where real Nexmo creds are needed.
If this were to land, I imagine a different config value name should be used, as well as extracting the MockNexmo into its own module.
> feat(sms): Mock out Nexmo for functional tests.

- config/index.js
- lib/features.js
- lib/routes/account.js
- test/local/ip_profiling.js
- test/local/lib/features.js
- test/local/routes/account.js
- test/remote/account_reset_tests.js
- test/remote/account_signin_verification_tests.js
- test/remote/flow_tests.js
- test/remote/password_change_tests.js
- test/remote/password_forgot_tests.js
- test/remote/recovery_email_resend_code_tests.js
- test/remote/verifier_upgrade_tests.js
This PR graduates 🎓 the security history and ip profiling features. This removes the `enabled` config values for them and all the corresponding checks in code. There are some whitespace changes so it might be a little better to review with [?w=1](https://github.com/mozilla/fxa-auth-server/commit/3ff423d355511a9e85b4ce8b83f80f006a464d06?w=1).
Fixes https://github.com/mozilla/fxa-auth-server/issues/1695
> fix(config): Graduate security history and ip profiling features

- docs/metrics-events.md
This came out of the OKR retro last night, it documents the experiment table that was created as part of mozilla/fxa-activity-metrics#62.
I also took the opportunity to document the down-sampled data sets and clean up a couple of other small bits.
> chore(docs): document the flow_experiments table

- lib/userAgent.js
- test/local/user_agent.js
Related to #1781.
Updates our user-agent parser to properly handle the new iOS user-agent strings from mozilla-mobile/firefox-ios#2556 / [bug 1350146](https://bugzilla.mozilla.org/show_bug.cgi?id=1350146). Fwiw the old regex still matches them, but it lumps the build number together with the browser version and it doesn't look for the extra OS version info that was added.
This doesn't fix the issue for us, as we're still awaiting an equivalent change to the Android user-agent string and there are also changes to be made to the metric pipeline scripts in `puppet-config`.
/cc @sleroux, this is intended to match the changes from your PR, if have a moment to check that the regex appears to be sane that would be much appreciated, thanks!
> fix(server): recognise the new iOS client UA string

- test/local/bounces.js
- test/local/customs.js
- test/local/devices.js
- test/local/error.js
- test/local/features.js
- test/local/geodb.js
- test/local/log.js
- test/local/mailer_locales.js
- test/local/mock-nexmo.js
- test/local/push.js
- test/local/senders/db_connect.js
- test/local/senders/email.js
- test/local/senders/index.js
- test/local/senders/legacy_log.js
- test/local/senders/pool.js
- test/local/senders/reminder.js
- test/local/senders/sms.js
- test/local/senders/translator.js
- test/local/server.js
- test/local/verification_reminder.js
This has been getting on my wick for a while now. Some of the tests are in `test/local/` and some of the tests are in `test/local/lib/`.
There's no rhyme or reason to it. All of the source is under `lib/` so all of the tests should either be under `lib/` or not be under `lib/`, which means the existence of `test/local/lib/` is completely redundant. Let's just get rid of it and have all those tests in `test/local/`, or sub-directories thereof.
This PR does that.
> chore(tests): move test/local/lib/* up to test/local/

- test/client/api.js
- test/client/index.js
- test/remote/sms_tests.js
Fixes #1774, adding remote tests of the `POST /sms` endpoint. It uses Shane's `useMock` flag because I figure we don't want to spend cash every time we run the tests.
> fix(tests): add remote tests for POST /sms

- bin/key_server.js
From latest.dev
`
{"Timestamp":1492530683953000000,"Logger":"fxa-auth-server","Type":"server.start.1","Severity":2,"Pid":28079,"EnvVersion":"2.0","Fields":{"op":"server.start.1","msg":"failed startup with error","err":"{\"message\":\"listen EADDRINUSE 127.0.0.1:9000\"}"}}
{"Timestamp":1492530683956000000,"Logger":"fxa-auth-server","Type":"promise.unhandledRejection","Severity":0,"Pid":28079,"EnvVersion":"2.0","Fields":{"op":"promise.unhandledRejection","error":"Error: listen EADDRINUSE 127.0.0.1:9000"}}
`
After that, the daemon continues to run, but will accept no connections.
> fix(starup): handle promise rejected on bind failure

- config/dev.json
- config/index.js
- lib/routes/account.js
- test/local/routes/recovery_email.js
The PR exposes a config value for the time X needed for criteria
`When I attempt to add a secondary email that is the unverified primary email on an existing account, and the existing account is more than X old, then the existing account is deleted and my request succeeds.`
Also bounty if someone can figure out a more readable config value for this.
> fix(config): Add config for unverified account to exist before secondary can replace it

- test/remote/sms_tests.js
Found this testing docker locally and with logging on.
```
remote sms (live nexmo)
fxa-auth-server.INFO: geodb.start {"op":"geodb.start","enabled":true,"dbPath":"/app/node_modules/fxa-geodb/db/cities-db.mmdb"}
mail_helper started...
fxa-auth-server.INFO: geodb.accuracy {"op":"geodb.accuracy","accuracy":50}
fxa-auth-server.INFO: geodb.accuracy_confidence {"op":"geodb.accuracy_confidence","accuracy_confidence":"fxa.location.accuracy.uncertain"}
fxa-auth-server.INFO: geodb.check {"op":"geodb.check","result":{"location":{"city":"Mountain View","country":"United States","countryCode":"US","state":"California","stateCode":"CA"},"timeZone":"America/Los_Angeles"}}
1) "before all" hook
remote sms (mocked nexmo)
fxa-auth-server.INFO: geodb.start …
```
> fix(tests): Add timeout for sms

- lib/db.js
- lib/error.js
- lib/routes/account.js
- npm-shrinkwrap.json
- test/local/routes/account.js
- test/mocks.js
- test/remote/recovery_email_emails.js
This PR allows `/account/login` to return a custom error when a user attempts to login with a secondary email. Previously if a user attempted to login with a secondary email, it would return `Account not found error`, which would cause the content-server to prompt to create account 👎 .
Connects with https://github.com/mozilla/fxa-auth-db-mysql/pull/227, which should be merged before this.
> feat(emails): Add custom error for users logging in with secondary email

- config/index.js
- lib/error.js
- lib/routes/account.js
- lib/senders/email.js
- test/local/routes/account.js
- test/local/senders/email.js
- test/remote/recovery_email_emails.js
This builds off of https://github.com/mozilla/fxa-auth-server/pull/1850. It allows a user to create an account from an unverified secondary email. It also returns a corresponding error if user attempts to create an account from a verified secondary email.
> feat(emails): Create account from unverified secondary email

- circle.yml
> fix(circle): fix string comparison on docker push

- lib/features.js
- lib/routes/account.js
- test/remote/recovery_email_emails.js
This correctly resolves `checkSecondaryEmail` if `isSecondaryEmailEnabled` is disabled. Also added some more guards if missing config for secondaryEmails.
Fixes #1871 
@jrgm r?
> fix(config): Correctly resolve if isSecondaryEmailEnabled is disabled

- lib/error.js
- lib/routes/password.js
- test/remote/recovery_email_emails.js
This PR fixes https://github.com/mozilla/fxa-content-server/pull/4996#issuecomment-298347100 by sending a unique error if a user is attempting to reset an account from a secondary email. This will cause the content server not to show the option of creating that account.
@vladikoff r?
> feat(emails): Throw unique error if initiating password reset from secondary email

- docs/metrics-events.md
- lib/routes/sms.js
- lib/senders/sms.js
- test/local/routes/sms.js
- test/local/senders/sms.js
> fix(metrics): include template name in sms.sent event

- lib/cache.js
- lib/metrics/context.js
- test/local/cache.js
- test/local/metrics/context.js
This change came out of my playing about with memcached for #1044. It seemed like it might be worthy of consideration in its own right, decoupling memcached from `lib/metrics/context.js` and providing an abstraction that may be useful if we ever decide to ditch memcached for redis (or whatever).
No functionality has changed, it's just moved around a bit. For instance, here's some sample log data showing memcached-stored metrics context data is still present on flow events:
```
flowEvent {"event":"account.created","locale":"en","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:54.0) Gecko/20100101 Firefox/54.0","time":1491495313907,"flow_id":"613f90c2cebef952fb352cd7b088b84f4bc95e60dc5237c123131d29903914bb","flow_time":28560,"flowCompleteSignal":"account.signed","uid":"ed4b83a1e …
```
> refactor(server): extract memcached usage to a dedicated module

- lib/senders/email.js
- test/remote/account_create_tests.js
When testing some emails, I noticed that we send an `X-Mailer: nodemailer blah blah` header, and many other automated emails from other companies does not include this header. It was noticeable in Gmail when viewing the original message, they highlighted `From accounts as firefox dot com Using nodemailer v2.7.2...`.
It's possible that a spam filter can inspect this header and determine that the mailer was an automated program and not a mail client, though it is easily forged. It's essentially the `User-Agent` header for email. Better to say nothing.
**tl;dr** - We don't need to send it, everyone else doesn't, let's stop.
> feat(mailer): disable X-Mailer header in emails

- config/index.js
- lib/features.js
- lib/routes/account.js
- lib/routes/password.js
- test/local/features.js
- test/local/routes/account.js
- test/local/routes/recovery_email.js
- test/remote/recovery_email_emails.js
From mtg: we wanted the ability to turn secondary emails on/off based on email address regex.
@seanmonstar / @mozilla/fxa-devs r?
> fix(config): Add email regex feature flag for secondary email

- lib/senders/index.js
- test/local/senders/index.js
- test/remote/recovery_email_emails.js
This PR updates how we handle sending email notifications to secondary email. Previously, we were sending all to emails, verified nor not. With this change we only send to verified emails.
Fixes #1887 
@rfk r? / @mozilla/fxa-devs
> fix(emails): Only send email notifications to verified secondary emails

- lib/senders/email.js
- test/local/senders/email.js
Fixes an issue where verify secondary email, change password link at the bottom was undefined from html and text emails.
Ref: https://github.com/mozilla/fxa-content-server/pull/4996#issue-224176438
> fix(emails): Fix issue where change password link was undefined

- config/index.js
Found that softvision has `softvision.com`, `softvisioninc.eu`, `softvision.ro` emails. Updated regex to support this and `restmail.net`.
@vladikoff Does this match what you were expecting? . r?
Fixes #1891
> fix(config): Update secondary email config to support softvision and restmail

- lib/db.js
- lib/routes/account.js
- test/remote/recovery_email_emails.js
This PR fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/275. If a secondary email is unverified in an account A, if another account B attempts to add it, it will add to the account B and deleted it from account A.
> fix(emails): Can create secondary email if it is unverified in another account

- npm-shrinkwrap.json
- package.json
- test/remote/sms_tests.js
Fixes #1821. Fixes #1877.
The secondary change of replacing the live nexmo test with a mocked one was made because that test was only passing by accident. From https://github.com/mozilla/fxa-auth-server/issues/1877#issuecomment-302025879:
> The actual response we're getting from Nexmo in this test is:
> 
> ```js
> {
>   'error-code': '401',
>   'error-code-label': 'authentication failed'
> }
> ```
> 
> Then our own code stupidly treats that like the balance is insufficient:
> 
> ```js
> var balance = result.value
> var isOk = balance >= smsConfig.balanceThreshold
> ```
> 
> In the latest version of the nexmo client, the error is properly returned down the error path and this test fails completely.
With that change made, we can safely update Nexmo and everyone's happy. I've tested the …
> chore(deps): update nexmo

- docs/pushpayloads.schema.json
- lib/push.js
- lib/routes/account.js
- test/local/push.js
- test/local/routes/account.js
- test/local/routes/password.js
- test/mocks.js
This connects to [Bugzilla #1365375](https://bugzilla.mozilla.org/show_bug.cgi?id=1365375).
I also noticed that we sometimes use a Buffer, sometimes an hex String for the `uid` param when we call the push library methods. I hardened the tests using the mock push and made the documentation crystal-clear on what we expect the parameters types to be in these push methods.  
These are the times when you miss strong typing :(
> Send push notification on account destroy

- lib/userAgent.js
- test/local/user_agent.js
Fixes #1889.
Adds handling for user agent strings from the new Sync mobile library.
I was torn between adding a third distinct regex to `lib/userAgent`, thereby creating an ugly chain of if-then-else-if ugliness, or consolidating all of our ~~debt~~ regexes into a single ultra-regex. Here you can see the ultra-regex approach in all it's glory: it starts off okay but then somewhere round the middle becomes completely impenetrable, in the customary style of all great regexes.
I'm happy to revert to separate expressions and explicit conditions if people find this one too unreadable.
There is one requirement from the linked issue that is not addressed here. Quoting from it:
> * Form factor (on Android, "Mobile" or "Tablet"; on iOS, device name instead)
> ...
>
> Which can be parsed to the …
> fix(devices): handle new user agent string from Sync client lib

- lib/email/utils/helpers.js
- test/local/email/utils.js
This may not have been an issue, but when I was building some graphs, I noticed some missing data for locale related to `sent` events, and went sniffing. This simply makes getting headers use the same logic for all 3 email events, which is consistent.
While in there, adding tests for the functionality I was changing (not the whole thing, that for some other eager soul!)
> fix(email): check case insensitive headers in EmailSent event

- docs/api.md
- docs/metrics-events.md
- lib/customs.js
- lib/db.js
- lib/error.js
- lib/metrics/context.js
- lib/mock-nexmo.js
- lib/routes/index.js
- lib/routes/signin-codes.js
- lib/routes/validators.js
- lib/senders/index.js
- lib/senders/sms.js
- scripts/write-api-docs.js
- test/client/api.js
- test/client/index.js
- test/local/customs.js
- test/local/mock-nexmo.js
- test/local/routes/account_devices.js
- test/local/routes/signin-codes.js
- test/local/senders/sms.js
- test/mailbox.js
- test/mocks.js
- test/remote/db_tests.js
- test/remote/signin_code_tests.js
- test/remote/sms_tests.js
Fixes #1882. ~~Do not merge until mozilla/fxa-customs-server#203 is ready.~~
This PR adds a new endpoint, `POST /signinCodes/consume`, that can be called by the content server to exchange a signin code for an email address. Future versions of the endpoint will return other properties to be used for expedited sign-in.
I struggled to write remote tests for the new endpoint. I have local tests and I have remote tests for the new db method, but I couldn't see a non-hacky way to get access to the signin code from a remote endpoint test because it's created out-of-process (so not easily mockable) and not returned to the client (it's only sent out via SMS message).
If we're okay with doing it hackishly, I could do something ugly like write the generated signin code to the file system in the mock …
> feat(server): add endpoint for consuming signinCodes

- CHANGELOG.md
- lib/push.js
- lib/routes/account.js
- npm-shrinkwrap.json
- package.json
- test/local/push.js
- test/local/routes/account_devices.js
- test/mocks.js
- test/remote/device_tests.js
- test/remote/password_forgot_tests.js
This backports the now-deployed-to-production code from https://github.com/mozilla/fxa-auth-server-private/pull/65 into the public repo.  It validates incoming push public keys before writing them to the db, and does so in a way that works around a bug node's handling of invalid keys:
https://github.com/nodejs/node/pull/13275
@vladikoff r?
> Backport ECDH key validation from private repo

- config/index.js
- lib/mock-nexmo.js
- lib/routes/sms.js
- lib/senders/sms.js
- test/local/mock-nexmo.js
- test/local/routes/sms.js
- test/local/senders/sms.js
As can be seen in [this dashboard](https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/PROD%20-%20Auth%20SMS%20status%20errors), we are being rate-limited on the Nexmo balance check:
I have [another branch](https://github.com/mozilla/fxa-auth-server/compare/phil/sms-balance-cached?expand=1) that leans on memcached to avoid the problem but, based on feedback in the meeting just now, it seems like there is more support for just ditching the balance check entirely and assuming we have credit. If sending the SMS fails, we can handle that error there and then.
So that is what this PR does, removes the balance check entirely. Speak up if you think that is the wrong answer, I'm happy to finish off my other branch (I just need to fix the tests). Alternatively, if we think this …
> fix(sms): ditch the balance checks due to rate-limiting woe

- lib/mock-nexmo.js
- test/local/mock-nexmo.js
We were using a made up sender, which caused our email provider
to drop the messages on the ground when testing on fxa-ci. Messages
were reported as delivered, but never seen again.
FWIW, this is the code that's running on fxa-ci right now.
> fix(sms): Use the real email sender when sending via MockNexmo

- docs/api.md
- lib/routes/account.js
- test/local/routes/recovery_email.js
While https://github.com/mozilla/fxa-content-server/pull/5093, stopped us from spamming `500` errors, we still need a better way for checking if secondary emails is enabled for a user while returning `200`.
This follows a similar pattern that `/sms/status` endpoint uses except I call this endpoing `/recovery_email/check_can_add_secondary_address` because `/status` is already being used for checking the status of an email. Open to other names.
> feat(emails): Add endpoint to check if secondary emails are enabled

- docs/api.md
- lib/routes/account.js
- lib/routes/validators.js
Fixes #1932.
Removes one of the validation regexes we had for URL-safe base 64. I opted to remove the original one because it used `*` instead of `+` for the quantifier, which didn't match with the usage of the newer one. By contrast, all usage of the original regex also specifies `allow('')`, meaning that the requirement to match an empty string in the regex itself was unnecessary.
> fix(server): remove duplicate URL-safe base 64 validator

- config/index.js
- lib/bounces.js
- lib/error.js
- lib/senders/index.js
- test/local/bounces.js
- test/local/senders/index.js
The config for each bounce type can now contain a map of counts vs
durations. This allows a tiered approach to blocking email actions based
on bounce history.
For example:
```
{
0: 5000,
5: 20000
}
```
This tier mapping is translated as "more than 0 in 5 seconds" or "more
than 5 in 20 seconds". If either condition is true, the appropriate
error is thrown.
The thrown error also now includes the timestamp of the latest bounce, to
allow for reporting of when exactly that bounce was recorded at.
Closes #1893
> feat(bounces): add tiers to bounce blocklist

- lib/email/utils/helpers.js
- test/local/email/utils.js
We've noticed in the email dashboard that our delivery rate has climbed over 100%, and it seems to correlate with when we shipped secondary emails. If we send an email to 10 users, and 1 has a secondary email, we emit 10 `sent` events, and later SES tells us about 11 `delivery` events.
This patch records additional `sent` events for each address in the `cc` field.
> fix(email): log a 'sent' email event for each CC address

- .travis.yml
- circle.yml
- lib/senders/translator.js
- package.json
**tl;dr** - This makes `npm test` about 112 seconds faster (almost 2 minutes!).
We've added a bunch of tests for some new big features, around SMS, secondary emails, signinCodes, and such. So our test execution time has been slowly growing again. I took another swing at counteracting that.
The changes:
- When running our remote tests, every time we restarted the server, we
would re-parse all of the po translation files. Each time takes around
500ms. By caching files we've already parsed, this shaves around 12s off
the remote test suite.
Since `npm test` is what we run constantly when working on features, if
we can make it faster, we make development faster.
- Disable memcache. We never specifically start a memcached, but the
tests were running trying to look for it. With the default …
> Make our test suite faster (again)

- lib/senders/partials/location/location.html
- lib/senders/templates/new_device_login.html
- lib/senders/templates/password_changed.html
- lib/senders/templates/recovery.html
- lib/senders/templates/unblock_code.html
- lib/senders/templates/verify_login.html
- lib/senders/templates/verify_secondary.html
- lib/senders/templates/verify_sync.html
- test/local/senders/email.js
Uplift from https://github.com/mozilla/fxa-auth-server-private/pull/66
> fix(email): Escape device name in HTML emails.

- lib/db.js
- lib/routes/signin-codes.js
- lib/routes/sms.js
- test/local/routes/signin-codes.js
- test/local/routes/sms.js
- test/mocks.js
- test/remote/db_tests.js
Fixes #1945. See also mozilla/fxa-auth-db-mysql#248.
I've written this PR, both the tests and the production code, so that it can land independently of the related db change. If that PR doesn't make it or is held up for whatever reason, this one can still land without issues (and vice versa). I opted to do it this way so that they can be reviewed in tandem for train 90, without concerns for deployment order or any of that jazz.
Hopefully the changes here are straightforward. We send `flowId` to the db when creating the signinCode, which will be ignored by the db until mozilla/fxa-auth-db-mysql#248 lands. When consuming the signinCode, if a flow id is returned by the db, we emit a `flow.continued` event using said flow id as the `entrypoint`.
This is so that we can link together the two …
> feat(metrics): emit a flow.continued event for signinCodes

- lib/userAgent.js
- test/local/user_agent.js
Fixes #1889.
The code for parsing Sync UA strings assumed that `node-uap` would fail to parse first. But actually it ends up with the browser name `Android` and the browser version `6` when parsing @mcomella's string from https://github.com/mozilla/fxa-auth-server/issues/1889#issuecomment-309182938:
```
Mobile-Android-Sync/(Mobile; Android 6.0) (Unknown app)
```
To fix that, I've promoted our regex to run first, only calling `node-uap` if it doesn't match. This allows the above user agent string to work correctly, producing the following entry in the devices view:
Sorry for not catching this before @mcomella!
> fix(server): step in before node-uap parses Sync UA strings

- lib/routes/account.js
- test/local/routes/account.js
Previously, some of them sent a plain "uid" and some of them sent the "uid" field as "uid@domain" for historical reasons.  This PR makes them all send a plain "uid" field, and include a new "iss" field so that existing applications can continue to piece together the old "uid@domain" form if they need to.
This will need to wait for https://github.com/mozilla-services/tokenserver/pull/107 to hit production before we can ship it.
> fix(notifications): Make data fields consistent across all notifyAttachedServices calls.

- lib/routes/signin-codes.js
- test/local/routes/signin-codes.js
Fixes a bug I introduced with #1946 and mozilla/fxa-auth-db-mysql#248.
Those changes return a `flowId` property from `db.consumeSigninCode`. However, response validation on the auth server endpoint only permits an `email` property.
This PR ensures that we don't fail response validation by dropping `flowId` from the result object.
> fix(server): do not return flowId from consumeSigninCode endpoint

- npm-shrinkwrap.json
- test/remote/db_tests.js
Noticed that the `db_tests` could not run independent tests with the `mysql` implementation. This updates tests to create a new unique user on each test. This update does increase the time for running tests but I think its worth it.
> fix(test): Make db tests more independent and update auth-db dev version

- lib/routes/account.js
- lib/routes/password.js
I went looking for occurrences of #1947 and couldn't actually find any. However, I did find a couple of places where different async calls were invoked serially but were not co-dependent or side-effecty in any way.
This PR eliminates them using `P.all`. I don't claim to have found every case, just a few quick wins I spotted while looking for something else.
> refactor(server): eliminate some unnecessary serial invocation

- lib/routes/password.js
- test/local/routes/password.js
- test/mocks.js
The originating device should already know about the pwd change thanks to a local WebChannel message from the content-server. Avoid sending it a push notification as well, since this could race with the WebChannel message and produce confusion.
WIP, Connects to #1929
> fix(push): Dont notify the originating device about pwd change.

- docs/api.md
- package.json
I just realised the API docs haven't been regenerated in a while (my fault). This change adds the script to the pre-commit hook so that I can give up this ridiculous pretense of remembering to run it manually as needed.
Of course it also picks up all the outstanding doc changes, which are mostly (all?) re-ordering from #1971.
> chore(package): update api docs on pre-commit

- lib/routes/account.js
- lib/routes/password.js
- lib/senders/index.js
- test/local/senders/index.js
This PR does a couple things to verify we are not sending to bouncy emails.
* Don't send to any bounced secondary emails
* If primary email bounced and their exisits a secondary email, send to that email.
Fixes #1953
> feat(email): When primary email bouncy, send to secondary email

- docs/api.md
- lib/cache.js
- lib/metrics/context.js
- lib/routes/account.js
- test/local/cache.js
- test/local/metrics/context.js
- test/local/routes/account.js
- test/local/routes/recovery_email.js
Adds optional `marketingOptIn` payload parameter to `/account/create`.
If set, a flag is set in memcached that the user opted in to marketing.
The `/recovery_email/verify_code` route will check memcached for this
flag, and if found, will set `marketingOptIn` to the message sent to
attached services (SNS).
Closes #1973
> feat(account): send marketingOptIn to attached services on registration

- lib/routes/devices-sessions.js
- test/local/routes/devices-sessions.js
Fixes #1980.
I was in a bit of a funny mood on Friday and the `GET /account/sessions` endpoint in particular annoyed me for some reason. Hence this PR, which does the following:
* Fixes the `userAgent` property so that it is never `'null null'`.
* Makes the map function pure, so that the tests don't have to clone the mock db result.
* Adds assertions for some previously-untested behaviour.
> fix(server): return sane user agent from /account/sessions

- package.json
@seanmonstar pointed this out in IRC last week, that the current precommit behaviour is weird because it leaves an unstaged change in your tree. He also pointed out that the correct approach is to to explicitly `git add` inside the hook, so that the change is magically included in the original commit. This PR does that.
> chore(docs): git add generated api docs in precommit hook

- docs/api.md
- lib/routes/account.js
- test/local/routes/account.js
- test/local/routes/recovery_email.js
After conversing with @shane-tomlinson in IRC, we decided it would be better to save the opt-in intent in the resume token, and send a parameter to `/recovery_email/verify_code`, instead of the auth server having to deal with a cache and expiring values and other unnecessary complexity.
Fixes #1973 for real.
> feat(account): receive marketingOptIn when verifying email codes

- docs/api.md
- lib/db.js
- lib/error.js
- test/remote/db_tests.js
Fixes #1849.
Adds the conflicting device id to the response for errno 124 / `deviceSessionConflict`, which enables clients to save a server round-trip when they encounter that error.
/cc @eoger
> feat(errors): include conflicting device id in errno 124 response

- config/index.js
- test/remote/account_reset_tests.js
- test/remote/account_signin_verification_tests.js
- test/remote/flow_tests.js
- test/remote/password_change_tests.js
- test/remote/password_forgot_tests.js
- test/remote/recovery_email_emails.js
- test/remote/recovery_email_resend_code_tests.js
- test/remote/session_tests.js
Disabling signin confirmation caused a lot of test failures.
Tests that called `loginAndVerify` to get a verified
session have been updated to call `login`.
Tests that work with both unverified and verified sessions
are handled differently. So that it's possible to generate
unverified sessions, config in these tests override
signinConfirmation.skipForNewAccounts.enabled to false.
fixes #1991
> feat(signin): Skip signin confirmation for new accounts by default

- config/dev.json
- config/index.js
- lib/db.js
- lib/features.js
- lib/tokens/session_token.js
- npm-shrinkwrap.json
- package.json
- test/local/features.js
- test/local/tokens/session_token.js
- test/remote/account_locale_tests.js
- test/remote/account_signin_verification_tests.js
- test/remote/certificate_sign_tests.js
- test/remote/db_tests.js
- test/remote/verifier_upgrade_tests.js
Fixes https://github.com/mozilla/fxa-auth-server/issues/1044
Ready for review
Sample of what the redis key/val looks like:
```
{"fxa-auth-session740eb35a75bd4908b8fcbe9efd5a29ad":"[{\"tokenId\":\"781d1b50c3114d60b778a605c576cb82eaa1022165a3ce05aaa855e0585325ec\",\"uid\":\"740eb35a75bd4908b8fcbe9efd5a29ad\",\"uaBrowser\":\"Firefox\",\"uaBrowserVersion\":\"54\",\"uaOS\":\"Mac OS X\",\"uaOSVersion\":\"10.12\",\"uaDeviceType\":null,\"lastAccessTime\":1499357068854,\"createdAt\":1499357068854}]"}
```
> Move session token to redis

- docs/api.md
- lib/db.js
- lib/error.js
- lib/routes/account.js
- lib/routes/emails.js
- lib/routes/password.js
- lib/senders/email.js
- lib/senders/index.js
- test/client/api.js
- test/client/index.js
- test/local/ip_profiling.js
- test/local/routes/account.js
- test/local/routes/emails.js
- test/local/routes/password.js
- test/mocks.js
- test/remote/db_tests.js
- test/remote/recovery_email_change_email.js
This PR exposes the ability of a user to change their primary email address. 
A couple of notes,
- It also is updates `db.account`, `db.emailRecord` to return the same account object that `db.accountRecord` returns. 
- This account object contains a `primaryEmail` object that contains the true primary email address, regardless if the user has changed it or not.
- To keep backwards compatibility with reset password, `emailToHashWith` is sent over in the reset request. The content server correctly accepts this and hashes the new password with this value. This keeps the contract we currently have that password resets are hashed with the original account email.
To test locally, use https://github.com/mozilla/fxa-content-server/pull/5242 and https://github.com/mozilla/fxa-js-client/pull/255. …
> feat(emails): Add change email

- lib/routes/password.js
Fixes #2005 
This bug is fixed in master from https://github.com/mozilla/fxa-auth-server/pull/1983. For some reason I am unable to replicate this error when testing through the remote tests. I am unsure if it has something to do with how the auth-server [client]() is created but a deviceId is not set and therefore does not go into the if block. I tried setting the `user-agent` header in the client but that did not create a device. However, manually testing a change password flow through the gui does correctly trigger the error.
Not to block deployment on having a explicit test case, mind an r @rfk?
> fix(devices): perform string comparison when notifying devices by id

- lib/metrics/events.js
- test/local/metrics/events.js
- test/mocks.js
This is a slightly hackish attempt to emit a flow event that measures request times. It will be good to keep an eye on the direction of these metrics over time, as we add more features and so on. Similar data is already emitted by `log.summary` but that data doesn't end up in redshift, so we can't plot pretty charts with it in redash.
It's slightly hackish because it overloads the `flow_time` property with request time. That's okay because we're not consuming these events as part of any funnels, we're going to query them only for perf charts.
Here are some sample log lines showing the new event immediately after the equivalent request summary and route flow event:
```
request.summary {"op":"request.summary","code":200,"errno":0,"rid":"1500636184060:Phils-MacBook-Pro.local:18131:j5ds0t6g:10 …
```
> feat(metrics): emit route performance events

- lib/db.js
- lib/routes/account.js
- test/local/routes/account.js
- test/mocks.js
- test/remote/account_reset_tests.js
This PR updates the auth-server to call `db.resetAccountTokens` after a successfull password reset which deletes all passwordForgotTokens, passwordChangeTokens, and accountResetTokens.
Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/288
> feat(tokens): delete all account reset tokens on password reset

- docs/api.md
- lib/db.js
- lib/error.js
- lib/routes/account.js
- lib/routes/emails.js
- lib/senders/index.js
- test/local/routes/emails.js
- test/mocks.js
- test/remote/recovery_email_change_email.js
- test/test_server.js
This PR updates the secondary emails endpoints to use the original account email as the feature flag. This fixes an issue where the feature would be disabled when a user changed their primary email address to one that wasn't supported in the regex. Ex. signup with `test@mozilla.com` then change to `a@a.com`, you should still have access to feature even though `a@a.com` is not in regex.
> fix(emails): Check secondary emails feature flag against account email

- lib/routes/emails.js
- lib/senders/email.js
- lib/senders/index.js
- lib/senders/partials/post_remove_secondary.html
- lib/senders/templates/index.js
- lib/senders/templates/post_remove_secondary.html
- lib/senders/templates/post_remove_secondary.txt
- scripts/write-emails-to-disk.js
- test/local/senders/email.js
- test/mocks.js
- test/remote/recovery_email_change_email.js
- test/remote/recovery_email_emails.js
The last pieces to #1948, notify verified emails when a secondary email has been removed.
Fixes #1948 
Matches these [mockup at the bottom](https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit), with the exception of app links which will be worked as part of https://github.com/mozilla/fxa-auth-server/issues/1859.
> fix(email): Notify all verified emails when a secondary email is removed

- config/index.js
- lib/db.js
- lib/pool.js
This allows the `Poolee` config options `timeout` and `maxPending` to be set from the environment as `DB_POOLEE_TIMEOUT` and `DB_POOLEE_MAX_PENDING`.
r? - @rfk
> fix(db): expose config options for Poolee timeout and maxPending

- test/remote/db_tests.js
Fixes #2031.
In addition to writing the new assertions, I also took the opportunity to tidy up those session token tests a bit. They were a bit wall-of-impenetrable-text, so I added some comments and a few line breaks, plus indulged in some minor es6ifying.
I kept the two commits separate in case it makes reviewing easier, see 8e1a676 for the tidy-up and 48c8e90 for the new test cases.
> fix(tests): add coverage for failing redis requests

- lib/db.js
- lib/devices.js
- lib/routes/devices-sessions.js
- lib/tokens/session_token.js
- lib/userAgent.js
- test/local/devices.js
- test/local/tokens/session_token.js
- test/local/user_agent.js
- test/remote/db_tests.js
Fixes #1910.
Changes the behaviour of `devices.synthesizeName` so that it appends the form factor when we have one. If we don't have one, the synthesized name is as it was previously. If we do have one, form factor replaces OS version.
We won't always have the form factor; either because the user agent string didn't contain it or because the session token didn't come from redis. The attempt to add `uaFormFactor` to MySQL from mozilla/fxa-auth-db-mysql#259 was swiftly rolled back in mozilla/fxa-auth-db-mysql#262 because the migration caused problems in prod. In future, if we do add `uaFormFactor` to MySQL, it should just work for `devices.synthesizeName` too.
I also did a spot of refactoring to the `/account/devices` route because the way that it was implemented made it easy to fail …
> feat(devices): include form factor in synthesized device name

- lib/senders/partials/post_remove_secondary.html
- lib/senders/templates/post_remove_secondary.html
- lib/senders/templates/post_remove_secondary.txt
I think it happened due to copy & paste from "You have successfully verified %(secondaryEmail)s as a secondary email to your Firefox Account" sentence. Decided to solve after discussion in mozilla:l10n irc channel.
> [l10n] Change "to" to "from" in remove secondary email message

- lib/senders/partials/post_verify_secondary.html
- lib/senders/templates/post_verify_secondary.html
- lib/senders/templates/post_verify_secondary.txt
- lib/senders/templates/post_verify_secondary_email.html
As discussed in the meeting just now, update the verify secondary email strings to use "for" instead of "to". Related to #2040.
> fix(strings): change "to" to "for" for verify secondary email

- lib/devices.js
- test/local/devices.js
Fixes #2045.
Opened as a patch against train-93 because it's low-impact and that's where the related fix landed.
Before:
After:
> fix(devices): ditch OS in synthesized name if form factor is present

- lib/userAgent.js
- test/local/user_agent.js
Fixes mozilla/fxa-content-server#5203.
Fixes the `uaDeviceType` for these user agent strings:
User agent string|`uaDeviceType`
------|------------
Mozilla/5.0 (Tablet; rv:26.0) Gecko/26.0 Firefox/26.0|tablet
Firefox AndroidSync 1.51.0.0 (Firefox)|mobile
Mozilla/5.0 (Linux; U; en-US) AppleWebKit/528.5+ (KHTML, like Gecko, Safari/528.5+) Version/4.0 Kindle/3.0 (screen 600×800; rotate)|tablet
Mozilla/5.0 (Linux; U; Android 2.3.4; en-us; Kindle Fire Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1|tablet
> fix(devices): saner mobile/tablet recognition for devices

- grunttasks/copyright.js
- grunttasks/eslint.js
I noticed the prepush hook seemed to eslint all the files always. Some searching around shows that we need to configure a target for eslint in order for eslint to save a proper timestamp of last run.
Easy way to compare the difference: run `grunt quicklint` with and without this change. Without, it always runs the full thing. With, after the first run, subsequent runs will print out immediately "No newer files to process."
> chore(eslint): fix eslint task config so newer works

- .travis.yml
- package.json
The prepush hook is slow, and annoying, and leads to people eventually just using `--no-verify` (at least @philbooth  and myself). This removes that hook, since CI will test for this stuff anyways.
Updates CI to do the same template check the prepush hook was doing.
> chore(git): remove prepush git hook

- lib/db.js
- lib/routes/account.js
- lib/routes/password.js
- lib/routes/sign.js
- lib/server.js
- lib/tokens/session_token.js
- lib/userAgent.js
- test/local/ip_profiling.js
- test/local/routes/account.js
- test/local/routes/password.js
- test/local/routes/sign.js
- test/local/server.js
- test/local/tokens/session_token.js
- test/local/user_agent.js
- test/mocks.js
- test/remote/db_tests.js
For the amplitude events, I want access to parsed user agent info before we have a session token object. To that end, I figured it makes sense to move parsing into the `onPreAuth` handler and expose the properties on `request.app`.
This has the side-effect of removing the need for any explicit calls to `lib/userAgent` in the main body of our request-handling code, which should eliminate the possibility of ever calling it multiple times per request again. The other side-effect is that now every request must pay the cost of user-agent parsing, however it feels like useful info to have around and we can keep an eye on the performance charts to make sure that median request times aren't negatively impacted.
> feat(server): add parsed user agent info to the request object

- lib/senders/email.js
I'm adding a couple of new email headers for the amplitude events work, and I intend to set them once in the generic `send` method rather than outside in the message-specific callers. This PR moves the `X-Flow-Id` and `X-Flow-Begin-Time` headers into the common code too, because I noticed they could benefit from the same treatment.
> refactor(email): extract common flow id boilerplate

- docs/api.md
- lib/devices.js
- lib/routes/devices-sessions.js
- scripts/api-docs.handlebars
- scripts/write-api-docs.js
- test/local/devices.js
Elsewhere, I have a branch that adds device registration to `/account/create` and `/account/login`. While working on that I realised that we duplicate the device schema on lots of endpoints. That's too high-maintenance for my liking so I took the opportunity of extracting it to `lib/devices.js`.
Also required a tweak to the doc generation script to pick up the new definitions.
/cc @eoger, just flagging that this has conflicts with your #2073, I'll make sure to incorporate `pushEndpointExpired` if yours gets merged first (and sorry for the hassle your end if not).
> refactor(api): extract device schema to a common definition

- lib/senders/email.js
- lib/senders/index.js
This addresses a pain point I had when adding properties to the data passed to mailer methods in #2069. There are actually three levels of indirection before reaching the core `send` method, and each one independently sets properties on the options object. Adding common properties to all methods involved a load of tedious copy/paste and then for a long time I didn't even realise that I'd missed one of the layers.
That explicit filtering would make sense if the data was about to be exposed publicly or subjected to validation that could make something fail. But neither of those are happening here so it's just annoying.
Here, I've tweaked things slightly on the two innermost layers to lean on `Object.assign` and pass through all properties as they arrive, unless overridden by method-specific …
> refactor(mailer): automatically pass through args to mailer methods

- lib/metrics/amplitude.js
- test/local/metrics/amplitude.js
It was agreed that this event is redundant because of the generic `fxa_email - sent` event and, as such, it's now crossed out in [the taxonomy](https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=879531055). Let's delete it from the code too.
> fix(metrics): remove the forgot_sent amplitude event

- docs/api.md
- docs/endpoint_data.md
- docs/schema.md
- lib/db.js
- lib/devices.js
- lib/push.js
- lib/routes/devices-sessions.js
- lib/tokens/session_token.js
- npm-shrinkwrap.json
- test/e2e/push_tests.js
- test/local/push.js
- test/local/routes/devices-sessions.js
- test/remote/db_tests.js
- test/remote/device_tests.js
- test/remote/push_db_tests.js
Fixes #1873.
Connects to mozilla/fxa-auth-db-mysql#272
(Duplicate of #2073 which was hosted on my repo, CircleCI wouldn't start)
> feat(push): add a pushEndpointExpired flag for devices that need to re-register their push endpoint

- lib/profile/updates.js
- lib/push.js
- test/local/devices.js
- test/local/ip_profiling.js
- test/local/profile/updates.js
- test/local/routes/account.js
- test/mocks.js
Connects to #2085 
After an epic PR by @seanmonstar we now uniformly prefer strings over buffers for passing data around internally.  Unfortunately the profile-update-handling code was still bufferizing the uid before passing it around.  This fixes it to be consistent with what the called code expects, updates the docs to report the correct types, and adds some sanity-checking asserts in our testsuite that might help us avoid this in other places in future.
> fix(profile): Handling incoming uids as strings, not buffers.

- lib/routes/devices-sessions.js
- test/local/routes/devices-sessions.js
I noticed that sometimes Firefox didn't detect a disconnected device, which might be caused by a race in this part of the code.
> fix(push): send push notification after a device is deleted

- lib/push.js
- test/local/push.js
Fixes #2083, but WIP while I do a bit of mucking around with it
> fix(push): Allow device connection push messages for Firefox iOS >= 9.0

- lib/log.js
- lib/metrics/amplitude.js
- test/local/log.js
- test/local/metrics/amplitude.js
While working on mozilla/fxa-content-server#5412, I realised that I'd forgotten to include the top-level `device_id` and `user_id` properties in the amplitude data. This is a quick & dirty PR to add them, which I'd like to slip into train 95 if nobody minds.
> fix(metrics): add missing device_id and user_id amplitude properties

- lib/db.js
- lib/routes/account.js
- lib/routes/emails.js
- lib/routes/password.js
- lib/routes/sign.js
- lib/routes/sms.js
- lib/server.js
- test/local/ip_profiling.js
- test/local/routes/emails.js
- test/local/routes/sign.js
- test/local/routes/sms.js
- test/local/server.js
- test/mocks.js
- test/remote/db_tests.js
Fixes #2015.
This didn't turn out quite as nicely as the user-agent stuff because `getGeoData` is an async call, so we need to consider what to do if it is accessed before the promise has resolved. Ultimately I decided to expose the raw promise as `request.app.geo` because that places the least burden on consuming code.
Some alternatives I discounted were:
* Make the property non-lazy and set it in `lib/server` as soon as `getGeoData` resolves. This would force consuming code to check the value before use and take appropriate action itself if unset, possibly including a duplicate call to `getGeoData`.
* Expose dual `request.app.geo.value` and `request.app.geo.promise` properties. Again it forces consumers to include ugly checks, for the limited benefit of eliminating a call to `.then`. …
> fix(server): make geo data lazily available on the request

- lib/push.js
- test/local/push.js
The client-side code for this is not going to make the 9.0 release of Firefox for iOS, so we need to push the target version back on the server-side as well.
> fix(push): Only send device connection push msgs to iOS 10+

- bin/profile_server_messaging.js
- lib/devices.js
- lib/profile/updates.js
- lib/push.js
- lib/routes/account.js
- lib/routes/devices-sessions.js
- lib/routes/emails.js
- lib/routes/password.js
- lib/server.js
- test/e2e/push_tests.js
- test/local/devices.js
- test/local/profile/updates.js
- test/local/push.js
- test/local/routes/devices-sessions.js
- test/local/routes/emails.js
- test/local/routes/password.js
- test/local/server.js
- test/mocks.js
- test/remote/push_db_tests.js
Fixes #2106.
Prevents us from accidentally calling `db.devices` more than once per request. I saw one definite case of this in `/recovery_email/verify_code` and it's possible there were others. I'll also be making use of this property heavily for the amplitude events, so it will get further usage imminently.
Making the change necessitated pulling calls to `db.devices` out of `lib/push`, which triggered some refactoring that almost got away from me. I'll add inline commentary to call out why things have changed the way they have, but most push methods now take an extra `devices` argument and a few other methods became redundant so I deleted them. I don't *think* I've broken anything.
> feat(server): lazily get devices array on the request object

- lib/metrics/context.js
- test/local/metrics/context.js
- test/local/metrics/events.js
- test/local/routes/account.js
- test/mocks.js
Related to mozilla/fxa-content-server#5487.
We dropped `utm_*` in #1585. Turns out they were being depended on by basket. This PR reinstates them.
> fix(basket): reinstate utm params to the metrics context bundle

- lib/email/utils/helpers.js
- lib/metrics/amplitude.js
- lib/metrics/events.js
- test/local/email/utils.js
- test/local/metrics/amplitude.js
- test/local/metrics/events.js
- test/mocks.js
Fixes #2076.
This mops up some user properties that I forgot about because they were on a separate tab in the taxonomy doc. There's still a couple of outstanding properties not included here, which I've opened standalone issues for because jiggery-pokery was involved.
The properties added are:
* `email_provider`
* `sync_device_count`
* `user_country`
* `user_locale`
* `user_state`
As it stands, it also ditches the duplicate `device_id` and `fxa_uid` properties, although there are still outstanding question marks over those two so best not merge this just yet. I'll confirm back here if/when they get the green light.
> fix(metrics): include missing user_properties on amplitude events

- config/dev.json
- config/index.js
- docs/api.md
- lib/features.js
- lib/routes/emails.js
- test/local/features.js
- test/local/routes/account.js
- test/local/routes/emails.js
- test/remote/recovery_email_change_email.js
- test/remote/recovery_email_emails.js
This removes features.isSecondaryEmailEnabled, but does not remove
the `/recovery_email/check_can_add_secondary_address` check which
checks to ensure the token is verified. I'm unsure whether that call
is necessary because the front-end will not allow a user to visit
/settings if their session is unverified.
fixes #2099 
@vbudhram - r?
> refactor(secondary-email): Remove "add secondary email" feature flag.

- .nsprc
- grunttasks/doc.js
Although this doesn't fix the underlying issue for #2128, it does update the list of dependencies which was hitherto incomplete.
> fix(docs): update dependencies for api doc generation

- .nsprc
- lib/email/bounces.js
- lib/email/delivery.js
- lib/email/utils/helpers.js
- test/local/email/bounce.js
- test/local/email/delivery.js
- test/local/email/utils.js
Opening this for a proposed `96.2` auth server patch, to help debug #2133 in production. My suspicion is that we're expecting headers from AWS that it never provides us, but I'd like to know for sure.
> chore(logs): log error if headers are missing in email notifications

- lib/email/utils/helpers.js
- test/local/email/utils.js
- test/local/senders/email.js
Related to #2133. Supercedes #2138. Opened for a prospective auth server `96.3` patch because it's affecting the amplitude metrics (sorry).
`logEmailEventSent` is not passed the full email headers that are created in `Mailer.prototype.send`. It *is* passed the `message` object that those headers are built from. This change makes it work using that `message` object instead.
The alternative fix would have been to pass in the headers and leave `logEmailEventSent` and `logAmplitudeEvent` untouched. I opted against that because the code to read from the headers is (a little bit) more work than dereferencing `message` directly. But I can still do it that way if it's preferred for reasons of conceptual purity.
Here is an amplitude event showing the correct properties:
```
amplitudeEvent …
```
> fix(metrics): fix the data on email sent events

- lib/metrics/amplitude.js
- test/local/metrics/amplitude.js
- test/local/metrics/events.js
Fixes mozilla/fxa-amplitude-send#6. Proposed for a `96.3` patch release.
The taxonomy document has been updated to use standard event properties where available. This PR implements some of the suggested changes and also proposes a couple of others:
* `user_properties.user_country` => `country`
* `user_properties.user_state` => `region`
* Removed: `user_properties.user_locale`
* `user_properties.ua_os` => `os_name`
* Added: `os_version`
* Added: `device_model`
@davismtl @jbuck r?
> fix(metrics): prefer standard amplitude properties

- lib/error.js
- lib/routes/emails.js
- test/local/routes/emails.js
Thinking about it a little more, I convinced myself this was the best thing to do if postfix fails to send a secondary email verification email.
* Show `Failed to send email.` instead of unexpected error
* Delete secondary email
Fixes #2101
> fix(email): Show proper error and delete email if postfix fails to send

- bin/mailer_server.js
- lib/email/utils/helpers.js
- lib/metrics/amplitude.js
- lib/senders/email.js
- lib/senders/index.js
- lib/senders/templates/_versions.json
- lib/senders/templates/index.js
- package.json
- scripts/template-version-bump.js
- test/local/email/utils.js
- test/local/metrics/amplitude.js
- test/local/senders/email.js
- test/local/senders/sms.js
- test/local/senders/templates.js
Fixes #2097.
Adds an `email_version` property to the amplitude events, which represents a numerical, automatically-incrementing version number for the relevant template. The automatically-incrementing part is handled by a new pre-commit hook. Version numbers are stored in a json file inside the `templates` directory.
Also adds an `email_template` property to the events, because `email_version` on its own makes no sense and may be misleading.
Here is a sample event demonstrating the new properties:
```
{"time":1506606961905,"user_id":"d849bbc4bee44f2592fae62816c002a5","event_type":"fxa_email - sent","session_id":1506606950658,"event_properties":{"email_provider":"gmail.com","email_template":"verifyEmail","email_type":"registration","email_version":1},"user_properties":{"flow_id":"89729796c8 …
```
> feat(metrics): implement email_version amplitude property

- lib/db.js
- lib/devices.js
- lib/routes/account.js
- lib/routes/devices-and-sessions.js
- lib/tokens/key_fetch_token.js
- lib/tokens/token.js
- test/local/db.js
- test/local/devices.js
- test/local/routes/account.js
- test/local/routes/devices-and-sessions.js
- test/local/tokens/account_reset_token.js
- test/local/tokens/key_fetch_token.js
- test/local/tokens/session_token.js
- test/mocks.js
- test/remote/db_tests.js
- test/remote/push_db_tests.js
Fixes #1981.
Removes the `tokenId` property from all token objects and uses `id` instead. Obviously the db schema still contains `tokenId` columns so there's a bit of marshalling in `lib/db.js`. Other than that, `id` is used everywhere.
This means we eliminate some duplication and avoid the stuttering pointed out by @seanmonstar in https://github.com/mozilla/fxa-auth-server/issues/1981#issuecomment-314138217 (may he rest in peace 😞).
> refactor(tokens): prefer token.id to token.tokenId

- test/e2e/push_tests.js
- test/local/cache.js
- test/local/db.js
- test/local/devices.js
- test/local/email/bounce.js
- test/local/email/delivery.js
- test/local/email/utils.js
- test/local/metrics/amplitude.js
- test/local/metrics/context.js
- test/local/profile/updates.js
- test/local/routes/account.js
- test/local/routes/devices-and-sessions.js
- test/local/routes/emails.js
- test/local/routes/password.js
- test/local/routes/session.js
- test/local/routes/sign.js
- test/local/routes/signin-codes.js
- test/local/routes/sms.js
- test/local/routes/unblock-codes.js
- test/local/senders/index.js
- test/local/server.js
- test/local/tokens/token.js
- test/local/verification_reminder.js
- test/mocks.js
Fixes #1655.
We had two implementations of a mock log object, this PR reduces that to one. It also replaces the home-baked spy functionality with the stuff provided by sinon.
> fix(tests): unify the mock log implementations

- lib/db.js
- test/local/db.js
Fixes #2163.
We were passing `undefined` to `redis.get` because the Amplitude metrics make an indiscriminate attempt to use `request.app.devices`.
Changing the logic in the Amplitude code was a bit messier, so I chose to shortcut the call inside `db.devices` instead. If `uid` is `undefined` we know that the request is going to fail, so fail early.
> fix(logging): silence annoying redis log noise

- lib/metrics/amplitude.js
- test/local/metrics/amplitude.js
Related to mozilla/fxa-amplitude-send#21.
Re-uses the client id -> service map that we added for `fxa_services_used` for the `service` event property.
> fix(metrics): map service event property from client id

- lib/push.js
- lib/routes/devices-and-sessions.js
- test/local/routes/devices-and-sessions.js
From https://github.com/mozilla/fxa-auth-server/issues/2156#issuecomment-335679674.
> fix(push): Allow sending verification messages from /devices/notify

- lib/metrics/amplitude.js
- test/local/metrics/amplitude.js
Tangentially related to mozilla/fxa-amplitude-send#19.
Omits the `os_version` Amplitude property if we have no value for `os_name`, which is the same behaviour that I've implemented for the content server in mozilla/fxa-content-server#5587.
@davismtl does that seem like the right thing to do?
> fix(metrics): don't emit os_version if os_name is unset

- lib/push.js
This updates device filtering for iOS. We will only send account verification messages for `Firefox Beta` devices. 
From debugger, ios beta devices show up as `Firefox Beta` for browser name. It doesn't appear that we filter down to build number if that would ever be needed.
@rfk When you get a chance r? Hoping to land this as a point for 97.
Fixes https://github.com/mozilla/fxa-auth-server/issues/2156
> fix(push): Target `Firefox Beta` for account verification messages

- lib/routes/devices-and-sessions.js
- test/client/api.js
- test/remote/device_tests.js
Fixes #2130.
The response from `POST /account/device` must always include "name" and "type" fields, otherwise it fails validation.  As seen in #2130 and [1], a small number of clients are somehow attempting to update a device record that doesn't have a "type" value specified, meaning we don't include a "type" field in the response, meaning we throw a response validation error.
This fixes it by applying the same logic for default "name" and "type" fields as the `GET /account/devices` route.  @eoger could you please sanity-check this as a follow-on to #2130?  @philbooth r?
[1] https://sentry.prod.mozaws.net/operations/auth-prod/issues/668478/
> Always report a name and type in device registration response

- lib/log.js
- lib/metrics/amplitude.js
- test/local/log.js
- test/local/metrics/amplitude.js
It came up in the meeting just now that we should more clearly distinguish the amplitude error messages so that they're not accidentally mistaken for events in the logs. This PR does that.
> fix(logging): more clearly distinguish amplitude error messages

- lib/senders/email.js
Added word "secondary" to subject line to pave the way for primary
> fix(emailVerify):Added secondary to subject line

- docs/api.md
- lib/routes/sms.js
- test/local/routes/sms.js
formattedPhoneNumber is used by the content server to display the
telephone number the SMS was sent to, formatted for the user's country.
fixes #2176
> feat(sms): Return the `formattedPhoneNumber` in the POST /sms response.

- config/index.js
- test/local/routes/sms.js
fixes #2177
@philbooth - I wasn't sure how far down the testing rabbit hole to go for each new country. It seems like most of the test is the same, the important parts are to ensure the sms.send is called correctly, logFlowEvent is called with the correct region, and that the formattedPhoneNumber is returned as expected. Do we need the other parts?
f? @philbooth
> feat(sms): Enable SMS in Austria, Germany.

- config/index.js
- lib/routes/devices-and-sessions.js
- test/local/routes/devices-and-sessions.js
- test/remote/device_tests.js
Related to mozilla/fxa-content-server#5599.
For the device manager OKR, we're replacing the first sync time with an approximate last sync time like "last sync over 2 months ago".
There are two parts to that change, one here and one in mozilla/fxa-content-server#5627. This PR does the auth server portion, implemented in such a way as to be deployable independently of the content server bit. It only adds new properties to the response, so doesn't break older content servers that receive the data.
The change is dependent on new config, the threshold timestamp before which all values should be treated as approximate. I've set that to the time at which auth server 96.4 was deployed (containing #2150). That seemed like the correct time to me, but let me know if it's wrong for whatever reason. …
> feat(devices): return approximateLastAccessTime for old devices

- lib/metrics/amplitude.js
- lib/routes/emails.js
- test/local/metrics/amplitude.js
- test/local/routes/emails.js
Fixes mozilla/fxa-amplitude-send#23.
~~I have an outstanding question for @davismtl on that issue about how I've implemented this, so don't merge just yet.~~
Here's a sample event when the newsletter checkbox was selected:
```
amplitudeEvent {"time":1508752234911,"user_id":"c1aec827141f4fabb1e1cb0d61215d53","device_id":"b98eac7fca63420c94e6a9453ad85c0e","event_type":"fxa_reg - email_confirmed","session_id":1508752189176,"event_properties":{"service":"sync"},"user_properties":{"flow_id":"66965668fd4ee50518fbd72c19c02490da5a2a541b730237c042187c64b5e2dc","sync_device_count":1,"ua_browser":"Firefox","ua_version":"58","$append":{"fxa_services_used":"sync"},"newsletter_state":"subscribed"},"app_version":"98","language":"en","os_name":"Mac OS X","os_version":"10.11"}
```
And here's one when it …
> feat(metrics): add newsletter_state property to amplitude events

- lib/db.js
- lib/devices.js
- lib/routes/devices-and-sessions.js
- npm-shrinkwrap.json
- package.json
- test/local/routes/devices-and-sessions.js
- test/mocks.js
- test/remote/db_tests.js
Related to mozilla/fxa-content-server#5597.
In preparation for content server changes that we want to land in train 100 for the device manager OKR, this PR does a couple of things:
* If the language is English, it includes `stateCode` in the location data for devices and sessions.
* For other languages, it returns the translated country (other fields may be added if we can translate them in the future). If we fail to translate the country for whatever reason, those languages will not receive any location data.
The country translation is handled by a new dependency, `cldr-localenames-full`. The other dependency, `cldr-core`, isn't strictly necessary but including it shuts up an npm warning about unmet peer dependencies.
Note that if we get approval to merge #2180 first, this will need to …
> feat(devices): translate location in devices and sessions response

- lib/senders/email.js
- lib/senders/partials/base/base.html
- lib/senders/templates/new_device_login.html
- lib/senders/templates/password_changed.html
- lib/senders/templates/password_reset.html
- lib/senders/templates/post_remove_secondary.html
- lib/senders/templates/post_verify.html
- lib/senders/templates/post_verify_secondary.html
- lib/senders/templates/recovery.html
- lib/senders/templates/unblock_code.html
- lib/senders/templates/verification_reminder_first.html
- lib/senders/templates/verification_reminder_second.html
- lib/senders/templates/verify.html
- lib/senders/templates/verify_login.html
- lib/senders/templates/verify_secondary.html
- lib/senders/templates/verify_sync.html
- test/local/senders/email.js
WIP PR, using the content server logo to see how things rendered. Waiting for `e.mozilla.org` hosted logo.
Targeting train-98 in case we need to rollback.
> chore(logo): add new logo to email templates

- lib/senders/templates/verify_primary.html
Because #2190 was made against the `train-98` branch, it obviously didn't update the new `verifyPrimaryEmail` template (which doesn't exist there). So when I merged `train-98` to `master`, bustage was created. This unbusts it.
@vbudhram r?
> chore(email): regenerate templates from partials

- config/index.js
- lib/senders/email.js
- test/local/senders/email.js
To help keep our metrics sane, use a different url for verifying your primary email. https://github.com/mozilla/fxa-content-server/pull/5626 adds support for this view.
> fix(links): use a custom url when verifying primary email

- lib/routes/devices-and-sessions.js
- test/local/routes/devices-and-sessions.js
Fixes #2199.
My error logging for #2188 was a smidgen over-zealous. Plenty of devices have no location set in redis and we shouldn't emit log noise for all of them. Really that error exists for the case where the translation lookup failed.
This PR fixes it by shortcutting the body of `marshallLocation` if `location` is not set. Opened against `train-99` for a prospective 99.1 patch.
> fix(logging): don't log errors if location is not set

- config/index.js
Monaco is not enabled as requested, I haven't found a phone
number that validates yet.
mozilla/fxa-content-server#5573
> feat(sms): Enable SMS in Belgium, France, Luxembourg

- lib/db.js
- package.json
- test/local/db.js
- test/remote/db_tests.js
Fixes #2207. Includes and supercedes #2210.
There were a couple of problems with how we were using the redis client:
* Not handling the `error` event made redis connection errors fatal.
* Not disabling the offline queue made redis reads wait indefinitely on a response when redis was down.
This PR fixes both problems, which also necessitated a related tweak to `db.devices` and `db.sessions` so that they don't return a stale `lastAccessTime` when redis fails. If you think there's mileage in it, I could extract that logic to a little wrapper that sets a flag on itself in the error case. I didn't think it was worth the indirection for the sake of two functions, but happy to do it nonetheless.
You can test it out by killing your redis service and then signing up/signing in and viewing the …
> fix(db): sanely handle redis errors

- lib/db.js
Updates `accountExists(email)` to check if email is a secondary email. Since secondary emails are owned by an account, the account is considered to exist.
This change fixes https://github.com/mozilla/fxa-content-server/issues/5394
> fix(emails): update accountExists to check for secondary emails

- bin/email_notifications.js
- bin/key_server.js
- bin/mailer_server.js
- bin/profile_server_messaging.js
- npm-shrinkwrap.json
- package.json
This PR adds newrelic to some background daemons, noting that newrelic must be `require`d first, and updates to latest newrelic@2.3.2, with an `npm run shrink` using npm@2.15
> Dockerpush fix moar enable newrelic

- .travis.yml
- circle.yml
- test/local/db.js
- test/remote/db_tests.js
Fixes #2208.
There were some assertions of behaviour when redis was mocked to fail, which have been moved into the local tests. Other than that everything is still there, except all the testing is now done via db methods or by verifying the state of redis directly.
> fix(tests): test against actual redis instance

- lib/metrics/amplitude.js
- test/local/metrics/amplitude.js
- test/local/metrics/events.js
Fixes mozilla/fxa-amplitude-send#28 (also see mozilla/fxa-content-server#5753).
Having raw client ids in Amplitude isn't helpful. This change replaces them with a fallback string, `undefined_oauth`.
> fix(metrics): stop sending raw client ids to amplitude

- lib/metrics/amplitude.js
- test/local/metrics/amplitude.js
- test/local/metrics/events.js
Related to mozilla/fxa-amplitude-send#28.
If we need to debug the `undefined_oauth` service property, we can now use `oauth_client_id` to do so. Suggested by @rfk in https://github.com/mozilla/fxa-auth-server/pull/2239#discussion_r152868273.
> fix(metrics): include oauth_client_id in amplitude event properties

- npm-shrinkwrap.json
- package.json
Fixes #2128
Fixes nvm usage via https://github.com/typicode/husky/blob/master/CHANGELOG.md#0143
@mozilla/fxa-devs @vbudhram r?
> fix(scripts): use latest Husky module for git hooks

- lib/db.js
- lib/redis/index.js
- test/local/db.js
- test/remote/db_tests.js
Fixes #2222, although I'm also open to the possibility that maybe it's not worth the effort making this last step and just leaving things as they currently are. It's up to you guys.
But anyway, this change stops us paying to store property keys in Redis, by re-packaging them as arrays before writing and unpacking them to the proper object format after reading. In practice, based on my back-of-a-fag-packet calculation made using [this script](https://github.com/mozilla/fxa-auth-server/blob/893dea954f79a009c48e62c26f3a60d3e4b789aa/scripts/redis-benchmark.js), I think it will reduce our stored token size by about 16% or so, depending on the data in the token.
No tests added because the whole point is that this should be invisible to the rest of the code, so the existing test coverage is …
> feat(redis): eliminate property names from redis-stored tokens

- lib/routes/index.js
- test/remote/misc_tests.js
Trying this out in CI...
(edit: Fixes https://github.com/mozilla/fxa-bugzilla-mirror/issues/433)
> Enable hawk payload validation for additional replay protection

- config/index.js
- lib/db.js
- lib/server.js
- test/local/db.js
- test/local/server.js
- test/mocks.js
- test/remote/db_tests.js
Optimistically fixes #2223.
I say "optimistically" because we're limited by my decision to remove `createdAt` from Redis-stored tokens back in #2235. Because of that change, we need the proper session token object from MySQL in order to make a decision about pruning. But of course, many session tokens were already pruned from MySQL so we don't know what their `createdAt` was and can't prune them. Fixing that properly would require us to speculatively read from MySQL for every token in Redis, which is obviously not practical given the size of our database.
Instead, the approach I've taken here is to conditionally prune tokens from Redis whenever we encounter an expired session token object from MySQL. There are two places where that can happen: the authentication hook in `lib/server.js` …
> feat(redis): prune expired session tokens from redis

- lib/routes/devices-and-sessions.js
This PR updates the account destroy device endpoint to pass `{}` on success. With https://github.com/mozilla/fxa-auth-db-mysql/pull/298, we were returning `sessionTokenId`, which caused joi to fail the response validation.
> fix(tests): Fix account destroy device test

- lib/routes/unblock-codes.js
- test/local/routes/unblock-codes.js
This PR updates the unblock route to retrieve a user account using the `db.accountRecord` (checks emails table) instead of the `db.emailRecord` (only checks account able). Doing so, the correct email is used in the unblock process.
Fixes #2256
> fix(unblock): Send correct primary email when blocked

- lib/email/bounces.js
- test/local/email/bounce.js
Fixes #2272 
This PR also contains some slight test/ES6 updates in https://github.com/mozilla/fxa-auth-server/pull/2273/commits/2aad78270d414f766c00511c9bacfda0451e84c7, which is probably best to review with `?w=1` flag.
> fix(bounce): Update bounces lib to use `accountRecord`

- lib/db.js
- npm-shrinkwrap.json
- test/local/db.js
- test/remote/db_tests.js
Fixes #2260, although there may be a small problem with it that I'll describe presently.
It builds on the recent db changes from mozilla/fxa-auth-db-mysql#298, using the returned session token id to remove the matching record from Redis if one exists.
However, the Redis update semantics for `deleteDevice` that I've added here are slightly different to everywhere else. Elsewhere we delete from Redis first, then from MySQL, to minimise the chance of future session tokens being created that have an old zombie with the same id hanging about in Redis. Here the Redis update happens last, which breaks our contract for the relationship between the two.
To be quite frank, I hadn't thought about this when I was rushing to land the db patch. Honouring the contract would entail some pretty hairy …
> fix(redis): delete session tokens from redis in db.deleteDevice

- .travis.yml
- package.json
- scripts/test-local.sh
This adjusts the test-local.sh script to set default values for important env vars like NODE_ENV.  Previously these were only set by `npm test`, and their absense would cause test failures when invoking ./scripts/test-local.sh directly.
I also made a slight change to always pass --recursive flag to mocha, since I can't imagine us ever not wanting this in practice.
~@mozilla/fxa-devs r?~
> chore(tests): Set defaults for env vars in test-local.sh script.

- lib/routes/account.js
Saw this come past in a Sentry notification:
```
Error: An internal server error occurred
File "/app/lib/routes/account.js", line 1188, in handler
uid = auth.credentials.user
File "/app/lib/server.js", line 318, in server.ext
reply.continue()
```
Looking at that route, the entire thing assumes we have `request.auth.credentials` so I don't see why authentication is marked optional. Maybe it was an oversight, or maybe the route has changed from when that setting was made?
Anyway, this PR unoptionals the route, which I presume will prevent these errors showing up in the future. (and means we'll return a 401 instead of a 500)
> fix(api): make authentication required on GET /account/profile

- npm-shrinkwrap.json
- test/remote/token_code_tests.js
Once https://github.com/mozilla/fxa-auth-db-mysql/pull/303 lands all these tests will pass. Previously, in the mem implementation of `verifyTokenCode`, it only verified session tokens and not keyFetchTokens.
Connects to https://github.com/mozilla/fxa-content-server/issues/5886
> fix(tests): Mem impl of `verifyTokenCode` should verify keyFetchToken

- test/remote/account_profile_tests.js
An extra test just to sanity-check #2290, based on some vague bad memories I have from writing the affected code.  It failed before #2290 and passes after, so 👍 AFAICT.  @philbooth r?
> fix(tests): Test that unauthenticated /account/profile rejects cleanly.

- bin/mailer_server.js
- lib/senders/email.js
- lib/senders/index.js
- lib/senders/oauth_client_info.js
- test/local/senders/email.js
- test/local/senders/oauth_client_info.js
Previously it would require() its own version of the logging module, and hence would not correctly use various test stubs and mocks, and hence caused `npm test` to dump a bunch of logging output to the screen when executing the remote tests.  This changes it to accept the `log` object as an argument in a similar style to other modules in this repo.
@vladikoff r?
> fix(logging): Make oauth_client_info use shared logging instance.

- lib/redis/connection.js
- test/local/redis/connection.js
- test/remote/redis_tests.js
I can't remember where or who, but somebody mentioned this error in the last couple of days. It's really nothing we should worry about if it happens every now and then, it just means our guards against unsafe concurrent updates of data in Redis are kicking in successfully.
This change tries to make that a bit clearer, by logging the message at `warn` level and adding a friendly explanatory comment in the code. Don't panic! 😄
> chore(logging): downgrade redis.watch.conflict to warning level

- config/index.js
- lib/db.js
- test/local/db.js
Fixes #2306.
Our pruning of session tokens from Redis is not perfect because we can only delete tokens that are expired-but-not-yet-pruned-from-MySQL. This leaves us with some number of zombie session tokens that are lying around in Redis, the effect of which could be to sometimes show incorrect session information in the device manager (albeit with very low probability).
To eliminate that possbility, this change speculatively deletes from Redis when creating the session token. In addition, the maximum number of Redis connections is bumped up from 100 to 200, because we can expect the number of concurrent Redis operations to increase significantly.
> fix(redis): delete clashing tokens from redis in createSessionToken

- lib/db.js
- lib/routes/account.js
- lib/routes/totp.js
- lib/tokens/session_token.js
- npm-shrinkwrap.json
- test/local/tokens/session_token.js
- test/mocks.js
- test/remote/totp_tests.js
This PR updates the auth-server to use the new verification methods in https://github.com/mozilla/fxa-auth-db-mysql/pull/309. When a TOTP code has been confirmed, the TOTP will become verified and enabled and the `verificationMethod` on the session will be set.
Fixes https://github.com/mozilla/fxa-auth-server/issues/2295
> feat(totp): Add verification methods

- test/local/routes/emails.js
The tests assume that doing `date.setMonth(date.getMonth() - 2)` here:
https://github.com/mozilla/fxa-auth-server/blob/fcf4052d9ff3e2a0dd4e3bb6df83c1089ee5dda3/test/local/routes/emails.js#L148
Will move the timestamp at least 60 days into the past.  That's not true in March, where it will only move it 31+28=59 days.  Thanks so much for an afternoon of complete bafflement at spontaneous test failures, February!
> fix(tests): Make email-polling-expiry tests pass in March.

- lib/routes/token-codes.js
- test/client/api.js
- test/client/index.js
- test/local/routes/token-codes.js
- test/remote/token_code_tests.js
This addresses an oddity that I noticed while digging in to https://bugzilla.mozilla.org/show_bug.cgi?id=1444204; I don't believe it has any security implications apart from possibly some weirdness around rate-limiting, but wanted to clean it up to avoid future confusion.
Since `/session/verify/token` is authenticated with a sessionToken, we know the uid that the session belongs to and do not need it to be passed in via the request body.  This change makes it so we continue to accept `uid` in the request body for b/w compat, but marks it optional and throws an error if it's different to the `uid` of the authenticated session.
@vbudhram r?
> fix(codes): Take token-code uid from the token, not the request payload.

- lib/routes/totp.js
- lib/routes/validators.js
- test/local/routes/totp.js
- test/remote/totp_tests.js
We expect TOTP codes to always be numeric, so let's validate that at the API boundary.
The only thing we do with these codes is pass them to `otplib.authenticator.check`, which runs them through `parseFloat`, so I don't think there's any badness that could ensue from passing in non-numeric values.  But we should reject them for completeness.
@vbudhram r?
> fix(totp): Restrict allowed chars in TOTP code input.

- lib/crypto/butil.js
- lib/routes/validators.js
- npm-shrinkwrap.json
- package.json
- test/local/crypto/butil.js
- test/local/senders/email.js
- test/mocks.js
fix(deprecation): #2343 Check for deprecated APIs
> fix(deprecation): #2343 Check for deprecated APIs

- docs/api.md
- lib/authMethods.js
- lib/routes/account.js
- lib/routes/sign.js
- lib/signer.js
- lib/tokens/session_token.js
- test/client/index.js
- test/local/authMethods.js
- test/local/tokens/session_token.js
- test/remote/account_profile_tests.js
- test/remote/certificate_sign_tests.js
This helps expose the user's MFA state to reliers, by reporting the "authentication methods" and "authenticator assurance level" used when creating a sessionToken, along with the available methods
and maximum level achieveable by the account.
Work in progress for now, but fixes #2314 and fixes #2315 once it's done.
> feat(amr): Report AMR and AAL in relier-facing APIs.

- docs/api.md
- lib/routes/totp.js
- test/remote/totp_tests.js
It turns out the `/totp/exists` endpoint was throwing unverified session error outside of a promise chain, which caused a 500.
Connect to https://github.com/mozilla/fxa-content-server/issues/5991.
> fix(totp): throw unverified session in promise chain

- lib/routes/devices-and-sessions.js
- test/local/routes/devices-and-sessions.js
Fixes mozilla/fxa-content-server#6001.
When I changed the user-agent version info in #2356, I broke the sessions view in the content server. This change fixes that by only returning the major rev from `/account/sessions` and adds a test case that would have caught me breaking it originally.
Note that the related content server test will need to be changed again after this lands.
@vladikoff r?
> fix(sessions): only return major rev for browser version

- lib/customs.js
- lib/db.js
- lib/pool.js
- lib/safe-url.js
- npm-shrinkwrap.json
- package.json
- test/local/db.js
- test/local/pool.js
- test/local/safe-url.js
Ref: [bug 1447452 (comment)](https://bugzilla.mozilla.org/show_bug.cgi?id=1447452#c19)
Even though we validate incoming data, we should belt-and-braces ensure that unsafe input can never make it into URLs that we request. This change seeks to do that by adding a new module to build parameterised path strings safely, failing any requests where bad input is encountered.
See also the discussion about bikeshed colours in #2361. The key difference from that PR here is that, if a raw path string is passed to `pool.request`, it now fails.
> chore(db): prevent the possibility of future url-injection bugs

- lib/devices.js
- lib/routes/account.js
- lib/routes/session.js
- lib/routes/validators.js
- test/local/routes/session.js
- test/local/routes/validators.js
- test/remote/device_tests.js
Previously we could accept URLs with unescaped special characters such as newlines or unicode, which means we were depending on other layers of the code to handle them correctly.  This change makes the
requestor responsible for properly escaping any special characters in their URLs before passing them in to us.
@philbooth r?
> fix(validation): Reject URLs with unexpected characters.

- lib/metrics/amplitude.js
- test/local/metrics/amplitude.js
- test/local/metrics/events.js
Fixes mozilla/fxa-amplitude-send#60.
Amplitude's view of devices is skewed by the randomly-generated `device_id` that we're using until cross-project ids are implemented. And the `sync_device_count` property is skewed to a lesser degree by apparent session-related problems that seem to force some users to sign in repeatedly on a single device.
To mitigate those problems, this change adds three new properties that indicate the number of devices that were active in a given time period:
* `sync_active_devices_day`
* `sync_active_devices_week`
* `sync_active_devices_month`
In this case, a "month" is 30 days.
Example log line showing the new properties:
```
amplitudeEvent {"time":1522231500788,"user_id":"dbbf4e8198b34d60bf0bda7d1c7c7128","device_id":"9b56f22335484800871ba44ba6076c8a","event_typ …
```
> feat(metrics): add user properties for active device counts

- config/index.js
- docs/api.md
- lib/routes/totp.js
- npm-shrinkwrap.json
- package.json
- test/local/routes/totp.js
- test/remote/totp_tests.js
This PR adds a configurable window for TOTP codes to be valid, defaulting to 1.
Fixes https://github.com/mozilla/fxa-content-server/issues/6005
> fix(totp): add totp code window valid config

- docs/metrics-events.md
Related to #2375.
The code to identify default locales [was removed about a year ago](https://github.com/mozilla/fxa-auth-server/pull/1793). Now, finally, the docs are updated to match.
> fix(docs): remove old/misleading information about the locale property

- lib/routes/totp.js
- test/client/api.js
- test/remote/totp_tests.js
Connects to https://github.com/mozilla/fxa-auth-server/issues/2355
> fix(email): only send new sign-in emails for sync when verifying with totp

- lib/metrics/amplitude.js
- npm-shrinkwrap.json
- package.json
- test/local/metrics/amplitude.js
- test/local/metrics/events.js
Fixes mozilla/fxa-shared#11.
WIP until I fix the tests and the `fxa-shared` changes land.
> refactor(metrics): use boiler-plate amplitude code from fxa-shared

- lib/routes/totp.js
- test/local/routes/totp.js
When the user enables or disables TOTP on their account, publish a "profileDataChanged" event so that attached services will know to update their cached copy of the user's profile data.  Connects to https://github.com/mozilla/fxa-profile-server/issues/313; @vbudhram r?
> feat(profile): Send "profileDataChanged" event when modifying 2FA status

- lib/metrics/context.js
- test/local/metrics/context.js
- test/mocks.js
We're tweaking the flow id validation a little bit, so this PR introduces a dual check. First it tries to check the new way then, if that fails, we try again the old way. In the next train, we can remove the old way entirely and update the tests to match.
Only way to test this really is to make sure flow events are emitted when it is run against the content server in `master` and the content server in `pb/flow-sig-ua`, which I'll be opening a PR for presently.
> fix(metrics): stop using user-agent string in flow id check

- lib/log.js
- test/local/log.js
While writing https://github.com/mozilla/fxa-auth-server/pull/2391#issuecomment-380728358, I noticed that the log line for an error in `log.flowEvent` is easy to confuse with an actual flow event.
Of course the error level is different, but the two bodies are kind of similar and the `op` property is very similar:
* ```
log.flowEvent {"op":"log.flowEvent","data":{"event":"route.performance./account/reset","locale":"en","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:61.0) Gecko/20100101 Firefox/61.0","time":1523522808577,"device_id":"d90fff2f94684ee1b2733accc047b36e","flow_time":256,"flowCompleteSignal":"account.signed"}}
```
* ```
flowEvent {"event":"route.performance./password/forgot/send_code","locale":"en","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; …
```
> chore(logging): use a less confusing op on flow event errors

- lib/senders/email.js
This change makes the email title consistent with the content.
fixes mozilla/fxa-content-server#6073
> fix(totp): Change 2FA removed email title to `Two-step authentication disabled`

- docs/service_notifications.md
@vladikoff as mentioned earlier in the week, here are my initial notes on the events we publish and what services should do when they receive them.  r?
> feat(docs): Add documentation for "attached service" notification events

- lib/senders/email.js
- test/local/senders/email.js
From IRC:
```
rfeeley> vbudhram: oooh also notice that the "Manage account" buttons in the email do not link to a specific email address. will help prevent accidents for some users if it does.
<vbudhram> Vijay Budhram rfeeley: ah didn't notice, there might be some more emails that need it too
```
This PR appends the email query param to `Manage Account` email link. When a user clicks the email link, it will try to open the settings page for that email or redirect to login if they are not currently logged in.
Fixes https://github.com/mozilla/fxa-auth-server/issues/2093
> feat(emails): add email to all manage account email links

- config/dev.json
To help test https://github.com/mozilla/fxa-content-server/pull/5922, the redirect domain env needs to be set to `127.0.0.1`.
> chore(config): update redirect domain for dev.json

- lib/notifier.js
- test/local/notifier.js
In service of #2387, this adds "event_type" and "email_domain" message attributes to our SNS notifications, so that we can filter on these when forwarding the notifications to SQS.
> feat(notifications): Add SNS msg attributes for service notification filtering

- scripts/must-reset.js
It looks like the `must-reset.js` script got left out of the epic "death to buffers" refactor of #1950 - it's still trying to call the long-since-removed `butil.bufferize` function, but in fact can safely leave the uid as a hex string.
This script does not have any tests, and I haven't added any here, but we should.  In the meantime this unbreaks it in service of https://bugzilla.mozilla.org/show_bug.cgi?id=1456771
> fix(scripts): Remove obsolete `bufferize` call from must-reset script.

- lib/metrics/context.js
- test/local/metrics/context.js
Added in #2391, this code was a fallback to handle a change in how the content server generates the flow id. Now that mozilla/fxa-content-server#6044 has stuck in prod, we can remove the fallback.
I meant to get this done before we cut train 111 but didn't get round to it, so will tag a point release containing this change if nobody objects.
> fix(metrics): remove old flow signature fallback code

- config/index.js
- lib/senders/sms.js
- test/local/mailer_locales.js
- test/local/senders/index.js
- test/local/senders/sms.js
Related to #2428.
Log a success message when a budget check succeeds, so we can easily compare the relative volumes of successful and failed checks in the logs.
I have a slight fear that the knock-on effect this message has in the tests may be non-deterministic, because the budget check happens in a subsequent tick and ends up inserting itself in the way of some unrelated test cases. But the test changes here seem to work both locally and in CI, so hopefully it's fine. It's worth keeping an eye out for future flakiness though, because this could easily be the cause of it.
> fix(logging): log successful sms budget checks

- docs/api.md
- lib/routes/password.js
- test/remote/password_change_tests.js
Connects to https://github.com/mozilla/fxa-auth-server/issues/2313
This isn't the full refactor as described in the issue above, but it does add some checks around the `/password/change/finish` endpoint to ensure that the session has been TOTP verified.
> fix(password): require totp verified session to change password

- docs/api.md
- scripts/write-api-docs.js
Fixes #2434.
This is a hack on top of a hack on top of a hack. The whole doc generation script is an ugly mess, but at least this produces better output than what we currently have. Well, it does until the next code change that comes along and breaks it, anyway.
> fix(docs): fix devices validation output of the doc generator

- .nsprc
- npm-shrinkwrap.json
- package.json
[One](https://nodesecurity.io/advisories/658) is fixed by updating `base64url`, no associated code changes necessary.
[The other one](https://nodesecurity.io/advisories/664) I think we're okay on because we only send validated input to `request` (the `service` param).
> fix(nsp): fix nsp warnings

- lib/metrics/amplitude.js
- npm-shrinkwrap.json
- package.json
Fixes mozilla/fxa-shared#23.
Moves `EMAIL_TYPES` back into this repo for easier maintenance when new email types get added.
> refactor(metrics): move amplitude email types back here from fxa-shared

- lib/routes/account.js
- lib/routes/session.js
- test/local/routes/session.js
Per https://github.com/mozilla/fxa-auth-server/pull/2300#pullrequestreview-123105409, removes specifying `verificationMethod` via a query param.
> fix(params): remove query param for verificationMethod

- lib/routes/devices-and-sessions.js
- test/remote/device_tests.js
The 'capabilities' field has been removed, but some clients still send it.
We need to explicitly avoid echoing it back to them in the registration
response, or the response will fail validation.
Fixes #2477; @jrgm r?
> fix(devices): Do not echo 'capabilities' field in device registration response.

- docs/api.md
- docs/recovery_keys.md
@vbudhram I gave your recovery-key docs a light edit, r?
Of note, I tried to clean up the terminology a bit, and it differs from what's in the google doc.  I think we need to call the top-level token the "recovery key" rather than "recovery code" as it is in the google doc, to avoid confusion with the other thing called recovery codes in this repo.  Thoughts?
> chore(docs): Expand docs for recovery key usage.

- config/index.js
- docs/api.md
- docs/device_registration.md
- docs/pushpayloads.schema.json
- lib/db.js
- lib/devices.js
- lib/error.js
- lib/push.js
- lib/pushbox.js
- lib/routes/devices-and-sessions.js
- lib/routes/index.js
- lib/routes/validators.js
- npm-shrinkwrap.json
- package.json
- test/local/db.js
- test/local/push.js
- test/local/pushbox.js
- test/local/routes/devices-and-sessions.js
- test/mocks.js
- test/remote/db_tests.js
- test/remote/device_tests.js
- test/remote/push_db_tests.js
- test/remote/session_tests.js
This is an extension of and alternative to the "device messages" feature from #2328, that's designed to support the latest requirements of new-send-tab while being a step along to road to a more general [peer discovery API](https://docs.google.com/document/d/1btFmS9jahtKllX3Xm-icPBxvnQKGUmT9-OZzq_M29Sw/).
As part of its device registration, a device can include a set of "supported commands".  This is a simple mapping where the keys are string URIs naming commands that the device can be asked to perform, and the values are additional metadata necessary in order to invoke the command.  Other devices can query the device list to discover their peers and the commands that they support, and can invoke a command on another device by issuing a `POST` request.
A good place to start is the new …
> Add support for "device commands" feature.

- config/index.js
- lib/senders/email.js
- lib/senders/email_service.js
- test/local/senders/email.js
Fixes #2411 
This is using fxa-email-service to send emails when the email matches the ` /emailservice.[A-Za-z0-9._%+-]+@restmail.net$/` pattern.
r? @vladikoff @philbooth
> feat(email): use fxa-email-server for specific email addresses

- config/index.js
- lib/senders/email.js
- test/local/senders/email.js
I'm putting this forward as a blunt-instrument proposal to fix mozilla/fxa-content-server#6258. It completely removes `utm_source=email` from the links we send out, which has the obvious knock-on effect of not overwriting `utm_source` in Amplitude:
```
{"op":"amplitudeEvent","event_type":"fxa_email - click","time":1530797664542,"user_id":"1f705b2692bc4565bf6a3f25d610d841","device_id":"81a9e7d7aa8c4de0a1cbcb3d3b64068c","session_id":1530797640628,"app_version":"115","language":"en","os_name":"Mac OS X","os_version":"10.11","event_properties":{"service":"sync","email_type":"registration"},"user_properties":{"entrypoint":"menupanel","flow_id":"c4bd39952cae9955fd90b3e892f5a4941a9ccea993e1b70aee76a4fa1a83dcb0","ua_browser":"Firefox","ua_version":"63.0","utm_campaign":"fx-welcome","utm_content":" …
```
> fix(metrics): don't force utm_source=email on links in emails

- lib/senders/email_service.js
If, say, `fxa-email-service` isn't running and you try to send email using it, requests fail and no `body` is passed to the response handler. This causes the auth server to fail messily with a 500 error:
```
{"op":"request.summary","code":500,"errno":999,"rid":"1531159435204:Phils-MacBook-Pro.local:56504:jjekohf0:10034","path":"/v1/account/create","lang":"en-US,en;q=0.7,fr;q=0.3","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0","remoteAddressChain":["127.0.0.1"],"accountRecreated":true,"t":205,"uid":"00","service":"sync","keys":true,"email":"emailservice42@restmail.net","stack":"TypeError: Uncaught error: Cannot read property 'messageId' of undefined\n    at Request._callback (/Users/pb/code/fxa-auth-server/lib/senders/email_service.js:34:25)\n …
```
> fix(email): gracefully handle errors from fxa-email-service

- lib/email/utils/helpers.js
- lib/metrics/amplitude.js
- lib/senders/email.js
- npm-shrinkwrap.json
- package.json
- test/local/email/utils.js
- test/local/metrics/amplitude.js
- test/local/senders/email.js
Fixes mozilla/fxa-email-service#113.
Uses the new properties we added in mozilla/fxa-shared#29 to add `email_service` and `email_sender` properties to Amplitude sent/delivered/bounced events.
Sample logs showing the new properties:
* Sent via the auth server.
```
{"op":"amplitudeEvent","event_type":"fxa_email - sent","time":1531159286730,"user_id":"c62efde0062b4093afd88566bdfd97d9","session_id":1531159276644,"app_version":"115","event_properties":{"service":"sync","email_type":"registration","email_provider":"other","email_sender":"","email_service":"fxa-auth-server","email_template":"verifySyncEmail","email_version":1},"user_properties":{"flow_id":"4799f3f71f2c8a3989c20fabbe96ce0eb2e68442438e53c2c9e0cf01e08429e6","$append":{"fxa_services_used":"sync"},"sync_device_count":0,"sync_active_de …
```
> feat(metrics): add amplitude event properties for email service/sender

- config/index.js
- lib/customs.js
- lib/error.js
- test/local/customs.js
If we can an error response when talking to customs-server, the auth-server currently fails open.  This can lead to silent failures of our rate-limiting logic when customs is misconfigured or called incorrectly, as seen in [1].
ISTM that the risk of accidental failure of security measures should outweigh the convenience of handling misconfigured customs-server URLs, and we should fail closed on any error from customs server.  If you don't want a customs-server, explicitly disable it.
This PR changes the default config to have customs-server preffed off, and changes the behaviour to fail closed when it is preffed on.  I think those behaviours are the least likely to cause security footguns, but I'm worried about breakage in our various deployments:
* Do we now need to explicitly pref on a …
> fix(customs): Fail closed if customs-server gives an error.

- test/mail_helper.js
Extracted from https://github.com/mozilla/fxa-auth-server/pull/2511
Added this logs for debugging purposes while working on https://github.com/mozilla/fxa-email-service/pull/122 , but they are very useful so I thought it would be good to send this in.
r? @vladikoff
> chore(emails): log smtp port in mail_helper.js

- config/index.js
- test/local/senders/email.js
In the current master, if sesConfigurationSet is not explicitly in config/<env>.json or in the environment, then config.sesConfigurationSet does not exist as a key. It seems to me the default should be an empty string anyways.
r? - @philbooth
> fix(email): make config.sesConfigurationSet default the empty string and assert key is always there

- lib/server.js
Fixes https://github.com/mozilla/fxa-auth-server/issues/2542
Per https://github.com/hapijs/hapi/issues/3658
> fix(hapi): use the new server event error handler

- scripts/download_l10n.sh
While sitting on the train w/ a terrible 3G connection,
it took about 10 minutes to update the repo, mostly
downloading l10n.
I noticed we delete the l10n directory and re-clone
*every time* we do an `npm install`. This seems
heavy handed.
This change checks if the l10n directory exists,
if it does it reverts any local changes and pulls.
If the directory doens't exist, then clone the
l10n repo.
not attached to any issue.
@vladikoff - I don't remember why we delete the l10n directory every time we install. This approach seems like it should be safe, maybe I'm forgetting some context? r?
> chore(install): Only clone the l10n repo if needed.

- lib/db.js
- test/local/db.js
Fixes #2537.
I did spend a bit of time trying to figure out how this might have happened, but couldn't see anything obvious. Solar particle / cosmic ray?
Anyway, if the data is invalid JSON it doesn't seem like there's much we can do about it. To stop those endpoints from failing, this change deletes the offending "JSON" from Redis and returns an empty object instead. Effectively we will be starting from scratch for session token updates with that user.
Fortunately, Sentry has only told us about this happening once, so the logic shouldn't kick in with any regularity.
> fix(redis): recover from invalid token JSON in Redis

- scripts/must-reset.js
Not associated with an issue, but this fixes the busted script.
> fix(reset): update must-verify script to use string instead of buffer

- lib/server.js
Uplift https://github.com/mozilla/fxa-auth-server/pull/2555 from master to train-117.
> fix(sentry): server.events.on takes channels, not channel

- lib/server.js
- test/mocks.js
I found this while working on the OAuth devices api:
https://github.com/mozilla/fxa-auth-server/blob/5caedf31c36108becb3768804813c8893ccc1af2/lib/tokens/session_token.js#L118
As you can see above `tokenTypeID` is a class variable, which means the following condition will never be true.
https://github.com/mozilla/fxa-auth-server/blob/5caedf31c36108becb3768804813c8893ccc1af2/lib/server.js#L117
> fix(sessionTokens): actually prune expired session tokens

- lib/senders/email.js
- lib/senders/email_service.js
- test/local/senders/email_service.js
Related to #2565.
The response handler for the email service was not creating error objects for error responses, so the call to `sendMail` was succeeding in those cases. I've changed it here so that `sendMail` fails and also tweaked the logging a little bit to give us better error info.
Although this addresses the auth server end of things for #2565, I notice that even with this fix applied the user is still told to go and check their email. I need to do some more digging to see whether that needs some content server code to change too (or whatever).
> fix(email): ensure email-service errors fail the call to sendMail

- lib/routes/account.js
- npm-shrinkwrap.json
- test/remote/account_login_tests.js
- test/remote/token_code_tests.js
This PR changes how the `verificationMethod` param behaves.
Previously, if the `verificationMethod` param was specified in a login requrest, the auth-server would force the client to verify using that method. This was regardless whether or not a verification was required (aka skip if account is new, or skip if they recently logged in). This behavior was put in place so that we could reduce any outliers in the `tokenCode` experiment. 
This change makes the `verificationMethod` optional. If a client specifies this param *and* it has to perform a verification, then this method will be used, otherwise it is not used.
These changes are safe to make because the `verificationMethod` is only specified in our tokenCode experiment, which is currently turned off.
Fixes #2466
> feat(codes): expose verificationMethod as optional

- lib/senders/email.js
- test/local/senders/email.js
In #2535 I forgot to call `JSON.parse` on the live email config in Redis. Nothing exists to write that config yet, so it was only the unit tests that I was running against and they were all wrong too. This change fixes both.
> fix(email): JSON.parse live email config after reading from redis

- lib/routes/account.js
Fixes #2563
I believe this was regression from https://github.com/mozilla/fxa-auth-server/commit/63738c85b5443c7e15bc03610deec9f1223e03eb#diff-ab87c506e682e952973178a41792df12L1241
> fix(server): do not return customs.flag in the destroy route

- .travis.yml
- README.md
- package.json
- scripts/email-config.js
- test/local/senders/email.js
- test/scripts/email-config.js
Fixes #2497 (I think).
Adds a script for managing the Redis-stored live email config. The script supports commands for reading and writing the config, reverting the last changes and checking the resolved state for a given email address.
The script is also used to implement integration tests for the read code, so that we can have confidence in the end-to-end process of writing then reading.
And there's tests for the script itself too of course. Those are pretty slow (because exec), so I'm not running them as part of a standard `npm t`. They're included in the travis build though and you can run them locally with `npm run test-scripts` if you need to.
> feat(email): write live email-sending config to redis

- scripts/email-config.js
- test/scripts/email-config.js
While trying to reproduce issues @jrgm was having with the live email config in stage last night, I spotted a couple of improvements that could be made to the script:
1. Because it was instantiating a real logger to give to the `redis` module, auth server config was being logged to `stdout`. This breaks the script's aim of being pipe/cmdline-friendly, because only the intended output should end up on `stdout`. Fixed by instantiating a mock logger instead.
2. When we parse the live email config, we reject regexes that contain a terminating quote character or look like they might redos us (have a star height greater than 1). It makes sense to reject those when setting them too.
Unfortunately I didn't manage to reproduce the actual problem I'm looking for yet, but in the meantime this still …
> Small improvements for the email-config script

- lib/routes/validators.js
- test/local/routes/validators.js
Fixes #2568.
The user part of an email address is limited to 64 characters, but our validation wasn't enforcing that. Before trying to fix that problem, I wrote some unit tests for the validation code because there weren't any. They uncovered a separate problem, where a regex was mistakenly using `+-\/` as a character range, so I've fixed that here too.
After that, feeling confident with the extra test support, I opted to simplify the whole function and boil it down to just two regexes and a call to `String.split`. Mostly that was for readability, but there's also a micro-optimisation in there because the old code was rather curiously testing regexes on individual characters, iterating through the string.
> Fixes for email address validation

- docs/api.md
- scripts/write-api-docs.js
Fixes #2521.
Two things were wrong with it:
1. We started using object destructuring, which necessitates a version bump for the JS version in Acorn.
2. The upgrade to Hapi 17 changed the property name for route settings from `config` to `options`, so the script needed the same.
> fix(scripts): fix the broken api docs generator script

- lib/devices.js
- lib/routes/devices-and-sessions.js
- test/local/devices.js
- test/local/routes/devices-and-sessions.js
- test/mocks.js
Fixes #2533.
This is the obvious fix but it might not be the right one. In the linked issue, @rfk mentions concern that a patch like this might be masking some deeper problem. But given there are actual 500 errors in prod that will go away with this fix applied, I still think it's worth doing (and it seems like we may have caused more of these ourselves anyway when we truncated `deviceCommands`).
> fix(devices): check token.deviceAvailableCommands before dereferencing

- test/mail_helper.js
This is kind of a hack, unfortunately. It was necessary because of the way email-service dependencies do things.
See discussion: https://github.com/mozilla/fxa-content-server/pull/6470
r? @vladikoff
> fix(mail_helper): remove '<' from to headers in email service requests

- lib/email/bounces.js
This wasn't actually causing anything to be wrong and it's covered by tests so I almost didn't bother changing it. But the operator precedence is slightly different to what was (presumably) assumed by this code and it came up in https://github.com/mozilla/fxa-auth-server/pull/2602#issuecomment-416592053, so I figured it's worth honouring both the spirit and the letter of the law.
Anyway, `!` has [higher precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#Table) than `&&`, which means that this line:
```js
const suggestAccountDeletion = !! bounce && bounce.bounceType
```
...is the same as:
```js
const suggestAccountDeletion = (!! bounce) && bounce.bounceType
```
...so it ends up resolving to either the value of the `bounceType` …
> chore(email): force value to boolean in account deletion check

- config/index.js
- lib/routes/totp.js
- test/remote/recovery_code_tests.js
Not associated with an issue, just some config cleanup found while working on https://github.com/mozilla/fxa-content-server/pull/6482. 
This removes the `recoveryCodes.length` config since it is not configurable via the auth-server but rather the auth-db-server. This also uses the correct recovery code count value.
> fix(config): update correct recoveryCodes config

- lib/senders/email.js
- test/local/senders/email.js
Related to #2577.
Speaking to @jrgm just now he noticed that this problem is only intermittent in stage too. That made me wonder if the call to `redis.get` is failing and, foolishly, like a fool, I didn't put any logging inside that `catch`.
This adds logging both there and around the associated `JSON.parse`, even though we know the latter is not a problem here because the call to `sendMail` itself is succeeding. But anyway, they could both do with some logging.
> fix(logging): log errors when reading/parsing live email config

- docs/api.md
- lib/devices.js
- lib/routes/validators.js
- test/remote/device_tests.js
- test/remote/token_code_tests.js
- test/remote/totp_tests.js
@vladikoff - here's a slightly different take on your PR. I added a `pushUrl` validator to avoid other https URLs being allowed to have a `:443`.
> fix(validation): allow https pushCallback URLs that contain :443

- npm-shrinkwrap.json
- package.json
- scripts/mocha-coverage.js
- scripts/test-local.sh
- test/remote/db_tests.js
Another potential fix for https://github.com/mozilla/fxa-auth-server/issues/2534. This PR has successfully ran tests 5 and 10 times in a row, ref https://circleci.com/gh/mozilla/fxa-auth-server/3368.
I think part of the flaky test failures might involve `proxyrequire` and caching modules. When running the local and remote test suites individually I could not get the majority of errors in https://github.com/mozilla/fxa-auth-server/issues/2534. I thought using proxyrequire with `noPreserveCache()` and `noCallThru()` would fix the issue but I could not determine the exact modules that needed them (it is probably very time consuming as well).
To that end, this solution just splits remote and local tests and updates coverage tool to combine from both runs.
> fix(tests): split running remote and local tests

- docs/api.md
- lib/db.js
- lib/error.js
- test/remote/recovery_key_tests.js
Fixes https://github.com/mozilla/fxa-content-server/issues/6498
This was previously returning a 500 `unexpected error` when a user attempted to create a recovery but already had one. This PR gives them a shiny custom error in that scenario.
> fix(keys): return proper error when failing to create duplicate recovery key

- npm-shrinkwrap.json
- package.json
- scripts/tls-shrink.sh
Continuing from the discussion in the meeting just now, this change adds a script that forces shrinkwrap to use TLS URLs.
Not sure where the best place for it to live is because we may want to use this in multiple repos. But anyway, if this lands I can use it to unblock myself in #2640.
> feat(scripts): force registry links in shrinkwrap to use tls

- docs/api.md
- lib/routes/account.js
- lib/routes/sign.js
- lib/signer.js
- lib/tokens/session_token.js
- npm-shrinkwrap.json
- test/remote/account_profile_tests.js
- test/remote/certificate_sign_tests.js
- test/remote/db_tests.js
Connects to https://github.com/mozilla/fxa-auth-server/issues/2490
This PR adds `fxa-profileChangedAt` to the `/cert/sign` endpoint. This will be used by the oauth-server to add this property in the id token. This also adds `profileChangedAt` to the `/account/profile` endpoint. This will be used by the profile server to compare profile change times and invalidate cache added as needed.
> fix(profile): add profileChangedAt to cert sign and profile

- scripts/tls-shrink.sh
@shane-tomlinson pointed out that the script I wrote for forcing TLS URLs in shrinkwrap is not portable. This change makes it portable.
> fix(scripts): make tls-shrink script portable

- lib/metrics/context.js
- lib/routes/password.js
- lib/server.js
- test/local/metrics/context.js
- test/local/routes/password.js
- test/mocks.js
Related to #2496.
We are planning to deprecate metrics context payloads on endpoints where it is not strictly required. This means only endpoints that start a flow or endpoints that occur outside of any flow will accept metrics context payloads in the future. The motivation for making this change is to reduce the likelihood of metrics weirdness arising from conflicting metrics context data being set mid-flow.
The account reset flow includes three different token types. By stashing metrics context as each new token is created, we can stop sending it to the subsequent endpoints in some future content server change without interrupting metrics.
There is no observable effect from making this change. Stashed metrics context is ignored when an endpoint receives metrics context data in the …
> fix(metrics): stash metrics context during the account reset flow

- lib/senders/sms.js
- test/local/senders/sms.js
Related to #2647.
Sometimes the attempt to dereference the result from `GetMetricStatistics` fails. Maybe it will help if we can see what the entire serialised result looks like, so this change logs that in the error message.
> chore(sms): log JSON-serialised result if we fail to parse max spend

- lib/senders/sms.js
- test/local/senders/sms.js
I factored out the polling and ran it live. The granularity of data for this metric is 5 minutes, so using a 5 minute period and a starttime at least 5 minutes in the past always produces a result.
fixes #2647
r? - @philbooth
> fix(sms): use a five minute period on polling

- config/index.js
- lib/senders/email.js
- test/local/senders/email.js
Connects to https://github.com/mozilla/fxa-content-server/issues/6599
This PR creates a new config option that will prepend a subdomain (`confirm`) to our `/verify_email` and `/complete_signin` email links.
I was able to test this in our stage environment since it has been setup to use to the redirect. Here is a video of it in action using a custom build of https://github.com/mozilla-mobile/firefox-ios/pull/4284.
https://drive.google.com/file/d/1ukcSZZ8MnwBH_NVPoKjs9LrIBvzyryf6/view?usp=sharing
> fix(emails): expose config to prepend domain to verification emails

- lib/senders/email_service.js
- test/local/senders/email_service.js
Blocks mozilla/fxa-email-service#198.
The code review for mozilla/fxa-email-service#198 suggested fixing the property names on errors returned by the email service. Since they're already depended on by the auth server, we need to change them here first.
It's safe to just make the switch in both places on the same train but just in case that PR doesn't land in this train for some reason, I've opted to handle both error structures as a first step. When the other change has definitely merged, we can remove the old property name.
> fix(email): handle the new error structure from fxa-email-service

- lib/senders/email.js
- test/local/senders/email.js
Fixes #2665.
`logEmailEventSent` expects a bunch of header data that is set on an object that is not passed to it. This change just ensures those headers are copied to the argument.
> fix(email): include data from headers in email sent events

- lib/metrics/context.js
- lib/routes/account.js
- lib/routes/emails.js
- lib/routes/password.js
- lib/routes/unblock-codes.js
- lib/routes/utils/signin.js
- lib/server.js
- test/local/metrics/context.js
- test/mocks.js
Fixes #2675.
A number of places that were sending emails assumed they had access to `flowId` and `flowBeginTime` on the request payload. However, we're in the process of changing some of those endpoints so that they don't receive metrics context data in the payload.
To fix this, all endpoints are changed here to read metrics context data via a lazy getter that falls back to loading from memcached if there's no flow data in the payload. This happened to be a nice refactor anyway, fitting in with our broader adoption of lazy getters. It makes the code more resilient to change and reduces the frequency that we hit the cache with.
Opened against train 123 because metrics are about to break when that hits production otherwise.
> fix(metrics): ensure email events use stashed flow data where applicable

- lib/routes/account.js
- test/local/routes/account.js
Sorry, another late metrics fix for train 123.
In #2642, a new `request.propagateMetricsContext` method was added to support propagation of metrics context data through each stage of the account reset flow. What's here is something that should have been part of that change: two calls to `request.stashMetricsContext` in the `/account/reset` endpoint.
Those calls will not do anything now that the content server stopped sending metrics context data to `/account/reset` in train 123. This means that the flow completion events will not be emitted. By changing those two calls to `request.propagateMetricsContext` instead, it fixes the issue.
> fix(metrics): ensure metrics context is propagated from /account/reset

- bin/email_notifications.js
- config/index.js
- lib/email/notifications.js
- test/local/email/notifications.js
Fixes #2633.
Once the email service starts handling bounce, complaint and delivery events we will need a way for it to tell the auth server to emit metrics. This change adds a handler + config for a new SQS queue to that end. It duplicates some of the code from other handlers but that's intentional, we plan to remove those queues eventually.
If this gets merged I'll update the deploy doc with a note about the new queue.
> feat(metrics): add code and config for email service notification queue

- .circleci/config.yml
- .travis.yml
- README.md
- docs/api.md
- lib/routes/account.js
- lib/routes/emails.js
- lib/routes/password.js
- lib/routes/recovery-codes.js
- lib/routes/totp.js
- package.json
- test/client/api.js
- test/local/routes/account.js
- test/local/routes/password.js
Fixes #2496. Fixes #2681.
Previously we identified some endpoints that were receiving metrics context data but would work equally well propagating stashed data instead.
There's been some work to prepare those endpoints, e.g. in #2642 we ensured metrics context gets propagated through the account reset flow. And in mozilla/fxa-content-server#6639 we stopped sending metrics context data to these endpoints. Ergo, it is now safe to remove it from the payload schemata.
Note that this change presented us with a dilemma in the remote tests for account reset. Some of the assertions there check that metrics context data is set in the email headers correctly. That now depends on memcached in order to work, but we were disabling memcached in the test config. Rather than delete those assertions, …
> chore(api): remove metrics context data from deprecated endpoints

- fxa-oauth-server/config/test.json
- fxa-oauth-server/lib/routes/key_data.js
- fxa-oauth-server/test/api.js
This fixes the following 500 error, which @eoger helpfully triggered in production:
https://sentry.prod.mozaws.net/operations/oauth-prod/issues/4883316/
> fix(key-data): Fail cleanly when the client has no allowedScopes.

- lib/routes/account.js
- lib/routes/emails.js
- test/local/routes/account.js
- test/local/routes/emails.js
It came up in [bug 1502164](https://bugzilla.mozilla.org/show_bug.cgi?id=1502164) that we don't always write a log line when deleting an account. This change does so and tries to include a deletion reason in the `op`, to make it easier to understand what's happened based on a single log line.
> fix(logging): log the reason for account deletions

- lib/email/notifications.js
- test/local/email/notifications.js
The email service made a conscious break with the SQS notification structure, to make the recipients array more uniform. Rather than sometimes being an object with an `emailAddress` property and other times being a string, it makes the items plain strings on all notification types.
(for reference, see the `bounced_recipients`, `complained_recipients` and `recipients` properties in [src/queues/notification.rs](https://github.com/mozilla/fxa-email-service/blob/master/src/queues/notification.rs))
When I added code for the new notification queue to this repo in #2684, I forgot about that and just ported the SQS logic verbatim. This fixes it to always expect plain strings in the recipient arrays.
> fix(metrics): use correct format for email service notifications

- test/remote/db_tests.js
In https://github.com/mozilla/fxa-auth-db-mysql/pull/421, the `accountRecord_4` stored procedure got rolled back. That means code depending on the `profileChangedAt` property will no longer work.
This commit removes the assertions of that property that were added to the remote db tests in #2638, but it doesn't revert anything else from that changeset. The property is also returned from `GET /account/profile` and `POST /certificate/sign` endpoints, so the ultimate consumers of those may need to be on their toes.
I'm mostly opening this to unblock CI for train 124.
> fix(tests): remove assertions of profileChangedAt property

- docs/api.md
- lib/error.js
- lib/routes/account.js
- lib/routes/emails.js
- lib/routes/utils/signin.js
- test/local/geodb.js
- test/local/routes/account.js
- test/local/routes/emails.js
- test/local/server.js
- test/remote/db_tests.js
In #2664, we added an error for email-sending failure to some routes. Quite reasonably, we made it a 500 on the assumption that it probably indicated a problem somewhere in our email-sending infrastructure, but it turns out that in most cases it indicates a user mistyped their email address. That causes Sentry to alert us pretty noisily, so this change seeks to return a 422 instead in cases where the email address is unverified.
Some rationale behind that decision:
* We still want actual infrastructure errors to be a 500, so I opted to keep the 500 in place on `/account/login`, where the email address has probably been verified before.
* For `/account/create` and `POST /recovery_email`, I wanted something different to a 400 so that it was distinct from our regular validation errors. The …
> chore(errors): make email-sending errors a 422 for new addresses

- lib/routes/account.js
- lib/routes/emails.js
- lib/routes/utils/email.js
- lib/routes/utils/signin.js
- npm-shrinkwrap.json
- package.json
- test/local/routes/account.js
In #2565, we added an error for email-sending failure to some routes, originally a 500. Then in #2707, we switched it to be a 422 because the 500 was noisily alerting us in Sentry for lots of cases where a user had just misspelled their email address. Then @jrgm pointed out that we already have error types in place for bounce/complaint checking and we should really be propagating those rather than inventing a new error type where possible.
So this commit wraps up the `cannotSendEmail` logic from those previous PRs into a little helper function that:
1. Checks the origin error and propagates that if it is a bounce or complaint.
2. Otherwise, returns a 422 if the email address was not previously verified.
3. Otherwise, returns a 500.
Opened against the `train-124` branch for tagging as a …
> fix(errors): reinstate bounce error failures/messaging

- fxa-oauth-server/lib/server/index.js
Same deal as https://github.com/mozilla/fxa-auth-server/pull/2555/files.
Sentry is not configured for oauth in stage. But when I built production:
```
{"Timestamp":1541442915235000000,"Logger":"fxa-oauth-server","Type":"server.prod","Severity":6,"Pid":6,"EnvVersion":"2.0","Fields":{"msg":"Disabling response schema validation"}}
(node:6) UnhandledPromiseRejectionWarning: ValidationError: Invalid event listener options {
"name": "request",
"listener": function (req, ev) {\n      const err = ev && ev.error || null;\n      let exception = '';\n      if (err && err.stack) {\n        try {\n          exception = err.stack.split('\\n')[0];\n        } catch (e) {\n          // ignore bad stack frames\n        }\n      }\n\n      Raven.captureException(err, {\n        extra: {\n …
```
> fix(oauth-sentry): arg to server.events.on is "channels" (plural)

- fxa-oauth-server/npm-shrinkwrap.json
- fxa-oauth-server/package.json
- grunttasks/bump.js
Fixes #2720 
r? - @mozilla/fxa-devs
> fix(release): on `grunt version(:patch?), bump both ./package.json and fxa-oauth-server/package.json

- fxa-oauth-server/config/dev.json
- test/local/geodb.js
- test/local/server.js
Fixes https://github.com/mozilla/fxa-auth-server/issues/2726; @jrgm r?
> fix(config): Add imageUri for reference browser client-id

- test/known-ip-location.js
- test/local/geodb.js
- test/local/routes/emails.js
- test/local/routes/session.js
- test/local/server.js
- test/mocks.js
As suggested by @shane-tomlinson in https://github.com/mozilla/fxa-auth-server/pull/2727#issuecomment-436976181, let's stop asserting a single specific city for the location tests and instead use a `Set` of the previous values returned by fxa-geodb. IIRC, that's Mountain View, Oakland, San Francisco and San Jose.
> chore(tests): make geolocation assertions more robust

- fxa-oauth-server/lib/db/mysql/index.js
Fixes https://github.com/mozilla/fxa-auth-server/issues/2725
> chore(oauth): Remove unused `profileChangedAt` parameter in db call.

- fxa-oauth-server/bin/purge_expired_tokens.js
- fxa-oauth-server/lib/db/memory.js
- fxa-oauth-server/lib/db/mysql/index.js
- fxa-oauth-server/test/db/index.js
No hurry on this change. But while running `./bin/purge-expired-tokens.js` I thought this would be useful. Maybe this script is safe to run concurrently, but, at minimum, multiple runners would create redundant load on the database (and increased latency on api endpoints) for no real gain.
Feel free to criticize this as I've never had a good feel for how the oauth db code works.
> fix(purge): use GET_LOCK("purge_expired_tokens.lock", 3) to only allow one-at-a-time

- config/index.js
- lib/routes/account.js
- test/local/routes/account.js
Fixes #2685
This PR exposes an environment config that can contain email addresses that will always skip any sign-in confirmation emails. We opt to use an explicit list here to avoid any accidental regex foot-guns.
> feat(signin): add ability to skip signin confirmation for specific emails

- fxa-oauth-server/lib/db/mysql/index.js
- fxa-oauth-server/lib/db/mysql/patch.js
- fxa-oauth-server/lib/db/mysql/patches/patch-025-026.sql
- fxa-oauth-server/lib/db/mysql/patches/patch-026-025.sql
Fixes https://github.com/mozilla/fxa-auth-server/issues/2695
As noted in https://github.com/mozilla/fxa-auth-server/issues/2695, the performance of this query was causing problems in production:
```
DELETE FROM tokens WHERE userId=? AND clientId IN (?);
```
It's fast if MySQL decides to use the `tokens_user_id` index, and it's very slow of if MySQL decides to use the `tokens_client_id` index.  Unfortunately MySQL's choice here doesn't seem very scrutable - in my testing it will choose `tokens_client_id` if the list of clients has only a single element, while in production it appears to choose `tokens_client_id` unless there's a foreign key constraint on the `clientId` column.
Double unfortunately, we can't use index hints to influence MySQL's choice, because they're not supported on raw …
> fix(db): Improve query performance when deleting tokens for public clients

- lib/metrics/amplitude.js
- test/local/metrics/amplitude.js
Fixes mozilla/fxa-activity-metrics#110.
This is a hack to fix the login complete numbers in Amplitude for train 126. I did try a "proper" fix too, but [it backfired](https://github.com/mozilla/fxa-shared/pull/37) and I don't have time to implement the alternative suggestion for this train. We can replace this with something more appropriate when there is time.
> fix(metrics): emit login complete amplitude event after reset complete

- lib/email/utils/helpers.js
- lib/routes/account.js
- lib/routes/password.js
- lib/routes/utils/signin.js
- test/local/email/utils.js
- test/local/routes/account.js
- test/local/routes/password.js
- test/local/routes/utils/signin.js
Related to mozilla/fxa-activity-metrics#109.
Currently our `fxa_email - sent` amplitude events do not include the device id, which may be causing problems with the funnels with Amplitude. This change fixes it by passing the device id to the mailer in our sign-in, sign-up and reset flows, and also by setting the property on the correct object when calling the amplitude module.
Here is an example event from before these changes (without `device_id`):
```
{"op":"amplitudeEvent","event_type":"fxa_email - sent","time":1543488875186,"user_id":"92edc9c2522745d29c96d99daab0f759","session_id":1543488852908,"app_version":"126","language":"en","event_properties":{"email_type":"reset_password","email_provider":"other","email_sender":"ses","email_service":"fxa-auth-server","email_template":"recoveryEma …
```
> fix(metrics): ensure email sent amplitude events include device id

- lib/senders/email.js
- lib/senders/partials/new_device_login.html
- lib/senders/templates/_versions.json
- lib/senders/templates/new_device_login.html
- lib/senders/templates/new_device_login.txt
- test/local/senders/email.js
Fixes https://github.com/mozilla/fxa-auth-server/issues/2197
Adds manage account button in `New sign-in` email. Approved in https://github.com/mozilla/fxa-auth-server/pull/2747
> fix(email): add manage account button in new device login email template

- lib/metrics/events.js
- test/local/devices.js
- test/local/metrics/events.js
- test/local/routes/account.js
- test/local/routes/devices-and-sessions.js
- test/local/routes/emails.js
- test/local/routes/password.js
- test/local/routes/sign.js
- test/local/routes/utils/signin.js
Related to mozilla/fxa-activity-metrics#108.
We'll also need to update the import scripts and the Heka filter.
> feat(metrics): add country and region to activity and flow events

- fxa-oauth-server/lib/routes/authorization.js
- fxa-oauth-server/lib/routes/key_data.js
- fxa-oauth-server/lib/routes/token.js
- fxa-oauth-server/lib/validators.js
- fxa-oauth-server/test/api.js
We had another instance of #2687, which finally encouraged me to dig in and fix it.  The `validators.scope` validator will now automatically parse and return a `ScopeSet` object, and any errors thrown during the parse will be handled cleanly as validation failures.
Unlike the way we do custom validators [in the auth-server codebase](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/validators.js), this implementation uses Joi's public extension API to add a new data type.  If we like it, we should consider refactoring the auth-server validators to this this as well.
Fixes #2687.
> feat(validation): Have `validators.scope` automatically parse the value to a `ScopeSet`.

- fxa-oauth-server/docs/api.md
Spotted by @ryanfeeley; @mozilla/fxa-devs r?
> chore(docs): Fix typo "depricated" -> "deprecated"

- .circleci/config.yml
Our build pipeline wants to find this file in version.json, so put it in all the places.
r? - @vladikoff 
(p.s., this will need to go into a v1.128.1 release)
> fix(circle): can never have enough version.json

- .nsprc
[Advisory 766](https://www.npmjs.com/advisories/766) points out that it's possible for untrusted content to break out of the `sandbox` dependency. However that's not the case in our usage, where input is expanded inside JavaScript strings and has been validated previously anyway.
Our invocation of `sandbox` looks like this:
```js
sandbox.run(`new RegExp("${regex}").test("${emailAddress}")`
```
Here, `regex` is a string from our Redis instance, which can only be written to by our ops team. And `emailAddress` is a string from the front-end which has been validated by Joi at the API boundary.
But more importantly, both are wrapped as strings in the evaluated code and a preceeding check ensures that they do not terminate their enclosing string prematurely:
```js
if (regex.indexOf('"') !== -1 …
```
> chore(package): disable security advisory 766 for sandbox dependency

- fxa-oauth-server/lib/routes/redirect.js
- fxa-oauth-server/test/api.js
Barring keys_jwk from GET /authorization broke Notes. We can't break Notes.
fixes mozilla/notes#1440
@vladikoff - r?
> fix(oauth): Allow keys_jwk through GET /authorization

- .circleci/config.yml
Minor point, and I realize @vladikoff chose to set this to `fxa-oauth-server`, but, if I remember correctly, the intent was that `/__version__` could be used to located the source code of an image.
This (https://mana.mozilla.org/wiki/display/SVCOPS/New+Service+Guide#NewServiceGuide-/__version__) is a little imprecise on that point though.
> fix(circle): version.json "source" should be code repository

- fxa-oauth-server/config/dev.json
Each environment maps this endpoint to its content server
> fix(config): use local redirect for the reference browser

- config/index.js
- fxa-oauth-server/config/dev.json
- lib/oauthdb.js
- test/local/oauthdb.js
- The `sub` change is because of
https://github.com/mozilla/fxa-auth-server/blob/fa4baba5b468c8a0e4f071c965a55af4b5e6d0a4/fxa-oauth-server/lib/assertion.js#L117.
- `megaz0rd` is the default `oauth.secretKey` in `fxa-auth-server`.
> Scoped keys data fixes

- lib/metrics/events.js
- test/local/metrics/events.js
Fixes #2850.
`/password/forgot/status` and `/recovery_email/status` are hit frequently, generating lots of events which aren't very useful. If we skip them we can appreciably reduce the amount of data that passes through our logs, our metrics pipeline and into Redshift.
Additionally, there are a number of specific `/recoveryKey/...` endpoints that also generate useless event data (although nowhere near as many events as the other two). I've stopped emitting those too.
> fix(metrics): stop emitting route flow events for status endpoints

- lib/senders/email.js
- test/local/senders/email.js
Fixes #2882.
In 3b2e946, I fix the local email tests so that they actually fail if one of the assertions throws an error. You can verify this if you run them against that commit, because you'll see this failure which has been lurking in tree since last month:
```
1) lib/senders/email:
account settings info link is in email template output for newDeviceLoginEmail:
AssertionError: expected false to be truthy
at mailer.mailer.sendMail.emailConfig (test/local/senders/email.js:525:22)
at Nodemailer.sendMail (test/local/senders/email.js:184:7)
at P.all.services.map.service (lib/senders/email.js:338:18)
at Array.map (<anonymous>)
at selectEmailServices.then.services (lib/senders/email.js:282:31)
at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler …
```
> fix(email): add missing query params to link in new device email

- docs/api.md
- lib/error.js
Fixes #2888 
Remove `A` from totpTokenAlreadyExists as well because it seemed to be a little clearer without it.
> fix(error): remove `A` from totpTokenNotFound and totpTokenAlreadyExists errors

- lib/log.js
- test/local/log.js
Fixes #2885.
Stackdriver doesn't like it when properties change their type across log lines, and there is a clash between the type of the `code` property for the `account.signin.confirm.success` and `request.summary` log lines.
This change renames it to `status` on `request.summary`, because that seems like a more appropriate name and the other log message appears to have greater legitimacy to its claim to use the `code` property name (that is literally the name of the corresponding property in the request payload).
However, I also know that `request.summary` is going to be parsed by the fraud detection pipeline, so maybe this is a breaking change for them. If that is the case I can change the other log line instead, no probs. @shane-tomlinson, maybe you know for certain whether that is …
> fix(logs): rename `code` to `status` on request.summary log lines

- lib/routes/sms.js
- test/local/routes/sms.js
Ref: https://sentry.prod.mozaws.net/operations/auth-prod/issues/5170677/?environment=prod
It turns out, sometimes `phoneNumberUtil.parse` throws instead of signalling state via `phoneNumberUtil.isValidNumber`, which I didn't realise when I wrote the code. This just ensures we catch those errors and return the appropriate 400 error instead of a 500.
> fix(sms): catch errors thrown from phoneNumberUtil.parse

- .travis.yml
- lib/crypto/scrypt.js
- npm-shrinkwrap.json
- package.json
Same deal as mozilla/fxa-auth-db-mysq#473, changes `scrypt-hash` to an optional dependency and then falls back to `crypto.scrypt` when it's not available.
Note that currently it's pointing to my unmerged fxa-auth-db-mysql branch, I'll need to re-run shrinkwrap if/when that PR is merged.
> fix(tests): pass tests in node 10

- docs/api.md
- scripts/write-api-docs.js
Saw this mentioned in https://github.com/mozilla/fxa-auth-server/pull/2896#discussion_r253717840.
Fixes the docs script so that it doesn't say refresh tokens are HAWK-authenticated. I also removed a comma in the generated output.
> fix(scripts): sanely handle refreshTokens in the docs script

- fxa-oauth-server/lib/config.js
- fxa-oauth-server/lib/events.js
Folks,
First of all, quite new to all this collaboration bits and bobs. I'm trying to run my own Mozilla Services. For my simple setup I don't see the need to have config.events to be set. When I change the NODE_ENV variable to production it requires me though. 
According to the friendly folks in #fxa it's made deliberately hard to disable the events system to guard against accidentally deploying this into production without it being properly set. It was reasonable to create a configuration flag to disable this requirement which is by default set to true. 
So hereby.
Best regards,
Jurgen Brunink
> Add option to disable requirement of config.events to be set in production

- lib/senders/email.js
- lib/senders/partials/verify.html
- lib/senders/templates/_versions.json
- lib/senders/templates/verify.html
- lib/senders/templates/verify.txt
- test/local/senders/email.js
Show the relier name in the email in the header and in
the main text.
fixes #2859
> feat(email): Update verification email for OAuth reliers.

- lib/routes/devices-and-sessions.js
- test/local/routes/devices-and-sessions.js
Currently, the server just echoes back the request payload on spurious updates.
> fix(devices): return full device response on spurious updates

- docs/api.md
- lib/backendService.js
- lib/error.js
- lib/safe-url.js
- lib/server.js
- test/local/backendService.js
- test/local/error.js
- test/local/safe-url.js
- test/local/server.js
Related to #2884, but a speculative patch rather than a definitive fix for it.
As discussed in the FxA meeting a few weeks ago, sometimes our `500` errors are devoid of any context that would help identify the cause in Sentry. I know we talked about other Sentry options we can set and updating the npm dependency too, but I wondered whether just adding a bit more data to the error object would be a quick win to get us started regardless of those. Hence, this PR.
Of course, setting extra data on the error object means returning it through the API, so I only picked out 2 particular cases where I think nothing sensitive could leak out. I decided not to add an error message or stack trace to `backendServiceFailure` for instance, lest it reveal some inner implementation detail of our production …
> fix(errors): add some more context to our 500 errors

- docs/api.md
- lib/metrics/context.js
- test/local/log.js
- test/local/metrics/context.js
- test/local/metrics/events.js
- test/local/routes/account.js
- test/mocks.js
- test/remote/account_create_tests.js
Related to #2917.
Adds `entrypoint` as an optional property of the metrics context payload. Also adds some validation for `entrypoint` and the UTM params. That duplicates validation in the content server so we probably want to refactor both to `fxa-shared` at some point (I'll open a separate issue for that).
> fix(metrics): reinstate entrypoint to the metrics context schema

- lib/db.js
The database now always returns device information when getting a sessionToken, so we don't need to use a special route for it. I think this code was just left over from our cleanup of the old "sessionWithDevice" route.
> fix(db): Stop using deprecated 'sessionWithDevice' db route.

- bin/key_server.js
It can be really confusing this, some server errors would make the server crash, but not output anything.
> fix(server): make sure to log errors on server start crash

- docs/api.md
- lib/error.js
- lib/redis.js
- test/local/redis.js
- test/remote/redis_tests.js
Fixes #2966.
The 500 errors for `redis.watch.conflict` are relatively infrequent but they're unactionable and get in the way of genuine Sentry errors. In hindsight, I should have made them a 409 from the start.
> chore(api): make redis.watch.conflict a 409 instead of 500 error

- fxa-oauth-server/lib/db/memory.js
- fxa-oauth-server/lib/routes/token.js
- fxa-oauth-server/test/api.js
Continues https://github.com/mozilla/fxa-auth-server-private/pull/90 in the public repo.
Here's my attempt at a broader refactor of the /token route, as described in https://bugzilla.mozilla.org/show_bug.cgi?id=1531648. There are longer functions, but the control flow is much simpler IMHO and therefore easier to follow.
> chore(refactor): Refactor the /token endpoint to improve clarity.

- docs/service_notifications.md
- lib/log.js
- lib/routes/account.js
- lib/routes/emails.js
- lib/routes/utils/signin.js
- test/local/log.js
- test/local/routes/account.js
- test/local/routes/emails.js
- test/local/routes/utils/signin.js
The Mozmeao team would like to create custom onboarding journeys
for different services, but we don't provide sufficient information
for them to do so.
Send along a `service` when emitting the `verified` event.
Send `login` for all services, not just Sync.
fixes #2915
> feat(basket): Updates to `login` and `verified` events for Basket

- bin/profile_server_messaging.js
- lib/db.js
- scripts/must-reset.js
Fixes #2916. The signature didn't cause any bugs, since the DB object is only used for very specific things in the profile_server_messaging and must-reset scripts, but this corrects the invocation.
Also makes the UnblockCode parameter explicitly optional.
I wasn't sure if a test was necessary here. The bad signature doesn't represent any outward bug. `profileUpdates` (which does all the work in this script) is tested elsewhere.
> fix(profile_server_messaging): fix db constructor signature

- npm-shrinkwrap.json
- package.json
Fixes:
```
1.92s$ npm run lint:deps
> fxa-auth-server@1.133.1 lint:deps /home/travis/build/mozilla/fxa-auth-server
> npm audit --json | audit-filter --nsp-config=.nsprc --audit=-
Unfiltered advisories:
https://npmjs.com/advisories/788
```
Blocks https://github.com/mozilla/fxa-auth-server/pull/2969
> fix(deps): fix npm advisory 788

- docs/api.md
- lib/routes/emails.js
As discussed in https://github.com/mozilla/fxa-auth-server/issues/2939#issuecomment-475143272, the query params on `POST /recovery_email/verify_code` are redundant and misleading. Let's remove them to prevent future confusion.
> fix(api): remove redundant query params from /recovery_email/verify_code

- config/index.js
This is just a tiny little improvement I noticed we could make while reviewing #2986. Instead of calling `conf.get('contentServer.url')` inline 12 times inside these template literals, it reads a bit nicer if we assign the result to a variable name instead.
> refactor(config): cache repetitive calls to conf.get

- fxa-oauth-server/docs/api.md
- fxa-oauth-server/lib/db/memory.js
- fxa-oauth-server/lib/db/mysql/index.js
- fxa-oauth-server/lib/error.js
- fxa-oauth-server/lib/grant.js
- fxa-oauth-server/lib/routes/authorization.js
- fxa-oauth-server/lib/routes/key_data.js
- fxa-oauth-server/lib/routes/token.js
- fxa-oauth-server/test/api.js
- fxa-oauth-server/test/grant.js
- fxa-oauth-server/test/routes/authorization.js
- fxa-oauth-server/test/routes/token.js
Fixes #2962. Requires #2946 as it's based off that commit.
Clients could previously use an FxA assertion to grant themselves OAuth access tokens via the /authorization endpoint in a style modelled after OAuth's "implicit grant" flow. But it's not really
the implicit grant flow, the way we use it in practice much more closely resembles the "resource owner password credentials" flow. In particular, existing clients use it to directly create tokens for their own use, rather than to authorize tokens for another client.
This commit makes that functionality available on the /token endpoint instead, using `grant_type=fxa-assertion`. This is better aligned with the way that the rest of OAuth works, closely mirroring
the `grant_type=password` flow and keeping a clear distinction between obtaining …
> feat(oauth): Use an assertion to directly grant tokens at /token.

- docs/api.md
- lib/error.js
- lib/oauthdb/create-authorization-code.js
- lib/oauthdb/index.js
- lib/oauthdb/utils.js
- lib/routes/oauth.js
- lib/routes/validators.js
- test/client/api.js
- test/client/index.js
- test/local/oauthdb/create-authorization-code.js
- test/local/routes/oauth.js
- test/mocks.js
- test/remote/oauth_tests.js
Fixes #2933.
Inspired by conversations with @shane-tomlinson and @vladikoff today, I wanted to see what it would look like to move the [OAuth /authorization endpoint](https://github.com/mozilla/fxa-auth-server/blob/master/fxa-oauth-server/docs/api.md#post-v1authorization) over to the auth-server, letting us do OAuth authorization grants directly from a sessionToken rather than having to indirect through a BrowserID assertion.
This is a sketch of what the code would look like.  It obviously needs tests and docs etc before we could consider using it.  But I think it came together pretty OK atop the existing "backend service" abstraction.  @shane-tomlinson @vladikoff what do you think, is this worth pursuing further?
> feat(oauth): Add /oauth/authorization route, authenticated with a sessionToken

- docs/api.md
- fxa-oauth-server/config/dev.json
- lib/error.js
- lib/oauthdb/grant-tokens-from-authorization-code.js
- lib/oauthdb/grant-tokens-from-credentials.js
- lib/oauthdb/grant-tokens-from-refresh-token.js
- lib/oauthdb/index.js
- lib/oauthdb/utils.js
- lib/routes/oauth.js
- lib/routes/validators.js
- test/client/api.js
- test/client/index.js
- test/local/oauthdb/grant-tokens-from-authorization-code.js
- test/local/oauthdb/grant-tokens-from-refresh-token.js
- test/local/oauthdb/grant-tokens-from-session-token.js
- test/local/routes/oauth.js
- test/mocks.js
- test/remote/oauth_tests.js
Fixes #2954; Requires #2969.
Here's my draft of how we'd use the new `fxa-assertion` grant type from #2969 to implenent a `/oauth/token` endpoint on the auth-server.  Needs tests etc, but hopefully gives you a bit of the idea.  You can imagine us proceeding to add additional auth-server things to this endpoint, like sending emails and creating/updating device records.
/cc @vladikoff
> feat(oauth): Add /oauth/token route, optionally authed via sessionToken

- lib/devices.js
- lib/oauthdb/check-access-token.js
- lib/oauthdb/index.js
- lib/routes/index.js
- lib/routes/oauth.js
- lib/routes/utils/oauth.js
- test/local/oauthdb.js
- test/local/routes/utils/oauth.js
- test/mocks.js
- test/remote/oauth_tests.js
Fixes https://github.com/mozilla/fxa-auth-server/issues/2880
Fixes https://github.com/mozilla/fxa-auth-server/issues/2955
> Notify push and email on code exchanges

- fxa-oauth-server/config/dev.json
- fxa-oauth-server/lib/config.js
- fxa-oauth-server/lib/grant.js
- fxa-oauth-server/lib/metrics/amplitude.js
- fxa-oauth-server/lib/routes/verify.js
- fxa-oauth-server/test/grant.js
- fxa-oauth-server/test/metrics/amplitude.js
- fxa-oauth-server/test/routes/verify.js
* `fxa_activity - access_token_created` whenever an access token is created.
* `fxa_activity - access_token_checked` whenever an access token is checked.
issue #2957
After adding config for 123done, here's what a checked event looks like:
```
amplitudeEvent {"op":"amplitudeEvent","event_type":"fxa_activity - access_token_checked","time":1553867227015,"user_id":"572a021237bf486fbf4951c07008f3f4","app_version":"133","event_properties":{"service":"123done","oauth_client_id":"dcdb5ae7add825d2"},"user_properties":{"$append":{"fxa_services_used":"123done"}}}
```
> feat(metrics): amplitude events from the OAuth server for MAU
