mozilla/fxa-auth-server

routes/account.js
routes/sign.js

Possible extra logging in service of https://bugzilla.mozilla.org/show_bug.cgi?id=1120804

Log debugging info when we fail to set a locale for an account.

---

test/load/Makefile
test/load/loadtests.py

This moves a lot of low-level stuff out into the PyFxA client library, which cleans up the file a *lot*.  @seanmonstar r?

Use shiny new PyFxA library for the python loadtests.

---

bin/basket.js

This is in service of #839.  Not sure how to actually test it though, @dannycoates maybe you can advise?

Add more fine-grained logging and retry policy on basket API errors.

---

bin/basket.js
server/server.js

See https://bugzilla.mozilla.org/show_bug.cgi?id=1102652#c15

Tell basket that locale="en-US" when the user doesn't provide one explicitly

---

bin/basket.js

This seems sensible in general even for production, and will fix #868.  @jrgm thoughts?  I'm not too worried about adding a little hack in here since we plan to majorly refactor the way these notifications are delivered.

Don't forward restmail.net email addresses to basket API.

---

npm-shrinkwrap.json

chore(shrinkwrap): update shrinkwrap to pick up latest fxa-content-server-l10n translations

---

bin/notifier.js
config/config.js
config/dev.json

Fixes #888 
Not the prettiest, but this way doesn't require an config schema changes.

allow the sns notifier to be disabled in config

---

npm-shrinkwrap.json
package.json

Okay, cleaned this and dependent shrinkwraps up now. r? @chilts @dannycoates

update fxa-auth-mailer/fxa-auth-db-mem in package.json and update shrinkwrap. 

---

.travis.yml
CHANGELOG
npm-shrinkwrap.json
package.json

I biffed and branched train-34 before the PR https://github.com/mozilla/fxa-auth-server/pull/904 was merged to master. I need these two commits on train-34 to have the correct l10n for email in this train. Mea culpa.

[train-34] some shrinkwrap and version cleanup from trunk that was intended to be part of train-34 too

---

.travis.yml

Just going to land this, since without it, current master is failing.

fix(travis): set --force flag on validate-shrinkwrap

---

npm-shrinkwrap.json
package.json

updated scrypt-hash

---

scripts/e2e-email/index.js
scripts/e2e-email/localeQuirks.js

I almost hate filing this PR (instead of just pushing to master), since I'm the sole consumer of this script. But I filed it anyways. Anyone want to bit the green button?

chore(test): fr,fy now translate "re-verify your account" subject line; small naming fix

---

db/httpdb.js
docs/api.md
routes/account.js
test/client/api.js
test/client/index.js
test/local/db_tests.js
test/remote/account_destroy_tests.js
test/remote/session_destroy_tests.js

unceremoniously removed /account/devices endpoint

---

scripts/e2e-email/index.js
scripts/e2e-email/p-request.js

Just two places that need to find promise.js in a different location now. r? @dannycoates or @rfk

chore(test): adjust library paths for GH-926

---

bin/basket.js
bin/email_bouncer.js
lib/log.js

@whd requested these naming changes to work in conjunction with [these heka changes](https://github.com/mozilla-services/puppet-config/pull/1314)

fix(logging): configuration changes per @whd

---

lib/crypto/password.js
lib/crypto/pbkdf2.js
lib/customs.js
lib/db.js
lib/mailer.js
lib/preverifier.js
lib/promise.js
lib/routes/account.js
lib/tokens/key_fetch_token.js
lib/tokens/token.js
npm-shrinkwrap.json
package.json
scripts/e2e-email/index.js
test/client/index.js
test/local/password_check_test.js
test/mailbox.js

I think bluebird won. We're using it in other newer repos too.

switch promises to bluebird from p-promise

---

docs/api.md
lib/log.js
lib/routes/account.js
test/client/api.js
test/remote/account_login_tests.js

@rfk - r?
This is the first step to determine the volume of notification emails that will be sent.
issue #875

feat(server): Log the `service` and `reason` parameters for `/account/login`.

---

lib/routes/account.js

Fixes : https://github.com/mozilla/fxa-auth-server/issues/800

Always check email case on login

---

lib/db.js
lib/routes/utils/password_check.js
test/local/password_check_test.js

Part of https://github.com/mozilla/fxa-auth-db-server/issues/88

Use checkPassword API

---

npm-shrinkwrap.json

```
-          "resolved": "git://github.com/mozilla/fxa-content-server-l10n.git#d0ac10ae189373497d58df2a7c8ffcb8c07972f8"
+          "resolved": "git://github.com/mozilla/fxa-content-server-l10n.git#0b14ddf163b06bd82ee53400ac0201c81c250875"
```

chore(shrinkwrap): update shrinkwrap to pickup latest fxa-content-server-l10n

---

lib/log.js
lib/routes/account.js
lib/routes/sign.js

Events added are:
* account.created
* account.verified
* account.login
* account.signed
* account.deleted

feat(log): Add logging of various account events

---

scripts/e2e-email/localeQuirks.js
scripts/e2e-email/p-request.js

A couple of small fixes to e2e-email check

---

config/index.js
lib/mailer.js
lib/routes/account.js
lib/routes/password.js
npm-shrinkwrap.json
test/remote/account_login_tests.js
test/remote/password_change_tests.js
test/remote/password_forgot_tests.js

Not quite ready yet, opening the PR to get initial feedback.
Link to:
https://github.com/mozilla/fxa-auth-mailer/pull/26
https://github.com/mozilla/fxa-js-client/pull/146
https://github.com/mozilla/fxa-content-server/pull/2129
https://github.com/mozilla/fxa-auth-server/pull/941
https://github.com/mozilla/fxa-content-server/pull/2561
https://github.com/mozilla/fxa-content-server/pull/2562

Issue 875 notification emails

---

npm-shrinkwrap.json

chore(shrinkwrap): update shrinkwrap, mostly for auth-{db-server,db-mem,mailer} and content-server-l10n

---

test/mailbox.js

Hi @dannycoates - r?
I have a rewrite of the test I wrote that checks the translations in the emails sent (scripts/e2e-email) and also, in general, the mechanics of generating and delivering those emails. I'm extending it to check the notification emails (new device, password changed, password reset) using the `test/client` code. To do that, I need this change to allow a caller to be able to listen for the email messages fetched by `test/mailbox`. So here's that change. Doesn't affect any existing callers of `test/mailbox`, just optional.

fix(tests): add an EventEmitter to test/mailbox

---

config/index.js
npm-shrinkwrap.json
package.json

Ref: https://github.com/mozilla/fxa-oauth-server/issues/296

refactor(config): Use human-readable duration values in config

---

bin/basket.js
bin/email_bouncer.js
bin/key_server.js
scripts/test-remote-quick.js
test/local/account_preverified_token_tests.js
test/local/base_path_tests.js
test/local/concurrent_tests.js
test/local/db_tests.js
test/local/email_validity_tests.js
test/local/mailer_locales_tests.js
test/local/resend_blackout_tests.js
test/local/token_expiry_tests.js
test/local/verifier_upgrade_tests.js
test/mail_helper.js
test/remote/account_create_tests.js
test/remote/account_destroy_tests.js
test/remote/account_locale_tests.js
test/remote/account_login_tests.js
test/remote/account_status_tests.js
test/remote/account_unlock_tests.js
test/remote/certificate_sign_tests.js
test/remote/flow_tests.js
test/remote/misc_tests.js
test/remote/password_change_tests.js
test/remote/password_forgot_tests.js
test/remote/recovery_email_verify_tests.js
test/remote/session_destroy_tests.js

fix(config): update convict .root() to .getProperties() calls

---

config/supportedLanguages.js

Companion to https://github.com/mozilla/fxa-content-server/pull/2975

feat(l10n): add en-GB as a supported locale.

---

test/remote/account_destroy_tests.js
test/remote/account_login_tests.js
test/remote/account_unlock_tests.js
test/remote/password_change_tests.js

Fixes #896, adding test coverage for the error paths of lockout code.

chore(tests): test locked account behaviour

---

scripts/check-i18n.js

A simple improvement to show what differs between supported locales when a difference is detected. 
r? - @philbooth

chore(tests): print locale differences on failure

---

README.md

chore(docs): update the configuration documentation

---

.env.dev
config/index.js
lib/log.js
lib/metrics/statsd.js
lib/routes/account.js
npm-shrinkwrap.json
package.json
test/local/statsd_tests.js

feat(metrics): add DataDog to activity events, email verified activity events

---

config/supportedLanguages.js

Companion to https://github.com/mozilla/fxa-content-server/pull/3001

feat(l10n): add fa as a supported locale.

---

test/load/Makefile

@jrgm I saw you mention these changes in email, figured there's no hard in getting them onto master.  r?

fix(tests): update loadtest build script to work with latest PyFxA.

---

lib/routes/defaults.js

I realized I should use an explicit path to git. Also removes and unneeded iffe, and formats the json output to use spaces and a newline to match fxa-oauth and fxa-profile.

fix(version): use explicit path with git-config

---

lib/routes/account.js

@rfk @dannycoates r?
Fixes https://github.com/mozilla/fxa-auth-server/issues/1045

fix(metrics): properly report account.uid for account.created

---

.travis.yml
README.md
package.json
scripts/start-local-mysql.sh
scripts/start-local-test-mysql.sh
test/local/verifier_upgrade_tests.js

fix(tests): run mysql tests on travis

---

scripts/e2e-email/localeQuirks.js
scripts/e2e-email/validate-email.js
test/client/api.js
test/client/index.js

fix(tests): changes for "Firefox Account Verified" in train-46

---

bin/key_server.js
config/index.js
lib/routes/idp.js
lib/routes/index.js
scripts/gen_keys.js
test/local/sign_key_tests.js
test/remote/misc_tests.js

Along with this change I think we should start setting the `kid` field in our key json files.

multiple public keys

---

scripts/e2e-email/index.js

Minor fix if anyone want to review

fix(e2e-email): exit 1 on error

---

lib/routes/account.js

This is the change that I described in https://github.com/mozilla/fxa-auth-server/pull/1102#issuecomment-153658657.
The background is that I find the long promise chains on some of the route handlers very difficult to follow. For instance, I'll be scrolling down one of them, reading it, and suddenly I'll be unsure whether I'm still in the same handler or if I've scrolled into the next one. Cue scrolling up to check and then scrolling back down to try and find where I was before I scrolled up. Sometimes this happens more than once in a row.
Also the constant in-then-out indentation just makes it hard to follow the flow of logic through the promise chain, figuring out where a given `return` or `throw` ends up is trickier than it needs to be. Which level of indentation is this `then` at? …

fix(server): refactor account promise chains to named functions

---

config/index.js
npm-shrinkwrap.json
package.json

feat(oauth): pass email=false when verifying oauth tokens

---

test/remote/account_create_tests.js

Translated now, so restoring original tests #995

fix(tests): unskip tests now that they are translated (GH-995)

---

lib/bounces.js

The measurement part of https://github.com/mozilla/fxa-content-server/issues/3295

feat(metrics): send email-bounce-related metrics to statsd.

---

docs/api.md

docs(profile): document the /account/profile endpoint

---

lib/routes/account.js

feat(activity): log successful account resets

---

docs/overview.md

chore(docs): add activity events log

---

lib/push.js
lib/routes/account.js
test/local/push_tests.js

feat(push): add account verification push updates

---

npm-shrinkwrap.json
package.json

chore(deps): update changelog template to 1.1.0

---

lib/tokens/session_token.js

Export constants from session_token.js for use in the tests.

---

lib/server.js
lib/tokens/token.js
npm-shrinkwrap.json
package.json

The latest version of Hawk works with our current Hapi, but has a few API changes.  @dannycoates r?

fix(hawk): Update to latest hapi-auth-hawk

---

test/remote/account_create_tests.js

Fixes #1177 (although right now I'm just pushing it for travis to take a look at)

fix(tests): Update tests for new fxa-auth-mailer behaviour

---

npm-shrinkwrap.json
scripts/e2e-email/localeQuirks.js
scripts/e2e-email/validate-email.js

Just some cleanups to wrap-up train-56
- update to mozilla/fxa-auth-mailer.git#01f8ee75fdd381ee26820545aba99ad95ce87c0f
- e2e-email: bg now has another subject line translated
- e2e-email: fix test expectation for utm params on query string in email
r? - @rfk

Train 56 pre2

---

lib/metrics/statsd.js
lib/userAgent.js
npm-shrinkwrap.json
package.json
test/local/user_agent_tests.js

fix(deps): Migrate to more up-to-date user-agent parsing lib.

---

lib/db.js
lib/routes/sign.js
lib/server.js
lib/signer.js
lib/tokens/session_token.js
npm-shrinkwrap.json
test/local/session_token_tests.js

An alternate implementation of #1166 (see https://github.com/mozilla/fxa-auth-server/pull/1166#discussion_r51185023)

fxa-deviceId in signed cert (alt)

---

.travis.yml
lib/push.js
npm-shrinkwrap.json
package.json
test/e2e/README.txt
test/e2e/push_tests.js
test/local/push_tests.js
test/push_helper.js

fix(push): add TTL to push requests

---

config/index.js

Fixes https://github.com/mozilla/fxa-auth-mailer/issues/122

fix(config): adjust localized post-verification links

---

npm-shrinkwrap.json
scripts/e2e-email/validate-email.js

- update l10n version
- change expected value of x-link header

Train 57 fixups

---

lib/server.js

revert(metrics): disable logging hask skew to datadog

---

lib/routes/account.js
test/local/account_routes.js

feat(metrics): track push email status checks

---

config/index.js
docs/api.md
lib/crypto/butil.js
lib/customs.js
lib/error.js
lib/mailer.js
lib/routes/account.js
lib/routes/password.js
lib/routes/utils/password_check.js
lib/server.js
npm-shrinkwrap.json
package.json
scripts/bulk-mailer.js
scripts/bulk-mailer/nodemailer-mock.js
scripts/must-reset.js
scripts/reset-send-all-batches.sh
scripts/reset-send-batch.sh
scripts/reset-send-create-batches.js
test/remote/account_login_tests.js
test/remote/account_unlock_tests.js
test/remote/password_forgot_tests.js

This PR merges commits in a private fork of auth-server. It has also been updated to point to master version of auth-mailer.
Features that were added
* fix(customs): Check more password-related actions with customs-server.
* feat(customs): include errno in customs flags with merge
* config for location of the client ip address
* chore(customs): use named error constant for UNEXPECTED_ERROR
* fix(email): reinstate new sync device emails
* feat(reset): Ability to put a users account in a "must reset" state, per dannycoates (PATCH)
* feat(scripts): Add a bulk mailer
@rfk @shane-tomlinson @philbooth Mind a quick review to make sure I didn't miss anything Thanks!

Auth Server merge private fork

---

lib/push.js
lib/routes/account.js
lib/routes/index.js
lib/routes/password.js
test/local/account_routes.js
test/local/password_routes.js
test/local/push_tests.js
test/mocks.js
test/routes_helpers.js

This is the server-side part of https://bugzilla.mozilla.org/show_bug.cgi?id=1262272.
What's the best way to test this, @vladikoff? I see you have an end-to-end test; does it make sense to use that here, or add a fake `pushCallback`?

feat(push): Notify devices when the password is changed or reset

---

lib/log.js

feat(log): includes uid in summary for account create and login

---

lib/routes/account.js

@jrgm what do you think of something like this?

fix(devices): Avoid spurious writes to device record if nothing has changed

---

.travis.yml
docs/api.md
docs/endpoint_data.md
docs/schema.md
lib/db.js
lib/push.js
lib/routes/account.js
lib/routes/validators.js
lib/tokens/session_token.js
npm-shrinkwrap.json
package.json
scripts/start-travis-auth-db-mysql.sh
test/e2e/push_tests.js
test/local/db_tests.js
test/local/push_db_tests.js
test/local/push_tests.js
test/remote/device_tests.js
test/remote/password_forgot_tests.js

See #1229 for past discussion, this PR allows us to land the data-payload related code without landing the new "notify other devices of new device" feature which is still WIP.

feat(push): Prepare codebase for data payloads

---

lib/server.js

Fixes https://github.com/mozilla/fxa-customs-server/issues/113; @vladikoff could you please try this out locally and see if it fixes things for you?

fix(clientAddress): Cope better with X-Forwarded-For having fewer items than expected

---

lib/push.js
test/e2e/push_tests.js
test/local/push_db_tests.js
test/local/push_tests.js

fix(push): adjust metrics increment logs

---

config/supportedLanguages.js

100% complete https://pontoon.mozilla.org/ar/firefox-accounts/ 
@jrgm @vbudhram r?

feat(locale): add Arabic locale support

---

config/supportedLanguages.js

Related https://github.com/mozilla/fxa-content-server/pull/3738

feat(locale): add Finnish locale

---

lib/routes/account.js
lib/routes/password.js

This is an intermediate PR to help with the deployment of https://github.com/mozilla/fxa-auth-server/pull/1232. It adds the params needed for the updated endpoints as optional.
@jbuck, this what you had in mind?

 feat(signin): Added updated params for sign-in confirmation

---

docs/api.md
lib/routes/account.js
lib/routes/password.js
test/remote/account_reset_tests.js

@vbudhram for your consideration 😁

fix(signin): @rfk nits on #1264

---

bin/key_server.js
lib/log.js
lib/routes/account.js
test/local/account_routes.js
test/local/metrics_context_tests.js

This will allow us to tunnel `utm_*` metrics parameters through to basket.  Connects to https://github.com/mozilla/fxa/issues/148

feat(events): Include metrics context in SQS events

---

docs/pushpayloads.schema.json
lib/push.js
lib/routes/account.js
npm-shrinkwrap.json
package.json
test/local/account_routes.js
test/local/push_tests.js

See #1229 for context and older discussion.

feat(devices): notify other devices of a new device

---

lib/routes/account.js
test/local/account_routes.js

feat(device): emit create and delete events to SNS

---

README.md
grunttasks/eslint.js
npm-shrinkwrap.json
package.json

We did this in https://github.com/mozilla/fxa-content-server/issues/2592 and it worked out pretty well!

chore(git): Run a quick linting task on pre-push

---

docs/pushpayloads.schema.json
lib/push.js
lib/routes/account.js
test/e2e/push_tests.js
test/local/account_routes.js
test/local/push_tests.js

feat(push): notify a device when it has been disconnected

---

lib/routes/account.js

fix(push): add verification push event to push log

---

config/index.js
lib/log.js
lib/metrics/context.js
lib/routes/account.js
lib/routes/index.js
lib/routes/sign.js
npm-shrinkwrap.json
package.json
test/local/account_routes.js
test/local/log_tests.js
test/local/metrics_context_tests.js
test/mocks.js

You might like to think of them as "meta-metrics", and they'll tell us useful things about whether the front-end metrics are working as expected.

feat(metrics): Log metrics about whether metrics are transmitted correctly

---

lib/routes/account.js
test/client/api.js
test/remote/account_create_tests.js

Connects to #1249; @seanmonstar r?

fix(verify): Only send post-verify email when service=sync

---

lib/routes/account.js
npm-shrinkwrap.json
package.json

@jrgm r?
(This includes a merge commit for the v1.63.0 tag which somehow didn't make it into master earlier)

Accept and ignore contentToken param

---

.env.dev
config/index.js
lib/db.js
lib/pool.js
lib/routes/account.js
lib/verification-reminders.js
npm-shrinkwrap.json
test/local/pool_tests.js
test/local/verification_reminder_db_tests.js
test/local/verification_reminder_tests.js

feat(email): verification reminders

---

config/index.js
docs/api.md
lib/db.js
lib/routes/account.js
test/remote/account_signin_verification_enable_tests.js
test/remote/account_signin_verification_tests.js
test/remote/password_change_tests.js
test/remote/recovery_email_resend_code_tests.js

Just working one some final tweaks to signin-confirmation....

Final nits on signin confirmation PR

---

npm-shrinkwrap.json
package.json

chore(deps): Update to latest version of mozlog

---

lib/push.js

We don't have an efficient way to look up a device record given just its device id, you need the (uid, deviceid) pair.  This ensures that the uid is logged alongside the deviceid in error reports.

fix(logs): Log the uid when reporting push errors.

---

.nsprc
.travis.yml

chore(nsp): update .nsprc and travis.yml

---

lib/push.js
lib/routes/account.js
test/local/account_routes.js
test/local/push_tests.js

Makes handling of push notifications more asynchronous, to hopefully avoid the event-loop-blocking behaviour that caused https://bugzilla.mozilla.org/show_bug.cgi?id=1280716.  Also logs an error when an accounts gets more than 200 sessions or more than 200 devices, to help guide further work on this issue.
Fixes #1294; @philbooth r?

Improved handling and monitoring of accounts with many active devices

---

lib/routes/account.js

fix(account): fix payload typo in device update

---

lib/routes/utils/password_check.js
test/local/password_check_test.js

Otherwise we report the default errno of `999`, which isn't very helpful.

fix(customs): Report errno to customs when password check fails.

---

docs/overview.md

chore(docs): add more docs to activity events.

---

docs/overview.md

feat(docs): document the new activity events

---

config/index.js
lib/metrics/context.js
test/local/metrics_context_tests.js

feat(metrics): Drop invalid flowids so they dont confuse our metrics.

---

lib/customs.js
lib/routes/account.js
lib/routes/password.js
test/local/customs.js

@seanmonstar gave me an r+ for this in private discussion, I'll carry it forward if travis goes green.

feat(customs): Send more request metadata to customs-server for checking

---

scripts/tap-coverage.js

fix(tests): fix test runner to exit with proper exit code

---

config/index.js
docs/api.md
lib/push.js
lib/routes/account.js
test/e2e/push_tests.js
test/local/account_routes.js
test/local/push_tests.js
test/mocks.js
test/remote/push_db_tests.js

Devices push proxy (account/devices/notify)

---

lib/routes/utils/request_helper.js
test/local/account_routes.js

fixes #1374
mozilla/fxa-content-server#3988
@vbudhram, @philbooth, @rfk - r?
cc @jrgm - this will be needed to fix mozilla/fxa-content-server#3988

fix(signin): No signin confirmation for email regexp match if keys not requested

---

lib/routes/utils/request_helper.js

chore(signin): Add commentary about temporary workarounds in sign-in confirmation config

---

.nsprc
config/index.js
lib/geodb.js
lib/mailer.js
lib/routes/account.js
npm-shrinkwrap.json
package.json
test/local/account_routes.js
test/local/geodb.js
test/mocks.js

Adds geolocation data to emails
@vbudhram 
@vladikoff 
@shane-tomlinson
(@rfk adds: Connects to #1274; this makes waffle link the PR with the issue card)

feat(geolocation): add geolocation data to emails

---

scripts/e2e-email/index.js
scripts/e2e-email/validate-email.js

r? - @rfk 
Although, I do get a flaky failure in stage that I'll need to look into more tomorrow, but this change doesn't affect any server code, so this is the first commit.

fix(e2e-email): fix e2e-email test

---

lib/routes/account.js
test/local/account_routes.js

fix(devices): serialize push payload in /devices/notify route

---

docs/pushpayloads.schema.json
lib/push.js
lib/routes/account.js
lib/routes/password.js
test/local/account_routes.js
test/local/password_routes.js
test/local/push_tests.js
test/mocks.js

feat(push): Send proper push messages for password change/reset

---

lib/push.js
lib/routes/account.js
lib/routes/password.js
test/local/push_tests.js

fix(device): remember devices to push-notify before resetting account on password change/reset

---

lib/routes/password.js
test/mocks.js
test/remote/password_change_tests.js

This reverts commit bb5f28b7759d00c3727bca77399f05409d81c194.
------
My mistake, I checked the related issue and it sounded like this was good to go. Seems we need to consider this in a few weeks.

Revert "fix(password): Remove raw token support"

---

config/index.js
npm-shrinkwrap.json

This PR adds the new configs that were added in [auth-mailer](https://github.com/mozilla/fxa-auth-mailer/blob/master/config.js#L192) to auth-server. Also updated shrinkwrap to use new mailer.

fix(config): Add new url configs for mailer

---

lib/customs.js
lib/routes/account.js
test/local/account_routes.js
test/local/customs.js

feat(server): Rate limit account/devices/notify with the new UIDRecord

---

lib/bounces.js
test/local/bounce_tests.js

fix(ses): add status and diagnosticCode for bounce

---

lib/db.js
lib/routes/account.js
lib/routes/password.js
lib/routes/utils/request_helper.js
lib/tokens/session_token.js
package.json
test/local/account_routes.js
test/remote/account_signin_verification_tests.js

(For now, just to let travis try and run the test)
Connects to #1374

Ensure keyless sessions are created unverified by default

---

lib/verification-reminders.js

fix(reminders): fix issue with reminder rate

---

lib/customs.js
lib/log.js
test/local/customs.js
test/local/log_tests.js
test/mocks.js

feat(metrics): add flowEvent support to all activityEvents and customs

---

docs/overview.md

I forgot all about these when reviewing #1409, sorry.
@vbudhram, r?

fix(docs): document the new flow events

---

bin/key_server.js
lib/geodb.js

Commit and comments say it all.

fix(geodb): load at startup and log configuration used

---

bin/key_server.js
lib/geodb.js

backport to train-67 branch. 
r? - @vladikoff or anyone?

fix(geodb): load at startup and log configuration used (from #1414)

---

lib/routes/account.js
test/local/account_routes.js

Fixes #1415.
This eliminates the spurious logging of successful sign-in confirmation in the email verification case.
@vbudhram, should be exactly as we discussed in Vidyo, r?

fix(logging): account.verified & account.confirmed are mutually exclusive

---

npm-shrinkwrap.json
package.json

chore(deps): update dev deps, fix husky issues

---

npm-shrinkwrap.json
package.json

fix(deps): use poolee@1.0.1 (train-68)

---

test/local/geodb.js
test/mocks.js

fix(geodb): 8.8.8.8 in latest data not in Mountain View; point to moz MTV

---

lib/userAgent.js
test/local/user_agent_tests.js
test/remote/db_tests.js

feat(devices): add tablet detection

---

docs/api.md
lib/customs.js
lib/error.js
test/local/customs.js
test/local/error_tests.js

feat(customs): return localized retry after data

---

lib/tokens/token.js

fix(process): remove process.domain in token.js

---

test/e2e/push_tests.js
test/push_helper.js

Fixes #1368.  I had the tests running in a loop for about half an hour with no failures.
The trick here is to ensure the "hello" and "register" websocket messages are properly sequenced into a handshake.  Thanks @kitcambridge for helping sanity-check this!
@vladikoff r?

fix(push): Fix and re-enable the end-to-end push tests.

---

lib/db.js
lib/routes/account.js
npm-shrinkwrap.json
test/remote/db_tests.js

* Unbuffer the POST request before sending.
* Convert the call to GET /securityEvents with query params to GET /securityEvents/:id/ip/:ipAddr to be more RESTful and to work with the pool.js GET api
fixes #1464

fix(security): Fix the security event calls to the DB.

---

lib/geodb.js
npm-shrinkwrap.json
test/local/geodb.js

For https://github.com/mozilla/fxa-auth-mailer/pull/215
@vbudhram r?

feat(geo): add state code to location response

---

lib/routes/account.js
test/local/account_routes.js

fix(push): notify devices after successful sign-in confirmation

---

lib/log.js
lib/routes/account.js
test/local/account_routes.js
test/local/log_tests.js

fix(logging): device.created is not a flow event

---

lib/routes/account.js
lib/routes/password.js
test/local/account_routes.js
test/local/password_routes.js
test/mocks.js

This adds basic rate-limiting to attempts to very email codes.  It will need a corresponding customs-server PR to actually support the new actions.  @mozilla/fxa-devs r?

feat(customs): Rate-limit verification of email codes.

---

lib/push.js
test/local/push_tests.js

fix(push): Add metrics events for reason=accountConfirm

---

bin/key_server.js
config/index.js
docs/api.md
lib/crypto/base36.js
lib/customs.js
lib/db.js
lib/error.js
lib/features.js
lib/log.js
lib/mailer.js
lib/routes/account.js
lib/routes/validators.js
npm-shrinkwrap.json
test/local/account_routes.js
test/local/features_tests.js
test/mail_helper.js
test/mocks.js

Signin Unblock

---

config/index.js
lib/server.js
npm-shrinkwrap.json
package.json
test/remote/hpkp_tests.js
test/remote/misc_tests.js

Adds support for hpkp headers. Disabled by default and in report only mode when enabled.
Ref: https://github.com/mozilla/fxa-bugzilla-mirror/issues/179

feat(hpkp): Add hpkp support

---

lib/routes/account.js
lib/routes/utils/request_helper.js
test/local/account_routes.js
test/local/request_helper_tests.js

refactor(email): Remove `sendEmailIfUnverified`

---

config/index.js

feat(metrics): set metricsContext expiry to 2 hours

---

lib/routes/account.js
test/local/account_routes.js

- `email.verification.sent`
- `email.confirmation.sent`
- `email.verify_code.clicked`
- `email.verification.resent`
- `email.confirmation.resent`
To support the "resent" events, I added `metricsContext` to the payload of `/recovery_email/resend_code`, and so it would need the content-server to also send its context. If this seems desirable, I can file an issue in the content-server to do so.
Closes #1511
r? @philbooth

feat(metrics): add flow events for email sent and clicked

---

.eslintrc
lib/crypto/base32.js
lib/crypto/random.js
lib/db.js
lib/routes/account.js
lib/routes/index.js
lib/routes/password.js
lib/routes/util.js
lib/tokens/account_reset_token.js
lib/tokens/index.js
lib/tokens/password_forgot_token.js
lib/tokens/token.js
package.json
scripts/.eslintrc
test/.eslintrc
test/local/account_routes.js
test/local/base32_tests.js
test/local/forgot_password_token_tests.js

It's 2 different commits because they're logically 2 different things. The first makes all the calls async, and the second adds a lint to error if any calls are synchronous.
Closes #1474

asyncify all crypto.randomBytes

---

lib/db.js
test/remote/db_tests.js

db.createUnblockCode called UnblockCode synchronously, but it's now
asynchronous.
fixes #1531
@philbooth since you are here, or @seanmonstar if @philbooth doesn't have time!

fix(unblock): Fix db.createUnblockCode - code generation is async.

---

bin/key_server.js
lib/routes/account.js
test/local/account_routes.js

fix(push): do not throw if push fails on the notify endpoint

---

lib/verification-reminders.js

@vbudhram r?
`var rand = Math.floor(Math.random() * (100 + 1))` can return 0 and pass the check.

fix(reminders): fix disabled state

---

lib/metrics/context.js
test/local/metrics_context_tests.js

Fixes #1540.
This changes adds regular expression for metrics context validation, mirroring the ones I'm adding to the content server in mozilla/fxa-content-server#4384. If anything violates a pattern we remove the metrics context data, which will prevent flow events from being emitted for those requests. This should reduce the corruption of flow event data that we see in redshift.

fix(logging): drop invalid metrics context data

---

lib/routes/account.js

This will help us to see how much impact #1504 might have. We can count how often this info log appears.

feat(unblock): log when an unverfied user successfully unblocked

---

lib/routes/account.js
test/local/account_routes.js

fix(unblock): rethrow customs server error when account is unknown

---

package.json
test/remote/db_tests.js

WIP: test fixes for upcoming change to db-mysql behaviour

---

docs/metrics-events.md

fix(docs): document recent flow event changes

---

config/index.js
lib/features.js
test/local/features_tests.js

Fixes #1586; @seanmonstar r?
The deltra from v1.75.1 to current master is very small, and since we haven't deployed train-75 yet, I propose we just merge this to master and cut a v1.75.2 from there.

Remove unblock context check

---

docs/overview.md
lib/metrics/context.js
test/client/api.js
test/local/account_routes.js
test/local/ip_profiling.js
test/local/metrics_context_tests.js
test/remote/account_create_tests.js

Fixes #1566.
I need to fix the bustage first, so don't review this yet. Just opening this for safe-keeping.

fix(server): remove redundant metrics context fields

---

lib/pool.js
test/local/pool_tests.js

fix(pool): Reject with an Error instance for HTTP errors.

---

docs/api.md

fix(docs): add unblock code API docs

---

config/index.js

fix(emails): remove /v1/ api prefix

---

config/index.js
lib/routes/account.js
test/local/account_routes.js
test/local/ip_profiling.js

Set default config to allow 3 days.
Closes #1614

feat(ip-profiling): make IP Profiling allowed recency use config

---

npm-shrinkwrap.json

A refresh of shrinkwrap, particularly to pick up current of auth-mailer.

chore(mailer): update fxa-auth-mailer (and other shrinkwrap)

---

lib/bounces.js
test/local/bounce_tests.js

This PR enables logging of the userAgent and complaint type of bounces.
Fixes #1561

fix(logging): Log bounced complaint

---

lib/routes/account.js

refactor(email): Don't flag logins with incorrect email case

---

circle.yml

I'd like to merge this in to `master` so that I can monitor how builds for all branches get on with the cross-repo tests. I've only added myself to the test org for now, so it won't spam anyone else with spurious build errors.
I'm interested in seeing:
1. Whether the builds are stable.
2. If it does a good job of catching problems ahead of time in auth server PRs.
If those two boxes get ticked, we can continue the discussion about a paid Circle account and bringing this into the mozilla org.
@vladikoff, you're probably best-placed to give this an r?

feat(ci): add config for cross-repo testing

---

lib/devices.js
lib/routes/sign.js
test/local/lib/devices.js
test/local/routes/sign.js

Partially fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1332987; @philbooth r?

fix(push): Try to always send a deviceName in the 'device connected' push message

---

docs/metrics-events.md

Whoops, this should have made it into #1630.

feat(docs): document the fix for duplicate flow events

---

config/index.js

fix(style): adjust config code style issue

---

config/index.js
lib/features.js
lib/routes/account.js
test/local/ip_profiling.js
test/local/lib/features.js
test/local/routes/account.js
test/local/routes/account_unblock.js

This PR removes all feature flag related code for sign-in unblock 🎓🎉!
Fixes #1644 

refactor(unblock): Graduate sign-in unblock

---

docs/api.md

fix(docs): Document that devices should reigster before attempting to sync

---

lib/routes/account.js
test/local/routes/account_devices.js

fix(push): don't wait on push methods to reply in account/devices/notify

---

npm-shrinkwrap.json
test/remote/db_tests.js

Fixes https://github.com/mozilla/fxa-auth-server/issues/1682

fix(db): update to latest db

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Release v1.82.0

---

config/index.js
lib/routes/account.js
test/local/ip_profiling.js
test/local/routes/account.js
test/local/routes/account_devices.js
test/local/routes/account_unblock.js
test/local/routes/recovery_email.js
test/remote/device_tests.js
test/remote/password_forgot_tests.js

fix(push): add extra validation to pushCallback payload param

---

docs/api.md
lib/routes/account.js
lib/routes/session.js
test/client/api.js
test/local/routes/account.js
test/local/routes/session.js
test/mocks.js
test/remote/session_destroy_tests.js

Connects to https://github.com/mozilla/fxa-content-server/issues/4585

feat(sessions): add /sessions support

---

lib/routes/session.js
test/remote/session_destroy_tests.js

fix(sessions): improve tests and fix incorrect buffer conversion

---

lib/metrics/events.js
test/local/metrics/events.js

We should not emit the route summary event if the metrics context payload is invalid. This fixes that.

fix(metrics): suppress route flow events if metrics context is invalid

---

lib/db.js
lib/tokens/token.js
test/local/tokens/session_token.js
test/remote/db_tests.js

See discussion in [bug 1330272](https://bugzilla.mozilla.org/show_bug.cgi?id=1330272).

fix(tokens): ensure account reset tokens get a fresh createdAt

---

lib/senders/email.js
mailer/config.js
test/local/lib/senders/email.js

https://github.com/mozilla/fxa-auth-mailer/pull/263/files
Fixes https://github.com/mozilla/fxa/issues/230

fix(mailer): fix sender from field. uplift

---

lib/routes/defaults.js

refs: bug 1320217 
similar to: https://github.com/mozilla/fxa-content-server/pull/4804
Fix commend execution in the unlikely event the application is run from a location with a malicious or malformed directory name per rfk's suggestions in the bug mentioned above.
Functional Tests:
```
fxa-local-dev/fxa-auth-server - [master] » curl -X GET http://localhost:9000/__version__
{
"version": "1.82.1",
"commit": "usage: git [--version] [--help] [-C <path>] [-c name=value]\n           [--exec-path[=<path>]] [--html-path] [--man-path$
[--info-path]\n           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=
<path>] [--namespace=<name>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a …
```

fix(version): use cwd and env var to get version in dev

---

bin/key_server.js
config/index.js
docs/api.md
lib/db.js
lib/error.js
lib/routes/account.js
lib/routes/password.js
lib/senders/index.js
npm-shrinkwrap.json
scripts/write-emails-to-disk.js
test/local/lib/mailer_locales.js
test/local/lib/senders/index.js
test/local/routes/account.js
test/local/routes/password.js
test/mocks.js
test/test_server.js

feat(mailer): check for hard bounced or complaints before sending emails

---

docs/metrics-events.md

Realised I hadn't updated this for a while, seemed like a good time.

chore(docs): update the metrics documentation

---

test/local/lib/senders/email.js

fix(tests): fix bad assertion in mailer tests

---

config/index.js
lib/routes/sms.js
test/local/routes/sms.js

chore(config): change SMS region config from regex to array

---

test/mail_helper.js

chore(test): fix mail_helper to run if require.main is mail_helper

---

bin/profile_server_messaging.js
config/index.js
docs/pushpayloads.schema.json
lib/profile/updates.js
lib/push.js
lib/routes/account.js
test/local/profile/updates.js
test/local/routes/account_devices.js

Connects to https://github.com/mozilla/fxa-features/issues/118
Disregard the structural changes in the JSON schema.

feat(profile): send push notifications after a profile update

---

lib/routes/account.js
lib/routes/password.js
lib/senders/index.js
test/local/lib/senders/index.js
test/local/routes/password.js

This PR is phase 1 of https://github.com/mozilla/fxa-auth-server/pull/1729#issuecomment-289026998 and connects to #1672. It normalizes all `mailer.*` function params to `(emails, account, opts)`. This allows us to have a common interface to send email to multiple addresses.

feat(emails): Mailer accept multiple emails Part 1

---

test/local/routes/account_devices.js

Tests are failing for me in `master` without this.

fix(tests): add missing require statement

---

lib/metrics/events.js
lib/server.js
test/local/lib/server.js
test/local/metrics/events.js
test/mocks.js

Pulling in from https://github.com/mozilla/fxa-auth-server-private/pull/62.

fix(server): remove crippled isLocaleAcceptable functionality

---

lib/metrics/events.js
lib/server.js
test/local/metrics/events.js
test/local/server.js
test/mocks.js

Uplift locale fix from train 83, https://github.com/mozilla/fxa-auth-server/pull/1793

fix(locale): Remove locale regex uplift from t83

---

CHANGELOG.md
lib/metrics/events.js
lib/server.js
npm-shrinkwrap.json
package.json
test/local/metrics/events.js
test/local/server.js
test/mocks.js

fix(locale): Fix merge conflicts (#1794)

---

lib/routes/defaults.js
test/remote/misc_tests.js

fix(routes): Add a /__lbheartbeat__ route.

---

config/index.js

fix(config): update the default SMS install link

---

config/index.js
test/local/bounces.js

fix(config): change default BOUNCES_SOFT_DURATION to '5 minutes'

---

bin/mailer_server.js
config/index.js

fix(mailer): bring back process ports for mailer_server.js

---

lib/metrics/context.js

fix(metrics): fix metrics context errors

---

config/index.js
lib/routes/sms.js
test/local/routes/sms.js

r? @philbooth 
Not sure what to stuff in as plausible dummy numbers in RO and GB, but the values shouldn't matter to the actual test.

fix(sms); DRY up sms.{regions,senderIds}

---

bin/key_server.js

fix(notifier): disable notifier in key_server.js

---

bin/mailer_server.js
npm-shrinkwrap.json
package.json

refs: bmo bug 1320211
Rebased from https://github.com/mozilla/fxa-auth-server/pull/1804

fix(mailer): escape json output

---

circle.yml

feat(docker): add feature branches

---

circle.yml

Similar to https://github.com/mozilla/fxa-content-server/pull/5019
r? - @jbuck, @vladikoff

fix(circle): if branch master, tag is latest

---

lib/metrics/context.js
test/local/metrics/context.js

Fixes #1817 
@jrgm / @vbudhram r?

fix(metrics): handle and log missing payload

---

test/remote/device_tests.js

Adding a test for https://bugzilla.mozilla.org/show_bug.cgi?id=1348298, I want to see if it'll fail in our CI environment.

fix(devices): Add test for unicode device names.

---

config/index.js
test/remote/device_tests.js

Fixes #1799 
@vbudhram r? 
#RegexFridays

fix(push): add support for dev and stage push servers

---

docs/metrics-events.md

There are a couple improvements (well, I hope they're improvements) contained herein:
* I've added an index, linking to each section of the doc.
* I've added new sections to document view names, action names, experiment names
and template names in the events.
Hopefully this makes things clearer to people consuming our events in redash.
The docs for view names aren't complete, if anyone can suggest suitable descriptions for the missing ones I'd be most grateful. Alternatively we can leave them blank for now and they can be filled in when people have time or whatever.

fix(docs): overhaul the metrics events documentation

---

config/index.js
docs/api.md
lib/db.js
lib/features.js
lib/routes/index.js
lib/routes/sms.js
lib/senders/sms.js
lib/server.js
scripts/api-docs.handlebars
scripts/write-api-docs.js
test/client/api.js
test/client/index.js
test/local/features.js
test/local/routes/sms.js
test/local/senders/sms.js
test/local/server.js
test/mocks.js
test/remote/db_tests.js
test/remote/sms_tests.js

Fixes #1883. ~~Must not be merged until after mozilla/fxa-content-server#5082.~~
Optionally updates the SMS install link to point at the content server and include the new signinCode.
/cc @shane-tomlinson

feat(server): include signinCode in the installFirefox SMS

---

test/mail_helper.js

Here's what it looks like in the console:

feat(sms): Show SMS links in the mail helper.

---

docs/metrics-events.md

Fixes #1905 
@mozilla/fxa-devs   r?

feat(emails): Add email metrics documentation

---

docs/metrics-events.md

fixes #1712 
@philbooth - this isn't ready yet, but is this the general format you are going for?

fix(CAD): Document CAD flow events.

---

test/mail_helper.js

fix(tests): add CC suport to mail_helper

---

test/load/loadtests.py

This fixes #1828 by using the restmail utilities in `PyFxA` to perform session confirmation if required.  It means we hit restmail on occasion in the middle of the loadtest, but since the bulk of requests are not login related I don't think it'll make a huge difference overall.  I also took the opportunity to make the password-reset test actual codes as well, for good measure.
With this patch I can consistently get `make bench` to pass cleanly against latest stage environment.
@jrgm r?

fix(tests): Update loadtests to cope with sign-in confirmation

---

docs/metrics-events.md

I didn't format the table correctly.

fix(CAD): Fix connectMethod table formatting.

---

docs/metrics-events.md

chore(docs): document the newsletter flow events

---

lib/push.js
test/local/push.js

WIP
fixes https://github.com/mozilla/fxa-auth-server/issues/1956

fix(ios): dont send non collection change notifs to ios devices

---

Dockerfile-build

feat(node): upgrade to Nodejs 6!!!

---

npm-shrinkwrap.json
test/remote/db_tests.js

@vbudhram, this updates the tests to match mozilla/fxa-auth-db-mysql#259, which has now been merged.
r?

fix(tests): update db tests to match recent session token changes

---

Dockerfile-build

This must get tagged in 1.91.1.

fix(nodejs): update to 6.11.1 for security fixes

---

config/index.js

fix(config): set token updates to true by default

---

npm-shrinkwrap.json
package.json
test/remote/db_tests.js

fix(tests): update tests to match recent db changes

---

docs/api.md
lib/db.js
lib/routes/devices-sessions.js
test/local/routes/devices-sessions.js
test/remote/db_tests.js

https://github.com/mozilla/fxa-auth-server/issues/2008

2008 - two timestamps for devices and sessions

---

lib/senders/partials/base/base.html
lib/senders/templates/new_device_login.html
lib/senders/templates/password_changed.html
lib/senders/templates/password_reset.html
lib/senders/templates/post_verify.html
lib/senders/templates/post_verify_secondary.html
lib/senders/templates/recovery.html
lib/senders/templates/unblock_code.html
lib/senders/templates/verification_reminder_first.html
lib/senders/templates/verification_reminder_second.html
lib/senders/templates/verify.html
lib/senders/templates/verify_login.html
lib/senders/templates/verify_secondary.html
lib/senders/templates/verify_sync.html

feat(style): update to new device image

---

docs/api.md
lib/db.js
lib/routes/devices-sessions.js
lib/routes/sign.js
test/local/db.js
test/local/routes/devices-sessions.js
test/remote/db_tests.js

cc: @vladikoff , @philbooth 
Fixes https://github.com/mozilla/fxa-auth-server/issues/1967

add location to sessions query

---

AUTHORS

chore(docs): update AUTHORS list

---

config/index.js
lib/routes/emails.js
test/local/routes/emails.js

Fixes https://github.com/mozilla/fxa-auth-server/issues/1792
cc: @vladikoff

chore(logs): add log when stale emails hit recovery endpoint

---

lib/db.js
test/remote/db_tests.js

fixes https://github.com/mozilla/fxa-auth-server/issues/2025
cc; @rfk @vladikoff

fix(redisSessions): improve redis session lookup performance

---

lib/db.js
test/remote/db_tests.js

train-92-patches

---

lib/routes/account.js
test/local/routes/account.js
test/remote/recovery_email_change_email.js

fix(email): Fix issue where you couldn't delete account after email change

---

docs/metrics-events.md

If this document was a car, I would have traded it in long ago for something that needs servicing less often. Sadly it is not a car.

chore(docs): regular maintenance for the metrics doc

---

lib/routes/emails.js
test/local/routes/emails.js
test/mocks.js

This PR Fixes #2017 and adds some extra change email coverage in local tests.

fix(push): Send push notification to devices when email has changed

---

lib/senders/sms.js

Did this for a spot of light relief. No logic changes, just something to get the ball rolling in `lib/senders` now that we can.

refactor(sms): unleash es6 in senders/sms

---

lib/routes/emails.js
test/local/routes/emails.js

Fixes #2042 
Failing test does not appear to be related to these changes. Blocked on https://github.com/mozilla/fxa-auth-server/issues/2067

feat(email): Notify services when user changes primary email

---

docs/api.md

Per https://github.com/mozilla/fxa-auth-server/pull/2089#discussion_r136907824; @philbooth r?

chore(docs): Auto-generated docs update

---

lib/email/bounces.js
test/local/email/bounce.js

Different mail servers format the addresses in their bounce messages in different ways, not all of them strictly RFC compliant.  This change makes us more lenient in what we accept, so that we don't error out
when receiving a bounce from a noncompliant server, so long as the result ends up looking like a valid email address.
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1393961; @jrgm r?

fix(bounces): Handle mis-formatted bounce addrs as best we can.

---

.gitignore
grunttasks/l10n-extract.js
lib/senders/translator.js
scripts/download_l10n.sh

Fixes #1678 
@seanmonstar @mozilla/fxa-devs r?

refactor(l10n): take l10n repo out of node_modules

---

lib/profile/updates.js
test/local/profile/updates.js

Just makes activity show in the logging
r? - @eoger

fix(profile): progress logging for handleProfileUpdated

---

lib/senders/index.js
test/local/senders/index.js

Previously, having a gated primary and unverified secondary would cause us to attempt to send an email to `undefined`, producing a 500 Server Error.  We now cleanly error out with the correct bounce-related error code.
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1395348#c20; @vbudhram r?

fix(email): Block sending if gated primary and unverified secondary.

---

docs/api.md
lib/devices.js
lib/routes/validators.js
npm-shrinkwrap.json
test/local/routes/devices-sessions.js
test/remote/device_tests.js

Connects to https://github.com/mozilla/fxa-auth-db-mysql/issues/229

feat(db): allow BMP chars in device name

---

test/local/email/bounce.js

This was annoying me.
Before:
```
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․(node:76399) Warning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․ …
```

fix(tests): silence obnoxious "possible memory leak detected" warning

---

lib/routes/password.js
test/local/routes/password.js

feat(password): notify attached services when a user changes their password

---

config/index.js
lib/server.js
npm-shrinkwrap.json
package.json

Fixes https://github.com/mozilla/fxa-auth-server/issues/2115
@vbudhram r?

feat(logs): add Sentry integration

---

lib/server.js
test/local/server.js

Fixes #2096.
Defines lazy getters for the remaining properties on `request.app`: `remoteAddressChain`, `clientAddress`, `acceptLanguage` and `locale`. None of them were hugely costly afaik, but the lazy getters thing is so marvellous that I think it should be the default pattern for accessing these.

feat(server): lazily get all request.app properties

---

lib/db.js
lib/devices.js
lib/routes/devices-and-sessions.js

Same as #2122 (tests not activated on my repo)

fix(push): return pushEndpointExpired as a boolean

---

docs/api.md
lib/error.js
lib/routes/emails.js
test/remote/recovery_email_resend_code_tests.js

feat(email): Fail when resending email code for email not on account

---

lib/routes/devices-and-sessions.js
test/remote/device_tests.js

fix(devices): return the whole device record in POST /device response

---

.nsprc
npm-shrinkwrap.json
package.json

fix(deps): update deps

---

lib/routes/sign.js
test/local/routes/sign.js

Fixes bz1403275
Ref https://github.com/mozilla/fxa-bugzilla-mirror/issues/378
r? @jrgm or @rfk or it could be you

fix(sessions): update the access time on /sign checking

---

config/index.js
test/local/bounces.js

As discussed on the mailing list; @vbudhram r?

fix(email): Make blocking rule for complaints match that for hard bounces

---

docs/pushpayloads.schema.json
lib/push.js
lib/routes/devices-and-sessions.js
test/local/push.js
test/local/routes/devices-and-sessions.js

This is the server-part of [bug 1400925](https://bugzilla.mozilla.org/show_bug.cgi?id=1400925)

feat(push): Drop collection_changed push notifications for first sync sent to iOS devices

---

config/dev.json

fix(config): add smsmock to dev config

---

lib/push.js
lib/routes/devices-and-sessions.js
test/local/routes/devices-and-sessions.js

fix(push): Allow sending verification messages from /devices/notify

---

lib/log.js
test/local/routes/account.js

feat(sqs): Add timestamp to notify services sqs message

---

lib/db.js
lib/features.js
test/remote/db_tests.js

Hopefully fixes #2142, pushing for CI

fix(devices): Avoid reporting stale last-access times when feature is disabled.

---

lib/metrics/amplitude.js
lib/routes/emails.js
lib/senders/email.js
lib/senders/index.js
lib/senders/partials/verify_primary.html
lib/senders/templates/_versions.json
lib/senders/templates/index.js
lib/senders/templates/verify_primary.html
lib/senders/templates/verify_primary.txt
test/client/api.js
test/local/metrics/amplitude.js
test/local/senders/email.js
test/local/senders/templates.js
test/remote/account_reset_tests.js
test/remote/flow_tests.js
test/remote/password_forgot_tests.js
test/remote/recovery_email_resend_code_tests.js
test/remote/session_tests.js

feat(session): Add verify primary email templates

---

package.json
scripts/template-version-bump.js

Fixes #2186.
@vbudhram, I couldn't be bothered with my other suggestion so I opted just to do your reminder idea. Includes a switch to disable the reminder so that it doesn't annoy people when run on pre-commit. You need to run the script manually for the reminder to show up.

feat(scripts): warn about no work in email template version bumper

---

lib/senders/partials/verify_primary.html
lib/senders/templates/_versions.json
lib/senders/templates/verify_primary.html

fix(email): add missing whitespace after semi-colon

---

test/local/routes/devices-and-sessions.js

The weird `language` property in mentioned in #2199 led me to update these tests, I should have been more comprehensive in #2188. The changes don't uncover any issues in the code, but they do exercise it more rigorously.

fix(tests): add local test coverage for english device locations

---

lib/senders/partials/base/base.html
lib/senders/templates/new_device_login.html
lib/senders/templates/password_changed.html
lib/senders/templates/password_reset.html
lib/senders/templates/post_change_primary.html
lib/senders/templates/post_remove_secondary.html
lib/senders/templates/post_verify.html
lib/senders/templates/post_verify_secondary.html
lib/senders/templates/recovery.html
lib/senders/templates/unblock_code.html
lib/senders/templates/verification_reminder_first.html
lib/senders/templates/verification_reminder_second.html
lib/senders/templates/verify.html
lib/senders/templates/verify_login.html
lib/senders/templates/verify_primary.html
lib/senders/templates/verify_secondary.html
lib/senders/templates/verify_sync.html

fix(logo): fix FF57 logo width and height

---

Dockerfile-build

chore(nodejs): update to 6.12.0

---

config/index.js
docs/api.md

feat(sms): Enable SMS in Spain (ES), Portugal (PT), Italy (IT)

---

lib/routes/emails.js
test/local/routes/emails.js

chore(email): remove check_can_add_secondary_address route

---

.nsprc

Related to moment/moment#4163.

chore(nsp): ignore warning about redos for date parsing in moment

---

config/index.js
docs/api.md

feat(sms): Enable SMS in Denmark (DK) and the Netherlands (NL)

---

lib/routes/devices-and-sessions.js
test/local/routes/devices-and-sessions.js

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1423015; @eoger r? if this makes sense as a fix to that bug.

fix(push): Send a notification to the device that's being disconnected.

---

lib/routes/emails.js
test/local/routes/emails.js
test/mocks.js
test/remote/recovery_email_emails.js

Fixes https://github.com/mozilla/fxa-auth-server/issues/2141

feat(codes): don't send delete notification when deleting unverified email

---

config/index.js

feat(sms): Enable SMS in australia

---

test/local/server.js

Related to mozilla/fxa-content-server#5817.

fix(tests): fix failing geolocation tests

---

lib/db.js
test/local/db.js

Related to the conversation in #2260, this just updates `db.deleteSessionToken` so that it always writes the packed format to Redis. It will save a bit more space for us, but doesn't fix any issues.

fix(redis): pack redis tokens inside db.deleteSessionToken

---

bin/key_server.js
lib/db.js
lib/email/utils/helpers.js
lib/geodb.js
lib/metrics/amplitude.js
lib/routes/account.js
lib/routes/emails.js
lib/routes/password.js
lib/routes/sms.js
lib/routes/unblock-codes.js
npm-shrinkwrap.json
package.json
test/local/db.js
test/local/email/utils.js
test/local/geodb.js
test/local/routes/sign.js
test/local/routes/sms.js
test/local/server.js
test/mocks.js
test/remote/db_tests.js

Updates `fxa-geodb` to `1.0.0` and removes the associated promise-handling code.

chore(deps): update fxa-geodb

---

lib/routes/emails.js
test/local/routes/emails.js
test/remote/recovery_email_emails.js

As noted as a helpful mitigation in https://bugzilla.mozilla.org/show_bug.cgi?id=1432477#c2

fix(emails): Reset account tokens when deleting an email address.

---

lib/metrics/events.js
test/local/metrics/events.js

Related to mozilla/fxa-amplitude-send#27. I don't think it's the killer fix we're looking for, although we won't know for sure until we've deployed it so I've opened this against train 104 for a prospective patch release.
Anyway, thanks to @jbuck's help in https://github.com/mozilla/fxa-amplitude-send/issues/27#issuecomment-360914147, we know that the primary cause for missing user properties on auth server Amplitude events is a missing `device_id` that can link them back to the content server events. As a consequence, I've been looking through both code bases for possible causes of that scenario.
The issue here was that we were only calling `metricsContext.gather` for flow events, which meant there was a code path for Amplitude that would never have metrics context (both `device_id` and …

fix(metrics): ensure amplitude events always have a metrics context

---

package.json

chore(ci): stop setting USE_REDIS in the test invocations

---

config/index.js

feat(cad): change destination of CAD in email to FxA-controlled page

---

lib/senders/email.js
lib/senders/partials/password_reset.html
lib/senders/partials/recovery.html
lib/senders/templates/password_reset.html
lib/senders/templates/password_reset.txt
lib/senders/templates/recovery.html
lib/senders/templates/recovery.txt

Connets to https://github.com/mozilla/fxa-content-server/issues/5776
Ref: https://github.com/mozilla/fxa-content-server/pull/5896

feat(reset): improve reset for reliers

---

lib/email/bounces.js
test/local/email/bounce.js

Fixes https://github.com/mozilla/fxa-content-server/issues/5629
@rfk r?

feat(emails): delete bounced registrations

---

lib/log.js
lib/pool.js
lib/push.js
scripts/write-api-docs.js
test/client/api.js
test/client/index.js
test/local/ip_profiling.js
test/local/routes/account.js
test/local/routes/devices-and-sessions.js
test/local/routes/emails.js
test/local/routes/password.js
test/local/routes/session.js
test/local/routes/sign.js
test/local/routes/signin-codes.js
test/local/routes/sms.js
test/local/routes/token-codes.js
test/local/routes/totp.js
test/local/routes/unblock-codes.js

@vladikoff ! I have added the mentioned changes for #2308 .Thanks :)

used default parameters

---

docs/api.md
lib/routes/index.js
lib/routes/token-codes.js
test/local/routes/token-codes.js
test/remote/token_code_tests.js

Couldn't cleanly merge [train-106](https://github.com/mozilla/fxa-auth-server-private/commit/c7c42ab2fda53e0eacb7557a901fd7f65aca27d0), so uplifting commits.

chore(uplift): uplift token validation fixes

---

lib/crypto/hkdf.js
lib/routes/idp.js
test/client/index.js
test/local/crypto/butil.js
test/local/crypto/pbkdf2.js
test/local/crypto/scrypt.js
test/local/password.js
test/local/routes/emails.js
test/local/routes/password.js
test/local/tokens/forgot_password_token.js
test/local/tokens/key_fetch_token.js
test/local/tokens/session_token.js
test/mailer_helper.js
test/oauth_helper.js
test/remote/account_destroy_tests.js
test/remote/account_locale_tests.js
test/remote/db_tests.js
test/remote/misc_tests.js
test/remote/password_change_tests.js
test/remote/push_db_tests.js

Made changes to fix issue #2333 Migrate to 'Buffer.from'

Fixes issue #2333 Migrate to 'Buffer.from'

---

Dockerfile-build

Updating node to get the new URLSearchParams feature
cc @eoger

feat(node): update to node v6.13.1

---

config/index.js
docs/api.md
lib/customs.js
lib/db.js
lib/error.js
lib/metrics/amplitude.js
lib/routes/index.js
lib/routes/recovery-codes.js
lib/routes/totp.js
lib/senders/email.js
lib/senders/index.js
lib/senders/partials/post_consume_recovery_code.html
lib/senders/partials/post_new_recovery_codes.html
lib/senders/templates/_versions.json
lib/senders/templates/index.js
lib/senders/templates/post_consume_recovery_code.html
lib/senders/templates/post_consume_recovery_code.txt
lib/senders/templates/post_new_recovery_codes.html
lib/senders/templates/post_new_recovery_codes.txt
test/client/api.js
test/client/index.js
test/local/senders/email.js
test/local/senders/templates.js
test/mocks.js
test/remote/recovery_code_tests.js
test/remote/totp_tests.js

feat(totp): initial recovery codes

---

docs/api.md
lib/routes/emails.js
lib/routes/totp.js
npm-shrinkwrap.json
test/local/routes/totp.js
test/remote/totp_tests.js

Fixes https://github.com/mozilla/fxa-auth-server/issues/2351

fix(totp): require totp verified session to delete totp token

---

docs/api.md
lib/routes/recovery-codes.js
test/client/api.js
test/remote/recovery_code_tests.js

Fixes https://github.com/mozilla/fxa-js-client/pull/273#discussion_r177046600

fix(metrics): pass metricsContext to consumeRecoveryCode

---

config/dev.json
config/index.js
lib/notifier.js

PR to test goaws : fake sqs/sns server

goaws : test fake sqs/sns server

---

lib/metrics/amplitude.js
test/local/metrics/amplitude.js

fix(metrics): count 28 days per metric month

---

config/popular-email-domains.js
npm-shrinkwrap.json
package.json

Related to mozilla/fxa-content-server#6014.

chore(emails): use popular email domain list from fxa-shared

---

lib/authMethods.js
lib/tokens/session_token.js
test/client/index.js
test/local/authMethods.js
test/remote/recovery_code_tests.js

fix(recovery): set assurance level when verifying with recovery code

---

lib/routes/totp.js
test/local/customs.js

Connects to https://github.com/mozilla/fxa-customs-server/issues/226
Once https://github.com/mozilla/fxa-customs-server/pull/233 lands, this can be review.

feat(totp): rate limit totp verify actions

---

test/local/ip_profiling.js

The code in `test/local/ip_profiling.js` was pretty confusing. There was a bunch of mocking code at the top level, which duplicated the mocking code inside `makeRoutes`. Then some of the test bodies were mocking things a third time.
This changeset attempts to tidy all that up a bit. In doing so, it also replaces the home-baked mock log object that was being used with a prefab from `test/mocks.js`. This fixes #2383.

chore(tests): remove duplicate mocking code

---

docs/api.md
lib/routes/account.js
lib/routes/totp.js
lib/routes/utils/totp.js
test/client/api.js
test/client/index.js
test/remote/account_destroy_tests.js

Fixes https://github.com/mozilla/fxa-auth-server/issues/2312

fix(totp): check totp before account deletion

---

docs/api.md

Typo in the api.md

---

.nsprc
npm-shrinkwrap.json
package.json

fix(newrelic): update newrelic module

---

.nsprc

Unblocks https://github.com/mozilla/fxa-auth-server/pull/2429

fix(nsp): update nsp for constantinople

---

config/index.js
lib/routes/recovery-codes.js
lib/senders/email.js
lib/senders/index.js
lib/senders/partials/low_recovery_codes.html
lib/senders/templates/_versions.json
lib/senders/templates/index.js
lib/senders/templates/low_recovery_codes.html
lib/senders/templates/low_recovery_codes.txt
npm-shrinkwrap.json
package.json
test/local/senders/email.js
test/local/senders/templates.js
test/mailbox.js
test/remote/recovery_code_tests.js
test/remote/recovery_email_resend_code_tests.js

Connects to https://github.com/mozilla/fxa-auth-server/issues/2409
Blocked on https://github.com/mozilla/fxa-shared/pull/22
Low recovery codes email:

feat(emails): notify users when they are running low on recovery codes

---

lib/metrics/events.js
test/local/metrics/events.js

fix(metrics): don't emit route flow events for 404s

---

lib/devices.js
lib/pool.js
lib/push.js
lib/routes/devices-and-sessions.js
lib/routes/emails.js
lib/safe-url.js
test/e2e/push_tests.js
test/local/devices.js
test/local/pool.js
test/local/push.js
test/local/routes/devices-and-sessions.js
test/local/routes/emails.js
test/local/safe-url.js
test/mocks.js
test/remote/push_db_tests.js

These are some of the initial refactorings that @eoger did in service of #2328.  Let's land them independently to reduce review load on the follow-up work to that feature.  @eoger could you please take a look to ensure I haven't broken anything during rebase here?

Land preparatory refactorings for "messages" system.

---

CHANGELOG.md
docs/api.md
lib/routes/session.js
lib/routes/sign.js
npm-shrinkwrap.json
package.json
test/local/routes/sign.js
test/remote/account_signin_verification_tests.js
test/remote/totp_tests.js

chore(merge): Reverse merge v1.113.5-private into origin/master

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

chore(release): Reverse merge train-114 into master

---

docs/api.md
docs/recovery_keys.md
lib/db.js
lib/routes/account.js
lib/routes/index.js
lib/routes/password.js
lib/routes/recovery-keys.js
lib/routes/session.js
lib/routes/validators.js
npm-shrinkwrap.json
test/client/api.js
test/client/index.js
test/local/routes/account.js
test/local/routes/recovery-keys.js
test/mocks.js
test/remote/recovery_key_tests.js

Fixes https://github.com/mozilla/fxa-auth-server/issues/2421

feat(recovery): account recovery apis

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

For merge to master, because I can't push it there without review.

Release v1.115.0

---

lib/routes/sign.js
test/local/routes/sign.js
test/mocks.js

Fixes #2491.  Since this is affecting the lockbox app, I'd like to make it a point-release of train-115.  @mozilla/fxa-devs r?

fix(devices): Fix race between real and placeholder device registration.

---

lib/push.js
test/local/push.js

fix(push): send FxA commands push messages to iOS devices

---

lib/senders/email.js
test/local/senders/email.js

Fixes #2522.
Adding a `service` property to the `X-SES-MESSAGE-TAGS` header lets us track the email-sending service in AWS metrics. If something goes wrong with the new service, this will help ops to identify the problem.
While doing that, I also opted to rejig some of the surrounding code in `lib/senders/email.js`, which was unnecessarily repetitive in some parts and difficult to follow in others. I'll call those changes out in the inline comments but fwiw I also think there are far greater improvements still to be made in that module, if we pursue a more data-driven/functional approach to the whole thing.

feat(email): add a service property to the X-SES-MESSAGE-TAGS header

---

lib/routes/account.js
npm-shrinkwrap.json
package.json

Connects to https://github.com/mozilla/fxa-oauth-server/issues/575
Replaces ad-hoc scope-checking logic with the shared code from https://github.com/mozilla/fxa-shared/pull/21.  WIP until that lands, as I want to iterate on it in conjunction with the consuming code.

feat(scopes): Use shared code lib for checking OAuth scopes.

---

test/local/senders/email_service.js

Fixes #2509 
Just added the tests we discussed in https://github.com/mozilla/fxa-auth-server/issues/2509#issuecomment-405311459
r? @philbooth @vladikoff

chore(tests): add tests to email_service.js

---

lib/db.js
lib/redis/index.js
lib/redis/pool.js
scripts/delete-account.js
test/local/redis/index.js
test/local/redis/pool.js

Not working yet, pushing for visibility; @jbuck was this the sort of thing you had in mind for https://bugzilla.mozilla.org/show_bug.cgi?id=1477806 ?

feat(admin): Add an admin script to delete an account.

---

test/remote/recovery_code_tests.js
test/remote/totp_tests.js

Connects to https://github.com/mozilla/fxa-auth-server/issues/2534. This doesn't fix the issue but gives a more generous code window for totp tests to pass.

fix(test): increase totp code window

---

lib/server.js

Check my math.
r? - @vladikoff 
Fixes #2554

fix(sentry): server.events.on takes channels, not channel

---

lib/server.js
test/local/sentry.js

fix(tests): add a check from sentry setup

---

config/dev.json

Connects to https://github.com/mozilla/fxa-local-dev/pull/122

Activate pushbox in dev environments

---

lib/senders/email_service.js
test/local/senders/email_service.js

Fixes #2569 
ref: https://github.com/mozilla/fxa-email-service/pull/161/files#diff-dd02a9e1af125dcee823974d07d358b4R58
@brizental confirm?

feat(email): change the email service errno values to numbers

---

CHANGELOG.md
lib/routes/account.js
npm-shrinkwrap.json
package.json
scripts/delete-account.js

Uplift train-119 into master

---

npm-shrinkwrap.json
package.json
scripts/test-local.sh

fix(tests): update to mocha 5

---

npm-shrinkwrap.json

fix(mysql): fix pushbox mysql

---

CHANGELOG.md
lib/routes/devices-and-sessions.js
npm-shrinkwrap.json
package.json
test/local/routes/devices-and-sessions.js
test/remote/db_tests.js
test/remote/device_tests.js

Uplift from train-119 into master

Release v1.119.3

---

lib/db.js
lib/routes/recovery-key.js
npm-shrinkwrap.json
test/local/routes/recovery-keys.js
test/mocks.js

Blocked on https://github.com/mozilla/fxa-auth-db-mysql/pull/395
PR contains updates needed to support https://github.com/mozilla/fxa-auth-db-mysql/issues/366.

fix(recovery): update to support hashing recoveryKeyId

---

CHANGELOG.md
config/index.js
npm-shrinkwrap.json
package.json
test/local/geodb.js
test/local/server.js
test/remote/device_tests.js

Fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1489294

fix(push): support port numbers in push urls

---

lib/senders/partials/verify_login_code.html
lib/senders/templates/_versions.json
lib/senders/templates/verify_login_code.html
scripts/write-emails-to-disk.js

Fixes https://github.com/mozilla/fxa-content-server/issues/6567

fix(codes): increase token code font size in email

---

.travis.yml
Dockerfile-build
Dockerfile-test

fix(npm): use npm ci for npm install

---

lib/customs.js

Fixes https://github.com/mozilla/fxa-customs-server/issues/275

fix(customs): increase customs timeout to 3000ms

---

npm-shrinkwrap.json
package.json

chore(package): bump fxa-shared to 1.0.14 + npm shrinkwrap

---

lib/routes/devices-and-sessions.js
test/local/routes/devices-and-sessions.js

Mostly f.ixes #2653
30 days is the maximum TTL the Push server allows.

fix(commands): Assign default TTL to send-tab commands

---

grunttasks/l10n-extract.js
npm-shrinkwrap.json
package.json

chore(deps): Update commander, jsxgettext-recursive to remove security warnings.

---

docs/api.md
lib/error.js
lib/routes/account.js
lib/routes/utils/signin.js
test/local/routes/account.js

fix(email): throw error for failed emails during account creation

---

.travis.yml

This might have been fixed now...

fix(ci): remove geodb workaround

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Merge train-123 into master

---

CHANGELOG.md
lib/routes/account.js
npm-shrinkwrap.json
package.json
test/local/routes/account.js

Merge train 123 into master

---

fxa-oauth-server/lib/server/configureSentry.js
fxa-oauth-server/lib/server/index.js
fxa-oauth-server/test/sentry.js

Adds a test for #2717 
r? - @mozilla/fxa-devs

fix(test): check that Sentry can be configured if SENTRY_DSN is set

---

fxa-oauth-server/docs/api.md

chore(docs): add acr docs

---

fxa-oauth-server/config/dev.json

As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1503456

chore(clients): Add a client_id for the Reference Browser.

---

test/known-ip-location.js

fix(tests): add Santa Clara to known locations

---

lib/routes/totp.js
test/local/routes/totp.js
test/mocks.js

Fixes https://github.com/mozilla/fxa-content-server/issues/6649

fix(totp): don't send totp email with invalid code

---

CHANGELOG.md
fxa-oauth-server/npm-shrinkwrap.json
fxa-oauth-server/package.json
lib/metrics/amplitude.js
npm-shrinkwrap.json
package.json
test/local/metrics/amplitude.js

Merge train-126 into master

---

fxa-oauth-server/lib/config.js
fxa-oauth-server/lib/server/index.js
fxa-oauth-server/test/api.js

@jrgm r?
sorry @rfk we had to disable this, it's just makes it really messy due to fxa-dev boxes and NODE_ENV

fix(oauth): remove prod requirement flag

---

lib/senders/translator.js
test/local/senders/email.js

fix(emails): fix arabic emails, add translator tests

---

lib/senders/email_service.js
test/local/senders/email_service.js

fix(email): check for null header values in the email service file

---

Dockerfile-oauth-build

Fixes https://github.com/mozilla/fxa-dev/issues/412
Matches https://github.com/mozilla/fxa-auth-server/blob/master/Dockerfile-build#L26
@jrgm thoughts?

fix(docker): gen_keys in the OAuth docker container

---

CHANGELOG.md
fxa-oauth-server/npm-shrinkwrap.json
fxa-oauth-server/package.json
lib/routes/account.js
lib/routes/recovery-codes.js
npm-shrinkwrap.json
package.json
test/local/routes/account.js
test/local/routes/recovery-codes.js
test/mocks.js
test/remote/totp_tests.js

chore(release): Merge train-126 into train-127, bump patch number.

---

fxa-oauth-server/bin/purge_expired_tokens.js

Small fix from the package.json consolidation
r? - @mozilla/fxa-devs

fix(purge): adjust path to package.json

---

CHANGELOG.md
lib/routes/account.js
lib/routes/recovery-codes.js
npm-shrinkwrap.json
package.json
test/local/routes/account.js
test/local/routes/recovery-codes.js
test/mocks.js
test/remote/totp_tests.js

chore(release): Merge train-127 into master 

---

grunttasks/bump.js

This removes grunt bump for oauth-server.

chore(grunt): remove grunt bump for oauth-server

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Merge train-128 into master

---

CHANGELOG.md
lib/senders/oauth_client_info.js
npm-shrinkwrap.json
package.json
test/local/senders/oauth_client_info.js

* fix(log): use fatal instead of criticial in log
* Release v1.128.2

Release v1.128.2

---

CHANGELOG.md
lib/oauthdb.js
lib/routes/index.js
npm-shrinkwrap.json
package.json
test/local/oauthdb.js

This fixes the error that lockbox was hitting in prod earlier today, and adds a test for good measure.
ref https://bugzilla.mozilla.org/show_bug.cgi?id=1518249#c16

Fix oauth client name validation

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Release v1.128.5

---

lib/senders/partials/verify_primary.html
lib/senders/partials/verify_secondary.html
lib/senders/partials/verify_sync.html
lib/senders/templates/verify_primary.html
lib/senders/templates/verify_secondary.html
lib/senders/templates/verify_sync.html
lib/senders/templates/verify_sync.txt

fixes #2860.
@shane-tomlinson please review.

style(lib/senders): removed right arrows

---

CHANGELOG.md
lib/log.js
npm-shrinkwrap.json
package.json
test/local/log.js

Merge train-129 into master

---

lib/log.js
test/local/log.js

Adds `email`, `phoneNumber` and `method`
fixes #2858

feat(metrics): Emit additional data for the DataFlow fraud detection pipeline.

---

npm-shrinkwrap.json
package.json
test/local/metrics/amplitude.js

Updates fxa-shared so that it no longer uses the client_id as the entrypoint
issue mozilla/fxa-shared#46

fix(metrics): Fix entrypoint being overwritten for every event.

---

npm-shrinkwrap.json
package.json

issue mozilla/fxa-content-server-l10n#322

feat(l10n): Enable Catalan (ca)

---

fxa-oauth-server/lib/routes/key_data.js
fxa-oauth-server/test/api.js

Fixes #2908
Fixes https://github.com/mozilla-mobile/reference-browser/issues/569

fix(key-data): fix key-data endpoint for fresh accounts

---

fxa-oauth-server/config/dev.json

bz1528355
@vladikoff or @rfk - r?

chore(clients): Add a dev client_id for Fenix

---

.circleci/config.yml
.travis.yml
Dockerfile-build
Dockerfile-oauth-build
npm-shrinkwrap.json

Fixes #2923.
Does what it says on the tin, everything seems to work tickety-boo.

chore(deploy): upgrade to node 10

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Merge train-131 into master

---

CHANGELOG.md
fxa-oauth-server/lib/routes/token.js
fxa-oauth-server/test/api.js

Fixes https://github.com/mozilla/fxa-auth-server/issues/2938

Train 131 private uplift

---

lib/crypto/scrypt.js
npm-shrinkwrap.json
package.json

fix(node 8 and scrypt-hash): removed support for node 8 and scrypt-hash

---

scripts/email-config.js

Just a little note to the future.
r? - @philbooth

fix(docs): add note for ops on how to check raw redis email config

---

lib/routes/devices-and-sessions.js
test/remote/device_tests_refresh_tokens.js

fix(devices): return isCurrentDevice for refreshToken device endpoint

---

fxa-oauth-server/lib/config.js
fxa-oauth-server/lib/encrypt.js

fix(config): remove hash alg from config

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Merge train-134 into master
